// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type trip2g_admin_formnotes_catalog_listQueryVariables = Exact<{ [key: string]: never; }>;


export type trip2g_admin_formnotes_catalog_listQuery = { __typename?: 'Query', admin: { __typename?: 'AdminQuery', formNotes: Array<{ __typename?: 'AdminFormNote', id: string, path: string, pathId: any, submitCount: number, lastSubmitAt: any }> } };


export function $trip2g_admin_formnotes_catalog_list(opts?: { revalidate?: boolean }): trip2g_admin_formnotes_catalog_listQuery {
	return $trip2g_gql_request(`query trip2g_admin_formnotes_catalog_list {
  admin {
    formNotes {
      id
      path
      pathId
      submitCount
      lastSubmitAt
    }
  }
}`, undefined, opts) as trip2g_admin_formnotes_catalog_listQuery
}

}
