// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type trip2g_admin_personaltoken_catalog_listQueryVariables = Exact<{
  filter: AdminUserTokensFilterInput;
}>;


export type trip2g_admin_personaltoken_catalog_listQuery = { __typename?: 'Query', admin: { __typename?: 'AdminQuery', personalTokens: { __typename?: 'AdminUserTokensConnection', nodes: Array<{ __typename?: 'AdminUserToken', id: string, userId: any, name: string, tokenPrefix: string, createdAt: any, lastUsedAt?: any | null, expiresAt?: any | null, revokedAt?: any | null, user: { __typename?: 'AdminUser', id: any, email?: string | null } }> } } };


export function $trip2g_admin_personaltoken_catalog_list(variables: trip2g_admin_personaltoken_catalog_listQueryVariables, opts?: { revalidate?: boolean }): trip2g_admin_personaltoken_catalog_listQuery {
	return $trip2g_gql_request(`query trip2g_admin_personaltoken_catalog_list(\u0024filter: AdminUserTokensFilterInput!) {
  admin {
    personalTokens(filter: \u0024filter) {
      nodes {
        id
        userId
        name
        tokenPrefix
        createdAt
        lastUsedAt
        expiresAt
        revokedAt
        user {
          id
          email
        }
      }
    }
  }
}`, variables, opts) as trip2g_admin_personaltoken_catalog_listQuery
}

}
