// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type trip2g_admin_usersubgraphaccesses_show_dataQueryVariables = Exact<{
  id: Scalars['Int64']['input'];
}>;


export type trip2g_admin_usersubgraphaccesses_show_dataQuery = { __typename?: 'Query', admin: { __typename?: 'AdminQuery', allSubgraphs: { __typename?: 'AdminSubgraphsConnection', nodes: Array<{ __typename?: 'AdminSubgraph', id: any, name: string }> }, userSubgraphAccess?: { __typename?: 'AdminUserSubgraphAccess', userId: any, subgraphId: any, expiresAt?: any | null, revoke?: { __typename?: 'AdminRevoke', createdAt: any, reason?: string | null, by: { __typename?: 'AdminUser', id: any, email?: string | null } } | null } | null } };


export function $trip2g_admin_usersubgraphaccesses_show_data(variables: trip2g_admin_usersubgraphaccesses_show_dataQueryVariables, opts?: { revalidate?: boolean }): trip2g_admin_usersubgraphaccesses_show_dataQuery {
	return $trip2g_gql_request(`query trip2g_admin_usersubgraphaccesses_show_data(\u0024id: Int64!) {
  admin {
    allSubgraphs {
      nodes {
        id
        name
      }
    }
    userSubgraphAccess(id: \u0024id) {
      userId
      subgraphId
      expiresAt
      revoke {
        createdAt
        reason
        by {
          id
          email
        }
      }
    }
  }
}`, variables, opts) as trip2g_admin_usersubgraphaccesses_show_dataQuery
}

}
