// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type trip2g_admin_telegrampublishnote_show_showQueryVariables = Exact<{
  id: Scalars['Int64']['input'];
}>;


export type trip2g_admin_telegrampublishnote_show_showQuery = { __typename?: 'Query', admin: { __typename?: 'AdminQuery', telegramPublishNote?: { __typename?: 'AdminTelegramPublishNote', id: any, createdAt: any, publishAt: any, secondsUntilPublish: any, publishedAt?: any | null, status: string, lastError?: string | null, tags: Array<{ __typename?: 'AdminTelegramPublishTag', label: string }>, chats: Array<{ __typename?: 'AdminTgBotChat', chatTitle: string, chatType: string }>, noteView: { __typename?: 'NoteView', title: string }, post: { __typename?: 'TelegramPost', content: string, warnings: Array<string> } } | null } };


export function $trip2g_admin_telegrampublishnote_show_show(variables: trip2g_admin_telegrampublishnote_show_showQueryVariables, opts?: { revalidate?: boolean }): trip2g_admin_telegrampublishnote_show_showQuery {
	return $trip2g_gql_request(`query trip2g_admin_telegrampublishnote_show_show(\u0024id: Int64!) {
  admin {
    telegramPublishNote(id: \u0024id) {
      id
      createdAt
      publishAt
      secondsUntilPublish
      publishedAt
      status
      lastError
      tags {
        label
      }
      chats {
        chatTitle
        chatType
      }
      noteView {
        title
      }
      post {
        content
        warnings
      }
    }
  }
}`, variables, opts) as trip2g_admin_telegrampublishnote_show_showQuery
}

}
