// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type trip2g_user_paywall_conversationprompt_email_createMutationVariables = Exact<{
  input: CreateEmailWaitListRequestInput;
}>;


export type trip2g_user_paywall_conversationprompt_email_createMutation = { __typename?: 'Mutation', createEmailWaitListRequest: { __typename: 'CreateEmailWaitListRequestPayload', success: boolean } | { __typename: 'ErrorPayload', message: string } };


export function $trip2g_user_paywall_conversationprompt_email_create(variables: trip2g_user_paywall_conversationprompt_email_createMutationVariables, opts?: { revalidate?: boolean }): trip2g_user_paywall_conversationprompt_email_createMutation {
	return $trip2g_gql_request(`mutation trip2g_user_paywall_conversationprompt_email_create(\u0024input: CreateEmailWaitListRequestInput!) {
  createEmailWaitListRequest(input: \u0024input) {
    __typename
    ... on ErrorPayload {
      message
    }
    ... on CreateEmailWaitListRequestPayload {
      success
    }
  }
}`, variables, opts) as trip2g_user_paywall_conversationprompt_email_createMutation
}

}
