// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package simplebackup_test

import (
	"context"
	"database/sql"
	"io"
	"sync"
	"trip2g/internal/logger"
	"trip2g/internal/miniostorage"
	"trip2g/internal/model"
	"trip2g/internal/simplebackup"
)

// Ensure, that EnvMock does implement simplebackup.Env.
// If this is not the case, regenerate this file with moq.
var _ simplebackup.Env = &EnvMock{}

// EnvMock is a mock implementation of simplebackup.Env.
//
//	func TestSomethingThatUsesEnv(t *testing.T) {
//
//		// make and configure a mocked simplebackup.Env
//		mockedEnv := &EnvMock{
//			DBFunc: func() *sql.DB {
//				panic("mock out the DB method")
//			},
//			DeletePrivateObjectFunc: func(ctx context.Context, objectID string) error {
//				panic("mock out the DeletePrivateObject method")
//			},
//			GetPrivateObjectFunc: func(ctx context.Context, objectID string) (io.ReadCloser, error) {
//				panic("mock out the GetPrivateObject method")
//			},
//			ListPrivateObjectsFunc: func(ctx context.Context, opts miniostorage.ListOptions) ([]model.PrivateObject, error) {
//				panic("mock out the ListPrivateObjects method")
//			},
//			LoggerFunc: func() logger.Logger {
//				panic("mock out the Logger method")
//			},
//			PutPrivateObjectFunc: func(ctx context.Context, reader io.Reader, objectID string) error {
//				panic("mock out the PutPrivateObject method")
//			},
//		}
//
//		// use mockedEnv in code that requires simplebackup.Env
//		// and then make assertions.
//
//	}
type EnvMock struct {
	// DBFunc mocks the DB method.
	DBFunc func() *sql.DB

	// DeletePrivateObjectFunc mocks the DeletePrivateObject method.
	DeletePrivateObjectFunc func(ctx context.Context, objectID string) error

	// GetPrivateObjectFunc mocks the GetPrivateObject method.
	GetPrivateObjectFunc func(ctx context.Context, objectID string) (io.ReadCloser, error)

	// ListPrivateObjectsFunc mocks the ListPrivateObjects method.
	ListPrivateObjectsFunc func(ctx context.Context, opts miniostorage.ListOptions) ([]model.PrivateObject, error)

	// LoggerFunc mocks the Logger method.
	LoggerFunc func() logger.Logger

	// PutPrivateObjectFunc mocks the PutPrivateObject method.
	PutPrivateObjectFunc func(ctx context.Context, reader io.Reader, objectID string) error

	// calls tracks calls to the methods.
	calls struct {
		// DB holds details about calls to the DB method.
		DB []struct {
		}
		// DeletePrivateObject holds details about calls to the DeletePrivateObject method.
		DeletePrivateObject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ObjectID is the objectID argument value.
			ObjectID string
		}
		// GetPrivateObject holds details about calls to the GetPrivateObject method.
		GetPrivateObject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ObjectID is the objectID argument value.
			ObjectID string
		}
		// ListPrivateObjects holds details about calls to the ListPrivateObjects method.
		ListPrivateObjects []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Opts is the opts argument value.
			Opts miniostorage.ListOptions
		}
		// Logger holds details about calls to the Logger method.
		Logger []struct {
		}
		// PutPrivateObject holds details about calls to the PutPrivateObject method.
		PutPrivateObject []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Reader is the reader argument value.
			Reader io.Reader
			// ObjectID is the objectID argument value.
			ObjectID string
		}
	}
	lockDB                  sync.RWMutex
	lockDeletePrivateObject sync.RWMutex
	lockGetPrivateObject    sync.RWMutex
	lockListPrivateObjects  sync.RWMutex
	lockLogger              sync.RWMutex
	lockPutPrivateObject    sync.RWMutex
}

// DB calls DBFunc.
func (mock *EnvMock) DB() *sql.DB {
	if mock.DBFunc == nil {
		panic("EnvMock.DBFunc: method is nil but Env.DB was just called")
	}
	callInfo := struct {
	}{}
	mock.lockDB.Lock()
	mock.calls.DB = append(mock.calls.DB, callInfo)
	mock.lockDB.Unlock()
	return mock.DBFunc()
}

// DBCalls gets all the calls that were made to DB.
// Check the length with:
//
//	len(mockedEnv.DBCalls())
func (mock *EnvMock) DBCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockDB.RLock()
	calls = mock.calls.DB
	mock.lockDB.RUnlock()
	return calls
}

// DeletePrivateObject calls DeletePrivateObjectFunc.
func (mock *EnvMock) DeletePrivateObject(ctx context.Context, objectID string) error {
	if mock.DeletePrivateObjectFunc == nil {
		panic("EnvMock.DeletePrivateObjectFunc: method is nil but Env.DeletePrivateObject was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		ObjectID string
	}{
		Ctx:      ctx,
		ObjectID: objectID,
	}
	mock.lockDeletePrivateObject.Lock()
	mock.calls.DeletePrivateObject = append(mock.calls.DeletePrivateObject, callInfo)
	mock.lockDeletePrivateObject.Unlock()
	return mock.DeletePrivateObjectFunc(ctx, objectID)
}

// DeletePrivateObjectCalls gets all the calls that were made to DeletePrivateObject.
// Check the length with:
//
//	len(mockedEnv.DeletePrivateObjectCalls())
func (mock *EnvMock) DeletePrivateObjectCalls() []struct {
	Ctx      context.Context
	ObjectID string
} {
	var calls []struct {
		Ctx      context.Context
		ObjectID string
	}
	mock.lockDeletePrivateObject.RLock()
	calls = mock.calls.DeletePrivateObject
	mock.lockDeletePrivateObject.RUnlock()
	return calls
}

// GetPrivateObject calls GetPrivateObjectFunc.
func (mock *EnvMock) GetPrivateObject(ctx context.Context, objectID string) (io.ReadCloser, error) {
	if mock.GetPrivateObjectFunc == nil {
		panic("EnvMock.GetPrivateObjectFunc: method is nil but Env.GetPrivateObject was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		ObjectID string
	}{
		Ctx:      ctx,
		ObjectID: objectID,
	}
	mock.lockGetPrivateObject.Lock()
	mock.calls.GetPrivateObject = append(mock.calls.GetPrivateObject, callInfo)
	mock.lockGetPrivateObject.Unlock()
	return mock.GetPrivateObjectFunc(ctx, objectID)
}

// GetPrivateObjectCalls gets all the calls that were made to GetPrivateObject.
// Check the length with:
//
//	len(mockedEnv.GetPrivateObjectCalls())
func (mock *EnvMock) GetPrivateObjectCalls() []struct {
	Ctx      context.Context
	ObjectID string
} {
	var calls []struct {
		Ctx      context.Context
		ObjectID string
	}
	mock.lockGetPrivateObject.RLock()
	calls = mock.calls.GetPrivateObject
	mock.lockGetPrivateObject.RUnlock()
	return calls
}

// ListPrivateObjects calls ListPrivateObjectsFunc.
func (mock *EnvMock) ListPrivateObjects(ctx context.Context, opts miniostorage.ListOptions) ([]model.PrivateObject, error) {
	if mock.ListPrivateObjectsFunc == nil {
		panic("EnvMock.ListPrivateObjectsFunc: method is nil but Env.ListPrivateObjects was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Opts miniostorage.ListOptions
	}{
		Ctx:  ctx,
		Opts: opts,
	}
	mock.lockListPrivateObjects.Lock()
	mock.calls.ListPrivateObjects = append(mock.calls.ListPrivateObjects, callInfo)
	mock.lockListPrivateObjects.Unlock()
	return mock.ListPrivateObjectsFunc(ctx, opts)
}

// ListPrivateObjectsCalls gets all the calls that were made to ListPrivateObjects.
// Check the length with:
//
//	len(mockedEnv.ListPrivateObjectsCalls())
func (mock *EnvMock) ListPrivateObjectsCalls() []struct {
	Ctx  context.Context
	Opts miniostorage.ListOptions
} {
	var calls []struct {
		Ctx  context.Context
		Opts miniostorage.ListOptions
	}
	mock.lockListPrivateObjects.RLock()
	calls = mock.calls.ListPrivateObjects
	mock.lockListPrivateObjects.RUnlock()
	return calls
}

// Logger calls LoggerFunc.
func (mock *EnvMock) Logger() logger.Logger {
	if mock.LoggerFunc == nil {
		panic("EnvMock.LoggerFunc: method is nil but Env.Logger was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLogger.Lock()
	mock.calls.Logger = append(mock.calls.Logger, callInfo)
	mock.lockLogger.Unlock()
	return mock.LoggerFunc()
}

// LoggerCalls gets all the calls that were made to Logger.
// Check the length with:
//
//	len(mockedEnv.LoggerCalls())
func (mock *EnvMock) LoggerCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLogger.RLock()
	calls = mock.calls.Logger
	mock.lockLogger.RUnlock()
	return calls
}

// PutPrivateObject calls PutPrivateObjectFunc.
func (mock *EnvMock) PutPrivateObject(ctx context.Context, reader io.Reader, objectID string) error {
	if mock.PutPrivateObjectFunc == nil {
		panic("EnvMock.PutPrivateObjectFunc: method is nil but Env.PutPrivateObject was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Reader   io.Reader
		ObjectID string
	}{
		Ctx:      ctx,
		Reader:   reader,
		ObjectID: objectID,
	}
	mock.lockPutPrivateObject.Lock()
	mock.calls.PutPrivateObject = append(mock.calls.PutPrivateObject, callInfo)
	mock.lockPutPrivateObject.Unlock()
	return mock.PutPrivateObjectFunc(ctx, reader, objectID)
}

// PutPrivateObjectCalls gets all the calls that were made to PutPrivateObject.
// Check the length with:
//
//	len(mockedEnv.PutPrivateObjectCalls())
func (mock *EnvMock) PutPrivateObjectCalls() []struct {
	Ctx      context.Context
	Reader   io.Reader
	ObjectID string
} {
	var calls []struct {
		Ctx      context.Context
		Reader   io.Reader
		ObjectID string
	}
	mock.lockPutPrivateObject.RLock()
	calls = mock.calls.PutPrivateObject
	mock.lockPutPrivateObject.RUnlock()
	return calls
}
