// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type trip2g_admin_oauth_github_delete_confirmMutationVariables = Exact<{
  input: DeleteGitHubOAuthCredentialsInput;
}>;


export type trip2g_admin_oauth_github_delete_confirmMutation = { __typename?: 'Mutation', admin: { __typename?: 'AdminMutation', data: { __typename: 'DeleteGitHubOAuthCredentialsPayload', deletedId: any } | { __typename: 'ErrorPayload', message: string } } };


export function $trip2g_admin_oauth_github_delete_confirm(variables: trip2g_admin_oauth_github_delete_confirmMutationVariables, opts?: { revalidate?: boolean }): trip2g_admin_oauth_github_delete_confirmMutation {
	return $trip2g_gql_request(`mutation trip2g_admin_oauth_github_delete_confirm(\u0024input: DeleteGitHubOAuthCredentialsInput!) {
  admin {
    data: deleteGitHubOAuthCredentials(input: \u0024input) {
      __typename
      ... on ErrorPayload {
        message
      }
      ... on DeleteGitHubOAuthCredentialsPayload {
        deletedId
      }
    }
  }
}`, variables, opts) as trip2g_admin_oauth_github_delete_confirmMutation
}

}
