// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type trip2g_admin_frontmatterpatch_catalog_listQueryVariables = Exact<{ [key: string]: never; }>;


export type trip2g_admin_frontmatterpatch_catalog_listQuery = { __typename?: 'Query', admin: { __typename?: 'AdminQuery', allFrontmatterPatches: { __typename?: 'AdminFrontmatterPatchesConnection', nodes: Array<{ __typename?: 'AdminFrontmatterPatch', id: any, description: string, priority: number, enabled: boolean, includePatterns: Array<string>, excludePatterns: Array<string> }> } } };


export function $trip2g_admin_frontmatterpatch_catalog_list(opts?: { revalidate?: boolean }): trip2g_admin_frontmatterpatch_catalog_listQuery {
	return $trip2g_gql_request(`query trip2g_admin_frontmatterpatch_catalog_list {
  admin {
    allFrontmatterPatches {
      nodes {
        id
        description
        priority
        enabled
        includePatterns
        excludePatterns
      }
    }
  }
}`, undefined, opts) as trip2g_admin_frontmatterpatch_catalog_listQuery
}

}
