// Code generated by qtc from "plain.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line plain.qtpl:1
package sendformsubmit

//line plain.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line plain.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line plain.qtpl:1
func StreamPlainView(qw422016 *qt422016.Writer, p *Params) {
//line plain.qtpl:1
	qw422016.N().S(`
New form submission on `)
//line plain.qtpl:2
	qw422016.E().S(p.NotePath)
//line plain.qtpl:2
	qw422016.N().S(`

Submitted: `)
//line plain.qtpl:4
	qw422016.E().S(p.SubmittedAt)
//line plain.qtpl:4
	qw422016.N().S(`
User: `)
//line plain.qtpl:5
	qw422016.E().S(p.UserInfo)
//line plain.qtpl:5
	qw422016.N().S(`
IP: `)
//line plain.qtpl:6
	qw422016.E().S(p.IP)
//line plain.qtpl:6
	qw422016.N().S(`

Fields:
`)
//line plain.qtpl:9
	for _, f := range p.Fields {
//line plain.qtpl:9
		qw422016.N().S(`
  `)
//line plain.qtpl:10
		qw422016.E().S(f.Name)
//line plain.qtpl:10
		qw422016.N().S(`: `)
//line plain.qtpl:10
		qw422016.E().S(f.Value)
//line plain.qtpl:10
		qw422016.N().S(`
`)
//line plain.qtpl:11
	}
//line plain.qtpl:11
	qw422016.N().S(`

View in admin: `)
//line plain.qtpl:13
	qw422016.E().S(p.AdminURL)
//line plain.qtpl:13
	qw422016.N().S(`
`)
//line plain.qtpl:14
}

//line plain.qtpl:14
func WritePlainView(qq422016 qtio422016.Writer, p *Params) {
//line plain.qtpl:14
	qw422016 := qt422016.AcquireWriter(qq422016)
//line plain.qtpl:14
	StreamPlainView(qw422016, p)
//line plain.qtpl:14
	qt422016.ReleaseWriter(qw422016)
//line plain.qtpl:14
}

//line plain.qtpl:14
func PlainView(p *Params) string {
//line plain.qtpl:14
	qb422016 := qt422016.AcquireByteBuffer()
//line plain.qtpl:14
	WritePlainView(qb422016, p)
//line plain.qtpl:14
	qs422016 := string(qb422016.B)
//line plain.qtpl:14
	qt422016.ReleaseByteBuffer(qb422016)
//line plain.qtpl:14
	return qs422016
//line plain.qtpl:14
}
