FROM golang:1.24 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN make build

FROM scratch

WORKDIR /app

COPY --from=builder /app/tmp/server /server

CMD ["/server"]
