FROM golang:1.26 AS builder

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /krispmock ./cmd/krispmock

FROM alpine:latest
RUN apk add --no-cache ca-certificates
COPY --from=builder /krispmock /krispmock
ENTRYPOINT ["/krispmock"]
