/** @type {import('repomix').RepomixConfigFile} */
export default {
  output: {
    filePath: 'repomix-output.xml',
    style: 'xml',
    removeComments: false,
    removeEmptyLines: false,
  },
  include: [
    'cmd/**/*.go',
    'internal/**/*.go',
    'docs/**/*.md',
    'db/schema.sql',
    'queries.*.sql',
    'internal/graph/schema.graphqls',
    'go.mod',
    'Makefile',
    'sqlc.yaml',
    'gqlgen.yml',
    'CLAUDE.md',
    'README.md',
  ],
  ignore: {
    useGitignore: true,
    useDefaultPatterns: true,
    customPatterns: [
      'internal/graph/generated.go',
      'internal/graph/model/models_gen.go',
      'db/migrations/**',
      '**/*.sqlite3',
      '**/*.sqlite3-*',
      '**/*.db',
      'node_modules/**',
      '.git/**',
      'tmp/**',
      'testdata/**',
      'test-results/**',
      'playwright-report/**',
      'demo/**',
      'demo2/**',
      '.bmad/**',
      '.claude/**',
      '.aider*',
      'infra/**',
      'k6/**',
      'e2e/**',
      'scripts/**',
      'assets/**',
      'obsidian-sync/**',
      '*.json',
      'session.json',
      'server',
    ],
  },
};
