// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package signinbyemail

import (
	"context"
	"sync"
	"trip2g/internal/db"
)

// Ensure, that EnvMock does implement Env.
// If this is not the case, regenerate this file with moq.
var _ Env = &EnvMock{}

// EnvMock is a mock implementation of Env.
//
//	func TestSomethingThatUsesEnv(t *testing.T) {
//
//		// make and configure a mocked Env
//		mockedEnv := &EnvMock{
//			DeleteSignInCodesByUserIDFunc: func(ctx context.Context, userID int64) error {
//				panic("mock out the DeleteSignInCodesByUserID method")
//			},
//			DevSignInBypassFunc: func(code string) bool {
//				panic("mock out the DevSignInBypass method")
//			},
//			SetupUserTokenFunc: func(ctx context.Context, userID int64) (string, error) {
//				panic("mock out the SetupUserToken method")
//			},
//			UserByEmailFunc: func(ctx context.Context, email string) (db.User, error) {
//				panic("mock out the UserByEmail method")
//			},
//			VerifySignInCodeFunc: func(ctx context.Context, arg db.VerifySignInCodeParams) (int64, error) {
//				panic("mock out the VerifySignInCode method")
//			},
//		}
//
//		// use mockedEnv in code that requires Env
//		// and then make assertions.
//
//	}
type EnvMock struct {
	// DeleteSignInCodesByUserIDFunc mocks the DeleteSignInCodesByUserID method.
	DeleteSignInCodesByUserIDFunc func(ctx context.Context, userID int64) error

	// DevSignInBypassFunc mocks the DevSignInBypass method.
	DevSignInBypassFunc func(code string) bool

	// SetupUserTokenFunc mocks the SetupUserToken method.
	SetupUserTokenFunc func(ctx context.Context, userID int64) (string, error)

	// UserByEmailFunc mocks the UserByEmail method.
	UserByEmailFunc func(ctx context.Context, email string) (db.User, error)

	// VerifySignInCodeFunc mocks the VerifySignInCode method.
	VerifySignInCodeFunc func(ctx context.Context, arg db.VerifySignInCodeParams) (int64, error)

	// calls tracks calls to the methods.
	calls struct {
		// DeleteSignInCodesByUserID holds details about calls to the DeleteSignInCodesByUserID method.
		DeleteSignInCodesByUserID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int64
		}
		// DevSignInBypass holds details about calls to the DevSignInBypass method.
		DevSignInBypass []struct {
			// Code is the code argument value.
			Code string
		}
		// SetupUserToken holds details about calls to the SetupUserToken method.
		SetupUserToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// UserID is the userID argument value.
			UserID int64
		}
		// UserByEmail holds details about calls to the UserByEmail method.
		UserByEmail []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Email is the email argument value.
			Email string
		}
		// VerifySignInCode holds details about calls to the VerifySignInCode method.
		VerifySignInCode []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.VerifySignInCodeParams
		}
	}
	lockDeleteSignInCodesByUserID sync.RWMutex
	lockDevSignInBypass           sync.RWMutex
	lockSetupUserToken            sync.RWMutex
	lockUserByEmail               sync.RWMutex
	lockVerifySignInCode          sync.RWMutex
}

// DeleteSignInCodesByUserID calls DeleteSignInCodesByUserIDFunc.
func (mock *EnvMock) DeleteSignInCodesByUserID(ctx context.Context, userID int64) error {
	if mock.DeleteSignInCodesByUserIDFunc == nil {
		panic("EnvMock.DeleteSignInCodesByUserIDFunc: method is nil but Env.DeleteSignInCodesByUserID was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID int64
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockDeleteSignInCodesByUserID.Lock()
	mock.calls.DeleteSignInCodesByUserID = append(mock.calls.DeleteSignInCodesByUserID, callInfo)
	mock.lockDeleteSignInCodesByUserID.Unlock()
	return mock.DeleteSignInCodesByUserIDFunc(ctx, userID)
}

// DeleteSignInCodesByUserIDCalls gets all the calls that were made to DeleteSignInCodesByUserID.
// Check the length with:
//
//	len(mockedEnv.DeleteSignInCodesByUserIDCalls())
func (mock *EnvMock) DeleteSignInCodesByUserIDCalls() []struct {
	Ctx    context.Context
	UserID int64
} {
	var calls []struct {
		Ctx    context.Context
		UserID int64
	}
	mock.lockDeleteSignInCodesByUserID.RLock()
	calls = mock.calls.DeleteSignInCodesByUserID
	mock.lockDeleteSignInCodesByUserID.RUnlock()
	return calls
}

// DevSignInBypass calls DevSignInBypassFunc.
func (mock *EnvMock) DevSignInBypass(code string) bool {
	if mock.DevSignInBypassFunc == nil {
		panic("EnvMock.DevSignInBypassFunc: method is nil but Env.DevSignInBypass was just called")
	}
	callInfo := struct {
		Code string
	}{
		Code: code,
	}
	mock.lockDevSignInBypass.Lock()
	mock.calls.DevSignInBypass = append(mock.calls.DevSignInBypass, callInfo)
	mock.lockDevSignInBypass.Unlock()
	return mock.DevSignInBypassFunc(code)
}

// DevSignInBypassCalls gets all the calls that were made to DevSignInBypass.
// Check the length with:
//
//	len(mockedEnv.DevSignInBypassCalls())
func (mock *EnvMock) DevSignInBypassCalls() []struct {
	Code string
} {
	var calls []struct {
		Code string
	}
	mock.lockDevSignInBypass.RLock()
	calls = mock.calls.DevSignInBypass
	mock.lockDevSignInBypass.RUnlock()
	return calls
}

// SetupUserToken calls SetupUserTokenFunc.
func (mock *EnvMock) SetupUserToken(ctx context.Context, userID int64) (string, error) {
	if mock.SetupUserTokenFunc == nil {
		panic("EnvMock.SetupUserTokenFunc: method is nil but Env.SetupUserToken was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		UserID int64
	}{
		Ctx:    ctx,
		UserID: userID,
	}
	mock.lockSetupUserToken.Lock()
	mock.calls.SetupUserToken = append(mock.calls.SetupUserToken, callInfo)
	mock.lockSetupUserToken.Unlock()
	return mock.SetupUserTokenFunc(ctx, userID)
}

// SetupUserTokenCalls gets all the calls that were made to SetupUserToken.
// Check the length with:
//
//	len(mockedEnv.SetupUserTokenCalls())
func (mock *EnvMock) SetupUserTokenCalls() []struct {
	Ctx    context.Context
	UserID int64
} {
	var calls []struct {
		Ctx    context.Context
		UserID int64
	}
	mock.lockSetupUserToken.RLock()
	calls = mock.calls.SetupUserToken
	mock.lockSetupUserToken.RUnlock()
	return calls
}

// UserByEmail calls UserByEmailFunc.
func (mock *EnvMock) UserByEmail(ctx context.Context, email string) (db.User, error) {
	if mock.UserByEmailFunc == nil {
		panic("EnvMock.UserByEmailFunc: method is nil but Env.UserByEmail was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Email string
	}{
		Ctx:   ctx,
		Email: email,
	}
	mock.lockUserByEmail.Lock()
	mock.calls.UserByEmail = append(mock.calls.UserByEmail, callInfo)
	mock.lockUserByEmail.Unlock()
	return mock.UserByEmailFunc(ctx, email)
}

// UserByEmailCalls gets all the calls that were made to UserByEmail.
// Check the length with:
//
//	len(mockedEnv.UserByEmailCalls())
func (mock *EnvMock) UserByEmailCalls() []struct {
	Ctx   context.Context
	Email string
} {
	var calls []struct {
		Ctx   context.Context
		Email string
	}
	mock.lockUserByEmail.RLock()
	calls = mock.calls.UserByEmail
	mock.lockUserByEmail.RUnlock()
	return calls
}

// VerifySignInCode calls VerifySignInCodeFunc.
func (mock *EnvMock) VerifySignInCode(ctx context.Context, arg db.VerifySignInCodeParams) (int64, error) {
	if mock.VerifySignInCodeFunc == nil {
		panic("EnvMock.VerifySignInCodeFunc: method is nil but Env.VerifySignInCode was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.VerifySignInCodeParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockVerifySignInCode.Lock()
	mock.calls.VerifySignInCode = append(mock.calls.VerifySignInCode, callInfo)
	mock.lockVerifySignInCode.Unlock()
	return mock.VerifySignInCodeFunc(ctx, arg)
}

// VerifySignInCodeCalls gets all the calls that were made to VerifySignInCode.
// Check the length with:
//
//	len(mockedEnv.VerifySignInCodeCalls())
func (mock *EnvMock) VerifySignInCodeCalls() []struct {
	Ctx context.Context
	Arg db.VerifySignInCodeParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.VerifySignInCodeParams
	}
	mock.lockVerifySignInCode.RLock()
	calls = mock.calls.VerifySignInCode
	mock.lockVerifySignInCode.RUnlock()
	return calls
}
