[toc_title]
other = "Table of Contents"

[backlinks_title]
other = "Backlinks"

[readmore]
other = "Read more →"

[onboarding_title]
other = "Site is being set up"

[onboarding_subtitle]
other = "Log in as administrator to get started."

[paywall_home]
other = "← Home"

[signinwall_home]
other = "Home"

[signinwall_message]
other = "Sign in to view this content"

[tg_read_on]
other = "Read on"

[tg_read]
other = "Read in Telegram"
