// Code generated by qtc from "endpoints.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views/endpoints.qtpl:1
package views

//line views/endpoints.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views/endpoints.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views/endpoints.qtpl:2
type CaseItem struct {
	PackageName  string
	PackageAlias string
	ImportPath   string
}

//line views/endpoints.qtpl:9
func StreamCode(qw422016 *qt422016.Writer, cases []CaseItem) {
//line views/endpoints.qtpl:9
	qw422016.N().S(`// Code generated by gencmd from ./gencmd/views/endpoints.qtpl; DO NOT EDIT.
//
// This file was auto-generated. Any manual changes will be lost.
// To regenerate, run: go run ./internal/router/gencmd
package router

import (
`)
//line views/endpoints.qtpl:17
	for _, cs := range cases {
//line views/endpoints.qtpl:17
		qw422016.N().S(`	`)
//line views/endpoints.qtpl:18
		qw422016.E().S(cs.PackageAlias)
//line views/endpoints.qtpl:18
		qw422016.N().S(` "`)
//line views/endpoints.qtpl:18
		qw422016.E().S(cs.ImportPath)
//line views/endpoints.qtpl:18
		qw422016.N().S(`"
`)
//line views/endpoints.qtpl:19
	}
//line views/endpoints.qtpl:19
	qw422016.N().S(`)

var endpoints = []Endpoint{
`)
//line views/endpoints.qtpl:23
	for _, cs := range cases {
//line views/endpoints.qtpl:23
		qw422016.N().S(`	&`)
//line views/endpoints.qtpl:24
		qw422016.E().S(cs.PackageAlias)
//line views/endpoints.qtpl:24
		qw422016.N().S(`.Endpoint{},
`)
//line views/endpoints.qtpl:25
	}
//line views/endpoints.qtpl:25
	qw422016.N().S(`}

type RoutesEnv interface {
`)
//line views/endpoints.qtpl:29
	for _, cs := range cases {
//line views/endpoints.qtpl:29
		qw422016.N().S(`	`)
//line views/endpoints.qtpl:30
		qw422016.E().S(cs.PackageAlias)
//line views/endpoints.qtpl:30
		qw422016.N().S(`.Env
`)
//line views/endpoints.qtpl:31
	}
//line views/endpoints.qtpl:31
	qw422016.N().S(`}

`)
//line views/endpoints.qtpl:34
}

//line views/endpoints.qtpl:34
func WriteCode(qq422016 qtio422016.Writer, cases []CaseItem) {
//line views/endpoints.qtpl:34
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views/endpoints.qtpl:34
	StreamCode(qw422016, cases)
//line views/endpoints.qtpl:34
	qt422016.ReleaseWriter(qw422016)
//line views/endpoints.qtpl:34
}

//line views/endpoints.qtpl:34
func Code(cases []CaseItem) string {
//line views/endpoints.qtpl:34
	qb422016 := qt422016.AcquireByteBuffer()
//line views/endpoints.qtpl:34
	WriteCode(qb422016, cases)
//line views/endpoints.qtpl:34
	qs422016 := string(qb422016.B)
//line views/endpoints.qtpl:34
	qt422016.ReleaseByteBuffer(qb422016)
//line views/endpoints.qtpl:34
	return qs422016
//line views/endpoints.qtpl:34
}
