// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type trip2g_admin_tgbot_show_chats_subgraphs_saveMutationVariables = Exact<{
  input: SetTgChatSubgraphsInput;
}>;


export type trip2g_admin_tgbot_show_chats_subgraphs_saveMutation = { __typename?: 'Mutation', admin: { __typename?: 'AdminMutation', payload: { __typename: 'ErrorPayload', message: string } | { __typename: 'SetTgChatSubgraphsPayload', success: boolean } } };


export function $trip2g_admin_tgbot_show_chats_subgraphs_save(variables: trip2g_admin_tgbot_show_chats_subgraphs_saveMutationVariables, opts?: { revalidate?: boolean }): trip2g_admin_tgbot_show_chats_subgraphs_saveMutation {
	return $trip2g_gql_request(`mutation trip2g_admin_tgbot_show_chats_subgraphs_save(\u0024input: SetTgChatSubgraphsInput!) {
  admin {
    payload: setTgChatSubgraphs(input: \u0024input) {
      __typename
      ... on SetTgChatSubgraphsPayload {
        success
      }
      ... on ErrorPayload {
        message
      }
    }
  }
}`, variables, opts) as trip2g_admin_tgbot_show_chats_subgraphs_saveMutation
}

}
