// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package updatetelegrampublishpost_test

import (
	"context"
	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api/v5"
	"sync"
	"trip2g/internal/case/updatetelegrampublishpost"
	"trip2g/internal/db"
	"trip2g/internal/model"
)

// Ensure, that EnvMock does implement updatetelegrampublishpost.Env.
// If this is not the case, regenerate this file with moq.
var _ updatetelegrampublishpost.Env = &EnvMock{}

// EnvMock is a mock implementation of updatetelegrampublishpost.Env.
//
//	func TestSomethingThatUsesEnv(t *testing.T) {
//
//		// make and configure a mocked updatetelegrampublishpost.Env
//		mockedEnv := &EnvMock{
//			ConvertNoteViewToTelegramPostFunc: func(ctx context.Context, source model.TelegramPostSource) (*model.TelegramPost, error) {
//				panic("mock out the ConvertNoteViewToTelegramPost method")
//			},
//			LatestNoteViewsFunc: func() *model.NoteViews {
//				panic("mock out the LatestNoteViews method")
//			},
//			ListTelegramPublishSentMessagesByNotePathIDFunc: func(ctx context.Context, notePathID int64) ([]db.ListTelegramPublishSentMessagesByNotePathIDRow, error) {
//				panic("mock out the ListTelegramPublishSentMessagesByNotePathID method")
//			},
//			SendTelegramRequestFunc: func(ctx context.Context, chatID int64, msg tgbotapi.Chattable) error {
//				panic("mock out the SendTelegramRequest method")
//			},
//			UpdateTelegramPublishSentMessageContentFunc: func(ctx context.Context, arg db.UpdateTelegramPublishSentMessageContentParams) error {
//				panic("mock out the UpdateTelegramPublishSentMessageContent method")
//			},
//		}
//
//		// use mockedEnv in code that requires updatetelegrampublishpost.Env
//		// and then make assertions.
//
//	}
type EnvMock struct {
	// ConvertNoteViewToTelegramPostFunc mocks the ConvertNoteViewToTelegramPost method.
	ConvertNoteViewToTelegramPostFunc func(ctx context.Context, source model.TelegramPostSource) (*model.TelegramPost, error)

	// LatestNoteViewsFunc mocks the LatestNoteViews method.
	LatestNoteViewsFunc func() *model.NoteViews

	// ListTelegramPublishSentMessagesByNotePathIDFunc mocks the ListTelegramPublishSentMessagesByNotePathID method.
	ListTelegramPublishSentMessagesByNotePathIDFunc func(ctx context.Context, notePathID int64) ([]db.ListTelegramPublishSentMessagesByNotePathIDRow, error)

	// SendTelegramRequestFunc mocks the SendTelegramRequest method.
	SendTelegramRequestFunc func(ctx context.Context, chatID int64, msg tgbotapi.Chattable) error

	// UpdateTelegramPublishSentMessageContentFunc mocks the UpdateTelegramPublishSentMessageContent method.
	UpdateTelegramPublishSentMessageContentFunc func(ctx context.Context, arg db.UpdateTelegramPublishSentMessageContentParams) error

	// calls tracks calls to the methods.
	calls struct {
		// ConvertNoteViewToTelegramPost holds details about calls to the ConvertNoteViewToTelegramPost method.
		ConvertNoteViewToTelegramPost []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Source is the source argument value.
			Source model.TelegramPostSource
		}
		// LatestNoteViews holds details about calls to the LatestNoteViews method.
		LatestNoteViews []struct {
		}
		// ListTelegramPublishSentMessagesByNotePathID holds details about calls to the ListTelegramPublishSentMessagesByNotePathID method.
		ListTelegramPublishSentMessagesByNotePathID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// NotePathID is the notePathID argument value.
			NotePathID int64
		}
		// SendTelegramRequest holds details about calls to the SendTelegramRequest method.
		SendTelegramRequest []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChatID is the chatID argument value.
			ChatID int64
			// Msg is the msg argument value.
			Msg tgbotapi.Chattable
		}
		// UpdateTelegramPublishSentMessageContent holds details about calls to the UpdateTelegramPublishSentMessageContent method.
		UpdateTelegramPublishSentMessageContent []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.UpdateTelegramPublishSentMessageContentParams
		}
	}
	lockConvertNoteViewToTelegramPost               sync.RWMutex
	lockLatestNoteViews                             sync.RWMutex
	lockListTelegramPublishSentMessagesByNotePathID sync.RWMutex
	lockSendTelegramRequest                         sync.RWMutex
	lockUpdateTelegramPublishSentMessageContent     sync.RWMutex
}

// ConvertNoteViewToTelegramPost calls ConvertNoteViewToTelegramPostFunc.
func (mock *EnvMock) ConvertNoteViewToTelegramPost(ctx context.Context, source model.TelegramPostSource) (*model.TelegramPost, error) {
	if mock.ConvertNoteViewToTelegramPostFunc == nil {
		panic("EnvMock.ConvertNoteViewToTelegramPostFunc: method is nil but Env.ConvertNoteViewToTelegramPost was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Source model.TelegramPostSource
	}{
		Ctx:    ctx,
		Source: source,
	}
	mock.lockConvertNoteViewToTelegramPost.Lock()
	mock.calls.ConvertNoteViewToTelegramPost = append(mock.calls.ConvertNoteViewToTelegramPost, callInfo)
	mock.lockConvertNoteViewToTelegramPost.Unlock()
	return mock.ConvertNoteViewToTelegramPostFunc(ctx, source)
}

// ConvertNoteViewToTelegramPostCalls gets all the calls that were made to ConvertNoteViewToTelegramPost.
// Check the length with:
//
//	len(mockedEnv.ConvertNoteViewToTelegramPostCalls())
func (mock *EnvMock) ConvertNoteViewToTelegramPostCalls() []struct {
	Ctx    context.Context
	Source model.TelegramPostSource
} {
	var calls []struct {
		Ctx    context.Context
		Source model.TelegramPostSource
	}
	mock.lockConvertNoteViewToTelegramPost.RLock()
	calls = mock.calls.ConvertNoteViewToTelegramPost
	mock.lockConvertNoteViewToTelegramPost.RUnlock()
	return calls
}

// LatestNoteViews calls LatestNoteViewsFunc.
func (mock *EnvMock) LatestNoteViews() *model.NoteViews {
	if mock.LatestNoteViewsFunc == nil {
		panic("EnvMock.LatestNoteViewsFunc: method is nil but Env.LatestNoteViews was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLatestNoteViews.Lock()
	mock.calls.LatestNoteViews = append(mock.calls.LatestNoteViews, callInfo)
	mock.lockLatestNoteViews.Unlock()
	return mock.LatestNoteViewsFunc()
}

// LatestNoteViewsCalls gets all the calls that were made to LatestNoteViews.
// Check the length with:
//
//	len(mockedEnv.LatestNoteViewsCalls())
func (mock *EnvMock) LatestNoteViewsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLatestNoteViews.RLock()
	calls = mock.calls.LatestNoteViews
	mock.lockLatestNoteViews.RUnlock()
	return calls
}

// ListTelegramPublishSentMessagesByNotePathID calls ListTelegramPublishSentMessagesByNotePathIDFunc.
func (mock *EnvMock) ListTelegramPublishSentMessagesByNotePathID(ctx context.Context, notePathID int64) ([]db.ListTelegramPublishSentMessagesByNotePathIDRow, error) {
	if mock.ListTelegramPublishSentMessagesByNotePathIDFunc == nil {
		panic("EnvMock.ListTelegramPublishSentMessagesByNotePathIDFunc: method is nil but Env.ListTelegramPublishSentMessagesByNotePathID was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		NotePathID int64
	}{
		Ctx:        ctx,
		NotePathID: notePathID,
	}
	mock.lockListTelegramPublishSentMessagesByNotePathID.Lock()
	mock.calls.ListTelegramPublishSentMessagesByNotePathID = append(mock.calls.ListTelegramPublishSentMessagesByNotePathID, callInfo)
	mock.lockListTelegramPublishSentMessagesByNotePathID.Unlock()
	return mock.ListTelegramPublishSentMessagesByNotePathIDFunc(ctx, notePathID)
}

// ListTelegramPublishSentMessagesByNotePathIDCalls gets all the calls that were made to ListTelegramPublishSentMessagesByNotePathID.
// Check the length with:
//
//	len(mockedEnv.ListTelegramPublishSentMessagesByNotePathIDCalls())
func (mock *EnvMock) ListTelegramPublishSentMessagesByNotePathIDCalls() []struct {
	Ctx        context.Context
	NotePathID int64
} {
	var calls []struct {
		Ctx        context.Context
		NotePathID int64
	}
	mock.lockListTelegramPublishSentMessagesByNotePathID.RLock()
	calls = mock.calls.ListTelegramPublishSentMessagesByNotePathID
	mock.lockListTelegramPublishSentMessagesByNotePathID.RUnlock()
	return calls
}

// SendTelegramRequest calls SendTelegramRequestFunc.
func (mock *EnvMock) SendTelegramRequest(ctx context.Context, chatID int64, msg tgbotapi.Chattable) error {
	if mock.SendTelegramRequestFunc == nil {
		panic("EnvMock.SendTelegramRequestFunc: method is nil but Env.SendTelegramRequest was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ChatID int64
		Msg    tgbotapi.Chattable
	}{
		Ctx:    ctx,
		ChatID: chatID,
		Msg:    msg,
	}
	mock.lockSendTelegramRequest.Lock()
	mock.calls.SendTelegramRequest = append(mock.calls.SendTelegramRequest, callInfo)
	mock.lockSendTelegramRequest.Unlock()
	return mock.SendTelegramRequestFunc(ctx, chatID, msg)
}

// SendTelegramRequestCalls gets all the calls that were made to SendTelegramRequest.
// Check the length with:
//
//	len(mockedEnv.SendTelegramRequestCalls())
func (mock *EnvMock) SendTelegramRequestCalls() []struct {
	Ctx    context.Context
	ChatID int64
	Msg    tgbotapi.Chattable
} {
	var calls []struct {
		Ctx    context.Context
		ChatID int64
		Msg    tgbotapi.Chattable
	}
	mock.lockSendTelegramRequest.RLock()
	calls = mock.calls.SendTelegramRequest
	mock.lockSendTelegramRequest.RUnlock()
	return calls
}

// UpdateTelegramPublishSentMessageContent calls UpdateTelegramPublishSentMessageContentFunc.
func (mock *EnvMock) UpdateTelegramPublishSentMessageContent(ctx context.Context, arg db.UpdateTelegramPublishSentMessageContentParams) error {
	if mock.UpdateTelegramPublishSentMessageContentFunc == nil {
		panic("EnvMock.UpdateTelegramPublishSentMessageContentFunc: method is nil but Env.UpdateTelegramPublishSentMessageContent was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.UpdateTelegramPublishSentMessageContentParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpdateTelegramPublishSentMessageContent.Lock()
	mock.calls.UpdateTelegramPublishSentMessageContent = append(mock.calls.UpdateTelegramPublishSentMessageContent, callInfo)
	mock.lockUpdateTelegramPublishSentMessageContent.Unlock()
	return mock.UpdateTelegramPublishSentMessageContentFunc(ctx, arg)
}

// UpdateTelegramPublishSentMessageContentCalls gets all the calls that were made to UpdateTelegramPublishSentMessageContent.
// Check the length with:
//
//	len(mockedEnv.UpdateTelegramPublishSentMessageContentCalls())
func (mock *EnvMock) UpdateTelegramPublishSentMessageContentCalls() []struct {
	Ctx context.Context
	Arg db.UpdateTelegramPublishSentMessageContentParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.UpdateTelegramPublishSentMessageContentParams
	}
	mock.lockUpdateTelegramPublishSentMessageContent.RLock()
	calls = mock.calls.UpdateTelegramPublishSentMessageContent
	mock.lockUpdateTelegramPublishSentMessageContent.RUnlock()
	return calls
}
