// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type trip2g_admin_release_create_createMutationVariables = Exact<{
  input: CreateReleaseInput;
}>;


export type trip2g_admin_release_create_createMutation = { __typename?: 'Mutation', admin: { __typename?: 'AdminMutation', payload: { __typename: 'CreateReleasePayload', release: { __typename?: 'AdminRelease', id: any } } | { __typename: 'ErrorPayload', message: string } } };


export function $trip2g_admin_release_create_create(variables: trip2g_admin_release_create_createMutationVariables, opts?: { revalidate?: boolean }): trip2g_admin_release_create_createMutation {
	return $trip2g_gql_request(`mutation trip2g_admin_release_create_create(\u0024input: CreateReleaseInput!) {
  admin {
    payload: createRelease(input: \u0024input) {
      __typename
      ... on CreateReleasePayload {
        release {
          id
        }
      }
      ... on ErrorPayload {
        message
      }
    }
  }
}`, variables, opts) as trip2g_admin_release_create_createMutation
}

}
