// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package pushnotes_test

import (
	"context"
	"sync"
	"trip2g/internal/case/pushnotes"
	"trip2g/internal/logger"
	appmodel "trip2g/internal/model"
)

// Ensure, that EnvMock does implement pushnotes.Env.
// If this is not the case, regenerate this file with moq.
var _ pushnotes.Env = &EnvMock{}

// EnvMock is a mock implementation of pushnotes.Env.
//
//	func TestSomethingThatUsesEnv(t *testing.T) {
//
//		// make and configure a mocked pushnotes.Env
//		mockedEnv := &EnvMock{
//			HandleLatestNotesAfterSaveFunc: func(ctx context.Context, changedPathIDs []int64) error {
//				panic("mock out the HandleLatestNotesAfterSave method")
//			},
//			InsertNoteFunc: func(ctx context.Context, update appmodel.RawNote) error {
//				panic("mock out the InsertNote method")
//			},
//			InsertSubgraphFunc: func(ctx context.Context, name string) error {
//				panic("mock out the InsertSubgraph method")
//			},
//			LayoutsFunc: func() *appmodel.Layouts {
//				panic("mock out the Layouts method")
//			},
//			LoggerFunc: func() logger.Logger {
//				panic("mock out the Logger method")
//			},
//			PrepareLatestNotesFunc: func(ctx context.Context) (*appmodel.NoteViews, error) {
//				panic("mock out the PrepareLatestNotes method")
//			},
//		}
//
//		// use mockedEnv in code that requires pushnotes.Env
//		// and then make assertions.
//
//	}
type EnvMock struct {
	// HandleLatestNotesAfterSaveFunc mocks the HandleLatestNotesAfterSave method.
	HandleLatestNotesAfterSaveFunc func(ctx context.Context, changedPathIDs []int64) error

	// InsertNoteFunc mocks the InsertNote method.
	InsertNoteFunc func(ctx context.Context, update appmodel.RawNote) error

	// InsertSubgraphFunc mocks the InsertSubgraph method.
	InsertSubgraphFunc func(ctx context.Context, name string) error

	// LayoutsFunc mocks the Layouts method.
	LayoutsFunc func() *appmodel.Layouts

	// LoggerFunc mocks the Logger method.
	LoggerFunc func() logger.Logger

	// PrepareLatestNotesFunc mocks the PrepareLatestNotes method.
	PrepareLatestNotesFunc func(ctx context.Context) (*appmodel.NoteViews, error)

	// calls tracks calls to the methods.
	calls struct {
		// HandleLatestNotesAfterSave holds details about calls to the HandleLatestNotesAfterSave method.
		HandleLatestNotesAfterSave []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChangedPathIDs is the changedPathIDs argument value.
			ChangedPathIDs []int64
		}
		// InsertNote holds details about calls to the InsertNote method.
		InsertNote []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Update is the update argument value.
			Update appmodel.RawNote
		}
		// InsertSubgraph holds details about calls to the InsertSubgraph method.
		InsertSubgraph []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// Layouts holds details about calls to the Layouts method.
		Layouts []struct {
		}
		// Logger holds details about calls to the Logger method.
		Logger []struct {
		}
		// PrepareLatestNotes holds details about calls to the PrepareLatestNotes method.
		PrepareLatestNotes []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockHandleLatestNotesAfterSave sync.RWMutex
	lockInsertNote                 sync.RWMutex
	lockInsertSubgraph             sync.RWMutex
	lockLayouts                    sync.RWMutex
	lockLogger                     sync.RWMutex
	lockPrepareLatestNotes         sync.RWMutex
}

// HandleLatestNotesAfterSave calls HandleLatestNotesAfterSaveFunc.
func (mock *EnvMock) HandleLatestNotesAfterSave(ctx context.Context, changedPathIDs []int64) error {
	if mock.HandleLatestNotesAfterSaveFunc == nil {
		panic("EnvMock.HandleLatestNotesAfterSaveFunc: method is nil but Env.HandleLatestNotesAfterSave was just called")
	}
	callInfo := struct {
		Ctx            context.Context
		ChangedPathIDs []int64
	}{
		Ctx:            ctx,
		ChangedPathIDs: changedPathIDs,
	}
	mock.lockHandleLatestNotesAfterSave.Lock()
	mock.calls.HandleLatestNotesAfterSave = append(mock.calls.HandleLatestNotesAfterSave, callInfo)
	mock.lockHandleLatestNotesAfterSave.Unlock()
	return mock.HandleLatestNotesAfterSaveFunc(ctx, changedPathIDs)
}

// HandleLatestNotesAfterSaveCalls gets all the calls that were made to HandleLatestNotesAfterSave.
// Check the length with:
//
//	len(mockedEnv.HandleLatestNotesAfterSaveCalls())
func (mock *EnvMock) HandleLatestNotesAfterSaveCalls() []struct {
	Ctx            context.Context
	ChangedPathIDs []int64
} {
	var calls []struct {
		Ctx            context.Context
		ChangedPathIDs []int64
	}
	mock.lockHandleLatestNotesAfterSave.RLock()
	calls = mock.calls.HandleLatestNotesAfterSave
	mock.lockHandleLatestNotesAfterSave.RUnlock()
	return calls
}

// InsertNote calls InsertNoteFunc.
func (mock *EnvMock) InsertNote(ctx context.Context, update appmodel.RawNote) error {
	if mock.InsertNoteFunc == nil {
		panic("EnvMock.InsertNoteFunc: method is nil but Env.InsertNote was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Update appmodel.RawNote
	}{
		Ctx:    ctx,
		Update: update,
	}
	mock.lockInsertNote.Lock()
	mock.calls.InsertNote = append(mock.calls.InsertNote, callInfo)
	mock.lockInsertNote.Unlock()
	return mock.InsertNoteFunc(ctx, update)
}

// InsertNoteCalls gets all the calls that were made to InsertNote.
// Check the length with:
//
//	len(mockedEnv.InsertNoteCalls())
func (mock *EnvMock) InsertNoteCalls() []struct {
	Ctx    context.Context
	Update appmodel.RawNote
} {
	var calls []struct {
		Ctx    context.Context
		Update appmodel.RawNote
	}
	mock.lockInsertNote.RLock()
	calls = mock.calls.InsertNote
	mock.lockInsertNote.RUnlock()
	return calls
}

// InsertSubgraph calls InsertSubgraphFunc.
func (mock *EnvMock) InsertSubgraph(ctx context.Context, name string) error {
	if mock.InsertSubgraphFunc == nil {
		panic("EnvMock.InsertSubgraphFunc: method is nil but Env.InsertSubgraph was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockInsertSubgraph.Lock()
	mock.calls.InsertSubgraph = append(mock.calls.InsertSubgraph, callInfo)
	mock.lockInsertSubgraph.Unlock()
	return mock.InsertSubgraphFunc(ctx, name)
}

// InsertSubgraphCalls gets all the calls that were made to InsertSubgraph.
// Check the length with:
//
//	len(mockedEnv.InsertSubgraphCalls())
func (mock *EnvMock) InsertSubgraphCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockInsertSubgraph.RLock()
	calls = mock.calls.InsertSubgraph
	mock.lockInsertSubgraph.RUnlock()
	return calls
}

// Layouts calls LayoutsFunc.
func (mock *EnvMock) Layouts() *appmodel.Layouts {
	if mock.LayoutsFunc == nil {
		panic("EnvMock.LayoutsFunc: method is nil but Env.Layouts was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLayouts.Lock()
	mock.calls.Layouts = append(mock.calls.Layouts, callInfo)
	mock.lockLayouts.Unlock()
	return mock.LayoutsFunc()
}

// LayoutsCalls gets all the calls that were made to Layouts.
// Check the length with:
//
//	len(mockedEnv.LayoutsCalls())
func (mock *EnvMock) LayoutsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLayouts.RLock()
	calls = mock.calls.Layouts
	mock.lockLayouts.RUnlock()
	return calls
}

// Logger calls LoggerFunc.
func (mock *EnvMock) Logger() logger.Logger {
	if mock.LoggerFunc == nil {
		panic("EnvMock.LoggerFunc: method is nil but Env.Logger was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLogger.Lock()
	mock.calls.Logger = append(mock.calls.Logger, callInfo)
	mock.lockLogger.Unlock()
	return mock.LoggerFunc()
}

// LoggerCalls gets all the calls that were made to Logger.
// Check the length with:
//
//	len(mockedEnv.LoggerCalls())
func (mock *EnvMock) LoggerCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLogger.RLock()
	calls = mock.calls.Logger
	mock.lockLogger.RUnlock()
	return calls
}

// PrepareLatestNotes calls PrepareLatestNotesFunc.
func (mock *EnvMock) PrepareLatestNotes(ctx context.Context) (*appmodel.NoteViews, error) {
	if mock.PrepareLatestNotesFunc == nil {
		panic("EnvMock.PrepareLatestNotesFunc: method is nil but Env.PrepareLatestNotes was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockPrepareLatestNotes.Lock()
	mock.calls.PrepareLatestNotes = append(mock.calls.PrepareLatestNotes, callInfo)
	mock.lockPrepareLatestNotes.Unlock()
	return mock.PrepareLatestNotesFunc(ctx)
}

// PrepareLatestNotesCalls gets all the calls that were made to PrepareLatestNotes.
// Check the length with:
//
//	len(mockedEnv.PrepareLatestNotesCalls())
func (mock *EnvMock) PrepareLatestNotesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockPrepareLatestNotes.RLock()
	calls = mock.calls.PrepareLatestNotes
	mock.lockPrepareLatestNotes.RUnlock()
	return calls
}
