package fleetgql

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.81

import (
	"context"
	"trip2g/internal/fleet/fleetgql/fleetgen"
	"trip2g/internal/fleet/fleetgql/model"
	"trip2g/internal/fleet/graph"
)

// Roles is the resolver for the roles field.
func (r *queryResolver) Roles(ctx context.Context) ([]model.Role, error) {
	parsed, _ := r.roles.DiscoverParsed(ctx)
	out := make([]model.Role, 0, len(parsed))
	for _, role := range parsed {
		out = append(out, toModelRole(role))
	}
	return out, nil
}

// RoleGraph is the resolver for the roleGraph field.
func (r *queryResolver) RoleGraph(ctx context.Context) (*model.RoleGraph, error) {
	parsed, errs := r.roles.DiscoverParsed(ctx)
	return toModelRoleGraph(graph.DeriveRoleGraph(parsed), errStrings(errs)), nil
}

// RoleParseErrors is the resolver for the roleParseErrors field.
func (r *queryResolver) RoleParseErrors(ctx context.Context) ([]string, error) {
	_, errs := r.roles.DiscoverParsed(ctx)
	return toErrStrings(errStrings(errs)), nil // toErrStrings: non-null list must never be nil
}

// Query returns fleetgen.QueryResolver implementation.
func (r *Resolver) Query() fleetgen.QueryResolver { return &queryResolver{r} }

type queryResolver struct{ *Resolver }
