// Code generated by easyjson for marshaling/unmarshaling. DO NOT EDIT.

package model

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson7b3c8c57DecodeTrip2gInternalModel(in *jlexer.Lexer, out *FederationResult) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "content":
			if in.IsNull() {
				in.Skip()
				out.Content = nil
			} else {
				in.Delim('[')
				if out.Content == nil {
					if !in.IsDelim(']') {
						out.Content = make([]FederationContent, 0, 2)
					} else {
						out.Content = []FederationContent{}
					}
				} else {
					out.Content = (out.Content)[:0]
				}
				for !in.IsDelim(']') {
					var v1 FederationContent
					(v1).UnmarshalEasyJSON(in)
					out.Content = append(out.Content, v1)
					in.WantComma()
				}
				in.Delim(']')
			}
		case "structuredContent":
			if data := in.Raw(); in.Ok() {
				in.AddError((out.StructuredContent).UnmarshalJSON(data))
			}
		case "isError":
			out.IsError = bool(in.Bool())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7b3c8c57EncodeTrip2gInternalModel(out *jwriter.Writer, in FederationResult) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"content\":"
		out.RawString(prefix[1:])
		if in.Content == nil && (out.Flags&jwriter.NilSliceAsEmpty) == 0 {
			out.RawString("null")
		} else {
			out.RawByte('[')
			for v2, v3 := range in.Content {
				if v2 > 0 {
					out.RawByte(',')
				}
				(v3).MarshalEasyJSON(out)
			}
			out.RawByte(']')
		}
	}
	if len(in.StructuredContent) != 0 {
		const prefix string = ",\"structuredContent\":"
		out.RawString(prefix)
		out.Raw((in.StructuredContent).MarshalJSON())
	}
	if in.IsError {
		const prefix string = ",\"isError\":"
		out.RawString(prefix)
		out.Bool(bool(in.IsError))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FederationResult) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7b3c8c57EncodeTrip2gInternalModel(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FederationResult) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7b3c8c57EncodeTrip2gInternalModel(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FederationResult) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7b3c8c57DecodeTrip2gInternalModel(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FederationResult) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7b3c8c57DecodeTrip2gInternalModel(l, v)
}
func easyjson7b3c8c57DecodeTrip2gInternalModel1(in *jlexer.Lexer, out *FederationPeer) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "KBID":
			out.KBID = string(in.String())
		case "KBURL":
			out.KBURL = string(in.String())
		case "KID":
			out.KID = string(in.String())
		case "Secret":
			if in.IsNull() {
				in.Skip()
				out.Secret = nil
			} else {
				out.Secret = in.Bytes()
			}
		case "Issuer":
			out.Issuer = string(in.String())
		case "Depth":
			out.Depth = int(in.Int())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7b3c8c57EncodeTrip2gInternalModel1(out *jwriter.Writer, in FederationPeer) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"KBID\":"
		out.RawString(prefix[1:])
		out.String(string(in.KBID))
	}
	{
		const prefix string = ",\"KBURL\":"
		out.RawString(prefix)
		out.String(string(in.KBURL))
	}
	{
		const prefix string = ",\"KID\":"
		out.RawString(prefix)
		out.String(string(in.KID))
	}
	{
		const prefix string = ",\"Secret\":"
		out.RawString(prefix)
		out.Base64Bytes(in.Secret)
	}
	{
		const prefix string = ",\"Issuer\":"
		out.RawString(prefix)
		out.String(string(in.Issuer))
	}
	{
		const prefix string = ",\"Depth\":"
		out.RawString(prefix)
		out.Int(int(in.Depth))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FederationPeer) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7b3c8c57EncodeTrip2gInternalModel1(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FederationPeer) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7b3c8c57EncodeTrip2gInternalModel1(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FederationPeer) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7b3c8c57DecodeTrip2gInternalModel1(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FederationPeer) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7b3c8c57DecodeTrip2gInternalModel1(l, v)
}
func easyjson7b3c8c57DecodeTrip2gInternalModel2(in *jlexer.Lexer, out *FederationContent) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeFieldName(false)
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "type":
			out.Type = string(in.String())
		case "text":
			out.Text = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7b3c8c57EncodeTrip2gInternalModel2(out *jwriter.Writer, in FederationContent) {
	out.RawByte('{')
	first := true
	_ = first
	{
		const prefix string = ",\"type\":"
		out.RawString(prefix[1:])
		out.String(string(in.Type))
	}
	{
		const prefix string = ",\"text\":"
		out.RawString(prefix)
		out.String(string(in.Text))
	}
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v FederationContent) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7b3c8c57EncodeTrip2gInternalModel2(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v FederationContent) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7b3c8c57EncodeTrip2gInternalModel2(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *FederationContent) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7b3c8c57DecodeTrip2gInternalModel2(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *FederationContent) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7b3c8c57DecodeTrip2gInternalModel2(l, v)
}
