// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type trip2g_user_space_tokens_listQueryVariables = Exact<{ [key: string]: never; }>;


export type trip2g_user_space_tokens_listQuery = { __typename?: 'Query', viewer: { __typename?: 'Viewer', user?: { __typename?: 'User', tokens: Array<{ __typename?: 'UserToken', id: string, name: string, tokenPrefix: string, scope: string, createdAt: any, lastUsedAt?: any | null, expiresAt?: any | null, revokedAt?: any | null }> } | null } };


export function $trip2g_user_space_tokens_list(opts?: { revalidate?: boolean }): trip2g_user_space_tokens_listQuery {
	return $trip2g_gql_request(`query trip2g_user_space_tokens_list {
  viewer {
    user {
      tokens {
        id
        name
        tokenPrefix
        scope
        createdAt
        lastUsedAt
        expiresAt
        revokedAt
      }
    }
  }
}`, undefined, opts) as trip2g_user_space_tokens_listQuery
}

}
