// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type trip2g_admin_subgraph_select_dataQueryVariables = Exact<{ [key: string]: never; }>;


export type trip2g_admin_subgraph_select_dataQuery = { __typename?: 'Query', admin: { __typename?: 'AdminQuery', allSubgraphs: { __typename?: 'AdminSubgraphsConnection', nodes: Array<{ __typename?: 'AdminSubgraph', id: any, name: string }> } } };


export function $trip2g_admin_subgraph_select_data(opts?: { revalidate?: boolean }): trip2g_admin_subgraph_select_dataQuery {
	return $trip2g_gql_request(`query trip2g_admin_subgraph_select_data {
  admin {
    allSubgraphs {
      nodes {
        id
        name
      }
    }
  }
}`, undefined, opts) as trip2g_admin_subgraph_select_dataQuery
}

}
