// Code generated by qtc from "views.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line internal/case/renderadminpage/views.qtpl:1
package renderadminpage

//line internal/case/renderadminpage/views.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line internal/case/renderadminpage/views.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line internal/case/renderadminpage/views.qtpl:1
func StreamPage(qw422016 *qt422016.Writer, resp *Response) {
//line internal/case/renderadminpage/views.qtpl:1
	qw422016.N().S(`<!DOCTYPE html>

<html mol_view_root>

  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, height=device-height, initial-scale=1" />
  <meta name="mobile-web-app-capable" content="yes">
  <meta name="apple-mobile-web-app-capable" content="yes">

  <title>Admin</title>

  <body mol_view_root>
    <div mol_view_root="$trip2g_admin"></div>
    <script src="`)
//line internal/case/renderadminpage/views.qtpl:15
	qw422016.N().S(resp.JSURL)
//line internal/case/renderadminpage/views.qtpl:15
	qw422016.N().S(`"></script>
  </body
</html>
`)
//line internal/case/renderadminpage/views.qtpl:18
}

//line internal/case/renderadminpage/views.qtpl:18
func WritePage(qq422016 qtio422016.Writer, resp *Response) {
//line internal/case/renderadminpage/views.qtpl:18
	qw422016 := qt422016.AcquireWriter(qq422016)
//line internal/case/renderadminpage/views.qtpl:18
	StreamPage(qw422016, resp)
//line internal/case/renderadminpage/views.qtpl:18
	qt422016.ReleaseWriter(qw422016)
//line internal/case/renderadminpage/views.qtpl:18
}

//line internal/case/renderadminpage/views.qtpl:18
func Page(resp *Response) string {
//line internal/case/renderadminpage/views.qtpl:18
	qb422016 := qt422016.AcquireByteBuffer()
//line internal/case/renderadminpage/views.qtpl:18
	WritePage(qb422016, resp)
//line internal/case/renderadminpage/views.qtpl:18
	qs422016 := string(qb422016.B)
//line internal/case/renderadminpage/views.qtpl:18
	qt422016.ReleaseByteBuffer(qb422016)
//line internal/case/renderadminpage/views.qtpl:18
	return qs422016
//line internal/case/renderadminpage/views.qtpl:18
}
