// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package createredirect

import (
	"context"
	"sync"
	"trip2g/internal/db"
	"trip2g/internal/usertoken"
)

// Ensure, that EnvMock does implement Env.
// If this is not the case, regenerate this file with moq.
var _ Env = &EnvMock{}

// EnvMock is a mock implementation of Env.
//
//	func TestSomethingThatUsesEnv(t *testing.T) {
//
//		// make and configure a mocked Env
//		mockedEnv := &EnvMock{
//			CurrentAdminUserTokenFunc: func(ctx context.Context) (*usertoken.Data, error) {
//				panic("mock out the CurrentAdminUserToken method")
//			},
//			InsertRedirectFunc: func(ctx context.Context, params db.InsertRedirectParams) (db.Redirect, error) {
//				panic("mock out the InsertRedirect method")
//			},
//		}
//
//		// use mockedEnv in code that requires Env
//		// and then make assertions.
//
//	}
type EnvMock struct {
	// CurrentAdminUserTokenFunc mocks the CurrentAdminUserToken method.
	CurrentAdminUserTokenFunc func(ctx context.Context) (*usertoken.Data, error)

	// InsertRedirectFunc mocks the InsertRedirect method.
	InsertRedirectFunc func(ctx context.Context, params db.InsertRedirectParams) (db.Redirect, error)

	// calls tracks calls to the methods.
	calls struct {
		// CurrentAdminUserToken holds details about calls to the CurrentAdminUserToken method.
		CurrentAdminUserToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// InsertRedirect holds details about calls to the InsertRedirect method.
		InsertRedirect []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Params is the params argument value.
			Params db.InsertRedirectParams
		}
	}
	lockCurrentAdminUserToken sync.RWMutex
	lockInsertRedirect        sync.RWMutex
}

// CurrentAdminUserToken calls CurrentAdminUserTokenFunc.
func (mock *EnvMock) CurrentAdminUserToken(ctx context.Context) (*usertoken.Data, error) {
	if mock.CurrentAdminUserTokenFunc == nil {
		panic("EnvMock.CurrentAdminUserTokenFunc: method is nil but Env.CurrentAdminUserToken was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCurrentAdminUserToken.Lock()
	mock.calls.CurrentAdminUserToken = append(mock.calls.CurrentAdminUserToken, callInfo)
	mock.lockCurrentAdminUserToken.Unlock()
	return mock.CurrentAdminUserTokenFunc(ctx)
}

// CurrentAdminUserTokenCalls gets all the calls that were made to CurrentAdminUserToken.
// Check the length with:
//
//	len(mockedEnv.CurrentAdminUserTokenCalls())
func (mock *EnvMock) CurrentAdminUserTokenCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCurrentAdminUserToken.RLock()
	calls = mock.calls.CurrentAdminUserToken
	mock.lockCurrentAdminUserToken.RUnlock()
	return calls
}

// InsertRedirect calls InsertRedirectFunc.
func (mock *EnvMock) InsertRedirect(ctx context.Context, params db.InsertRedirectParams) (db.Redirect, error) {
	if mock.InsertRedirectFunc == nil {
		panic("EnvMock.InsertRedirectFunc: method is nil but Env.InsertRedirect was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		Params db.InsertRedirectParams
	}{
		Ctx:    ctx,
		Params: params,
	}
	mock.lockInsertRedirect.Lock()
	mock.calls.InsertRedirect = append(mock.calls.InsertRedirect, callInfo)
	mock.lockInsertRedirect.Unlock()
	return mock.InsertRedirectFunc(ctx, params)
}

// InsertRedirectCalls gets all the calls that were made to InsertRedirect.
// Check the length with:
//
//	len(mockedEnv.InsertRedirectCalls())
func (mock *EnvMock) InsertRedirectCalls() []struct {
	Ctx    context.Context
	Params db.InsertRedirectParams
} {
	var calls []struct {
		Ctx    context.Context
		Params db.InsertRedirectParams
	}
	mock.lockInsertRedirect.RLock()
	calls = mock.calls.InsertRedirect
	mock.lockInsertRedirect.RUnlock()
	return calls
}
