// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type trip2g_admin_boostycredentials_button_delete_deleteMutationVariables = Exact<{
  input: DeleteBoostyCredentialsInput;
}>;


export type trip2g_admin_boostycredentials_button_delete_deleteMutation = { __typename?: 'Mutation', admin: { __typename?: 'AdminMutation', payload: { __typename: 'DeleteBoostyCredentialsPayload', boostyCredentials: { __typename?: 'AdminBoostyCredentials', id: any } } | { __typename: 'ErrorPayload', message: string } } };


export function $trip2g_admin_boostycredentials_button_delete_delete(variables: trip2g_admin_boostycredentials_button_delete_deleteMutationVariables, opts?: { revalidate?: boolean }): trip2g_admin_boostycredentials_button_delete_deleteMutation {
	return $trip2g_gql_request(`mutation trip2g_admin_boostycredentials_button_delete_delete(\u0024input: DeleteBoostyCredentialsInput!) {
  admin {
    payload: deleteBoostyCredentials(input: \u0024input) {
      __typename
      ... on ErrorPayload {
        message
      }
      ... on DeleteBoostyCredentialsPayload {
        boostyCredentials {
          id
        }
      }
    }
  }
}`, variables, opts) as trip2g_admin_boostycredentials_button_delete_deleteMutation
}

}
