// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type trip2g_admin_healthchecks_listQueryVariables = Exact<{ [key: string]: never; }>;


export type trip2g_admin_healthchecks_listQuery = { __typename?: 'Query', admin: { __typename?: 'AdminQuery', healthChecks: Array<{ __typename?: 'HealchCheck', id: string, status: HealthCheckStatus, description: string }> } };


export function $trip2g_admin_healthchecks_list(opts?: { revalidate?: boolean }): trip2g_admin_healthchecks_listQuery {
	return $trip2g_gql_request(`query trip2g_admin_healthchecks_list {
  admin {
    healthChecks {
      id
      status
      description
    }
  }
}`, undefined, opts) as trip2g_admin_healthchecks_listQuery
}

}
