// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type trip2g_admin_offer_create_createMutationVariables = Exact<{
  input: CreateOfferInput;
}>;


export type trip2g_admin_offer_create_createMutation = { __typename?: 'Mutation', admin: { __typename?: 'AdminMutation', payload: { __typename: 'CreateOfferPayload', offer: { __typename?: 'AdminOffer', id: any, publicId: string } } | { __typename: 'ErrorPayload', message: string } } };


export function $trip2g_admin_offer_create_create(variables: trip2g_admin_offer_create_createMutationVariables, opts?: { revalidate?: boolean }): trip2g_admin_offer_create_createMutation {
	return $trip2g_gql_request(`mutation trip2g_admin_offer_create_create(\u0024input: CreateOfferInput!) {
  admin {
    payload: createOffer(input: \u0024input) {
      __typename
      ... on CreateOfferPayload {
        offer {
          id
          publicId
        }
      }
      ... on ErrorPayload {
        message
      }
    }
  }
}`, variables, opts) as trip2g_admin_offer_create_createMutation
}

}
