// Code generated by qtc from "view.qtpl". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line view.qtpl:1
package rendernotepage

//line view.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line view.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line view.qtpl:1
func StreamNote(qw422016 *qt422016.Writer, resp *Response) {
//line view.qtpl:1
	qw422016.N().S(`

<div class="flex">
  `)
//line view.qtpl:4
	if sidebar := resp.Sidebar(); sidebar != nil {
//line view.qtpl:4
		qw422016.N().S(`
  <div class="w-60 pr-8">
    `)
//line view.qtpl:6
		qw422016.N().S(string(sidebar.HTML))
//line view.qtpl:6
		qw422016.N().S(`
  </div>
  `)
//line view.qtpl:8
	}
//line view.qtpl:8
	qw422016.N().S(`

  <div class="flex-1">

  <h1 class="text-2xl font-bold">`)
//line view.qtpl:12
	qw422016.E().S(resp.Page.Title)
//line view.qtpl:12
	qw422016.N().S(`</h1>

  <div class="prose">
  `)
//line view.qtpl:15
	qw422016.N().S(string(resp.Page.HTML))
//line view.qtpl:15
	qw422016.N().S(`
  </div>

  `)
//line view.qtpl:18
	if len(resp.Page.InLinks) > 0 {
//line view.qtpl:18
		qw422016.N().S(`

    <h2 class="font-bold mt-4">Linked from</h2>

    `)
//line view.qtpl:22
		for k := range resp.Page.InLinks {
//line view.qtpl:22
			qw422016.N().S(`
      `)
//line view.qtpl:23
			if inPage, ok := resp.Pages[k]; ok {
//line view.qtpl:23
				qw422016.N().S(`
        <div><a href="`)
//line view.qtpl:24
				qw422016.E().S(inPage.Permalink)
//line view.qtpl:24
				qw422016.N().S(`">`)
//line view.qtpl:24
				qw422016.E().S(inPage.Title)
//line view.qtpl:24
				qw422016.N().S(`</a></div>
      `)
//line view.qtpl:25
			}
//line view.qtpl:25
			qw422016.N().S(`
    `)
//line view.qtpl:26
		}
//line view.qtpl:26
		qw422016.N().S(`

  `)
//line view.qtpl:28
	}
//line view.qtpl:28
	qw422016.N().S(`
  </div>

`)
//line view.qtpl:31
}

//line view.qtpl:31
func WriteNote(qq422016 qtio422016.Writer, resp *Response) {
//line view.qtpl:31
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view.qtpl:31
	StreamNote(qw422016, resp)
//line view.qtpl:31
	qt422016.ReleaseWriter(qw422016)
//line view.qtpl:31
}

//line view.qtpl:31
func Note(resp *Response) string {
//line view.qtpl:31
	qb422016 := qt422016.AcquireByteBuffer()
//line view.qtpl:31
	WriteNote(qb422016, resp)
//line view.qtpl:31
	qs422016 := string(qb422016.B)
//line view.qtpl:31
	qt422016.ReleaseByteBuffer(qb422016)
//line view.qtpl:31
	return qs422016
//line view.qtpl:31
}

//line view.qtpl:33
func StreamNotFound(qw422016 *qt422016.Writer) {
//line view.qtpl:33
	qw422016.N().S(`
<div>
  Page not found.
</div>
`)
//line view.qtpl:37
}

//line view.qtpl:37
func WriteNotFound(qq422016 qtio422016.Writer) {
//line view.qtpl:37
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view.qtpl:37
	StreamNotFound(qw422016)
//line view.qtpl:37
	qt422016.ReleaseWriter(qw422016)
//line view.qtpl:37
}

//line view.qtpl:37
func NotFound() string {
//line view.qtpl:37
	qb422016 := qt422016.AcquireByteBuffer()
//line view.qtpl:37
	WriteNotFound(qb422016)
//line view.qtpl:37
	qs422016 := string(qb422016.B)
//line view.qtpl:37
	qt422016.ReleaseByteBuffer(qb422016)
//line view.qtpl:37
	return qs422016
//line view.qtpl:37
}

//line view.qtpl:39
func StreamLayoutHeader(qw422016 *qt422016.Writer, resp *Response) {
//line view.qtpl:39
	qw422016.N().S(`
<!DOCTYPE html>

<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1" />
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-capable" content="yes">

<title>`)
//line view.qtpl:47
	qw422016.E().S(resp.Title)
//line view.qtpl:47
	qw422016.N().S(`</title>
<link href="/assets/output.css" rel="stylesheet">

<div id="all-content">

<header class="container mx-auto px-4 py-2">
  <a href="/">Home</a>
</header>

<main class="container mx-auto px-4 py-2">
`)
//line view.qtpl:57
}

//line view.qtpl:57
func WriteLayoutHeader(qq422016 qtio422016.Writer, resp *Response) {
//line view.qtpl:57
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view.qtpl:57
	StreamLayoutHeader(qw422016, resp)
//line view.qtpl:57
	qt422016.ReleaseWriter(qw422016)
//line view.qtpl:57
}

//line view.qtpl:57
func LayoutHeader(resp *Response) string {
//line view.qtpl:57
	qb422016 := qt422016.AcquireByteBuffer()
//line view.qtpl:57
	WriteLayoutHeader(qb422016, resp)
//line view.qtpl:57
	qs422016 := string(qb422016.B)
//line view.qtpl:57
	qt422016.ReleaseByteBuffer(qb422016)
//line view.qtpl:57
	return qs422016
//line view.qtpl:57
}

//line view.qtpl:59
func StreamLayoutFooter(qw422016 *qt422016.Writer) {
//line view.qtpl:59
	qw422016.N().S(`

</main>
</div>

<script src="/ui/auth/-/web.js"></script>

`)
//line view.qtpl:66
}

//line view.qtpl:66
func WriteLayoutFooter(qq422016 qtio422016.Writer) {
//line view.qtpl:66
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view.qtpl:66
	StreamLayoutFooter(qw422016)
//line view.qtpl:66
	qt422016.ReleaseWriter(qw422016)
//line view.qtpl:66
}

//line view.qtpl:66
func LayoutFooter() string {
//line view.qtpl:66
	qb422016 := qt422016.AcquireByteBuffer()
//line view.qtpl:66
	WriteLayoutFooter(qb422016)
//line view.qtpl:66
	qs422016 := string(qb422016.B)
//line view.qtpl:66
	qt422016.ReleaseByteBuffer(qb422016)
//line view.qtpl:66
	return qs422016
//line view.qtpl:66
}

//line view.qtpl:68
func StreamPayWall(qw422016 *qt422016.Writer, resp *Response, err *PaywallError) {
//line view.qtpl:68
	qw422016.N().S(`

<h1 class="text-2xl font-bold">`)
//line view.qtpl:70
	qw422016.E().S(resp.Page.Title)
//line view.qtpl:70
	qw422016.N().S(`</h1>

<p>
  Эта страница доступна только для подписчиков. Авторизуйтесь или купите подписку.
</p>
<p>`)
//line view.qtpl:75
	qw422016.E().S(err.Message)
//line view.qtpl:75
	qw422016.N().S(`</p>

<div mol_view_root>
  <div mol_view_root="$trip2g_auth"></div>
</div>

<form action="/_system/signin" method="post" class="max-w-3xs mt-8">
  <input type="hidden" name="return_to" value="">
  <div class="mb-4">
    <label class="block text-gray-700 text-sm font-bold mb-2" for="email">
      Email
    </label>
    <input
      class="shadow appearance-none border rounded w-full py-2 px-3 text-gray-700 leading-tight focus:outline-none focus:shadow-outline"
      value="test@example.com"
      id="email" type="text" name="email" placeholder="Имя пользователя">
  </div>
  <div class="mb-6">
    <label class="block text-gray-700 text-sm font-bold mb-2" for="password">
      Пароль
    </label>
    <input
      class="shadow appearance-none border border-red rounded w-full py-2 px-3 text-gray-700 mb-3 leading-tight focus:outline-none focus:shadow-outline"
      value="X173T6pThLNm"
      id="password" type="password" name="password" placeholder="******************">
  </div>
  <div class="flex items-center justify-between">
    <button
      class="bg-blue-500 hover:bg-blue-700 text-white font-bold py-2 px-4 rounded focus:outline-none focus:shadow-outline"
      type="submit">
      Войти
    </button>
  </div>
</form>

`)
//line view.qtpl:110
}

//line view.qtpl:110
func WritePayWall(qq422016 qtio422016.Writer, resp *Response, err *PaywallError) {
//line view.qtpl:110
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view.qtpl:110
	StreamPayWall(qw422016, resp, err)
//line view.qtpl:110
	qt422016.ReleaseWriter(qw422016)
//line view.qtpl:110
}

//line view.qtpl:110
func PayWall(resp *Response, err *PaywallError) string {
//line view.qtpl:110
	qb422016 := qt422016.AcquireByteBuffer()
//line view.qtpl:110
	WritePayWall(qb422016, resp, err)
//line view.qtpl:110
	qs422016 := string(qb422016.B)
//line view.qtpl:110
	qt422016.ReleaseByteBuffer(qb422016)
//line view.qtpl:110
	return qs422016
//line view.qtpl:110
}
