// Code generated by qtc from "view.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line view.html:1
package rendernotepage

//line view.html:1
import "trip2g/internal/model"

//line view.html:3
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line view.html:3
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line view.html:3
func StreamNote(qw422016 *qt422016.Writer, resp *Response) {
//line view.html:3
	qw422016.N().S(`

<div class="noteview" id="noteview-layout">
  <div class="noteview__header">
    `)
//line view.html:7
	StreamSidebar(qw422016, resp)
//line view.html:7
	qw422016.N().S(`

    <div class="noteview__header-space"></div>

    <div>
      <div mol_view_root="$trip2g_user_space"></div>
    </div>
  </div>

  <div mol_view_root="$trip2g_user_search"></div>

  `)
//line view.html:18
	StreamNoteContent(qw422016, resp)
//line view.html:18
	qw422016.N().S(`
</div>

`)
//line view.html:21
}

//line view.html:21
func WriteNote(qq422016 qtio422016.Writer, resp *Response) {
//line view.html:21
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view.html:21
	StreamNote(qw422016, resp)
//line view.html:21
	qt422016.ReleaseWriter(qw422016)
//line view.html:21
}

//line view.html:21
func Note(resp *Response) string {
//line view.html:21
	qb422016 := qt422016.AcquireByteBuffer()
//line view.html:21
	WriteNote(qb422016, resp)
//line view.html:21
	qs422016 := string(qb422016.B)
//line view.html:21
	qt422016.ReleaseByteBuffer(qb422016)
//line view.html:21
	return qs422016
//line view.html:21
}

//line view.html:23
func StreamTurboNote(qw422016 *qt422016.Writer, resp *Response) {
//line view.html:23
	qw422016.N().S(`
<div id="title">`)
//line view.html:24
	qw422016.E().S(resp.Title)
//line view.html:24
	qw422016.N().S(`</div>
`)
//line view.html:25
	StreamNoteContent(qw422016, resp)
//line view.html:25
	qw422016.N().S(`
`)
//line view.html:26
	StreamSidebar(qw422016, resp)
//line view.html:26
	qw422016.N().S(`
`)
//line view.html:27
}

//line view.html:27
func WriteTurboNote(qq422016 qtio422016.Writer, resp *Response) {
//line view.html:27
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view.html:27
	StreamTurboNote(qw422016, resp)
//line view.html:27
	qt422016.ReleaseWriter(qw422016)
//line view.html:27
}

//line view.html:27
func TurboNote(resp *Response) string {
//line view.html:27
	qb422016 := qt422016.AcquireByteBuffer()
//line view.html:27
	WriteTurboNote(qb422016, resp)
//line view.html:27
	qs422016 := string(qb422016.B)
//line view.html:27
	qt422016.ReleaseByteBuffer(qb422016)
//line view.html:27
	return qs422016
//line view.html:27
}

//line view.html:29
func StreamNoteContent(qw422016 *qt422016.Writer, resp *Response) {
//line view.html:29
	qw422016.N().S(`

  <div class="noteview__content noteview--`)
//line view.html:31
	qw422016.E().S(resp.UserRole)
//line view.html:31
	qw422016.N().S(`" id="noteview-content">

    <style type="text/css">
      `)
//line view.html:34
	if resp.UserToken != nil {
//line view.html:34
		qw422016.N().S(`
      .paywall\:core::before { display: none }
      `)
//line view.html:36
	}
//line view.html:36
	qw422016.N().S(`
      `)
//line view.html:37
	for _, k := range resp.UserSubgraphs {
//line view.html:37
		qw422016.N().S(`
      .paywall-`)
//line view.html:38
		qw422016.E().S(k)
//line view.html:38
		qw422016.N().S(`::before { display: none }
      `)
//line view.html:39
	}
//line view.html:39
	qw422016.N().S(`
    </style>

    `)
//line view.html:42
	if resp.NoteView.HasLangAlternatives() {
//line view.html:42
		qw422016.N().S(`
      <div class="lang-switcher">
        <span class="lang-switcher__label">Read in:</span>
        <details class="lang-switcher__picker">
          <summary class="lang-switcher__current lang-switcher__current--`)
//line view.html:46
		qw422016.E().S(resp.NoteView.Lang())
//line view.html:46
		qw422016.N().S(`">`)
//line view.html:46
		qw422016.E().S(resp.NoteView.LangName())
//line view.html:46
		qw422016.N().S(`</summary>
          <div class="lang-switcher__dropdown">
            `)
//line view.html:48
		for _, alt := range resp.NoteView.LangAlternativesList() {
//line view.html:48
			qw422016.N().S(`
            <a href="`)
//line view.html:49
			qw422016.E().S(alt.Permalink())
//line view.html:49
			qw422016.N().S(`" class="lang-switcher__alt lang-switcher__alt--`)
//line view.html:49
			qw422016.E().S(alt.Lang())
//line view.html:49
			qw422016.N().S(`">`)
//line view.html:49
			qw422016.E().S(alt.LangName())
//line view.html:49
			qw422016.N().S(`</a>
            `)
//line view.html:50
		}
//line view.html:50
		qw422016.N().S(`
          </div>
        </details>
      </div>
    `)
//line view.html:54
	}
//line view.html:54
	qw422016.N().S(`

    <div class="noteview__content-header">
      `)
//line view.html:57
	if !resp.Note.IsHomePage() {
//line view.html:57
		qw422016.N().S(`
      <h1 class="noteview__main-title">
        `)
//line view.html:59
		qw422016.E().S(resp.Note.Title)
//line view.html:59
		qw422016.N().S(`
        <span mol_view_root="$trip2g_user_favoritenote" class="noteview__favorite" data-pid="`)
//line view.html:60
		qw422016.N().DL(resp.Note.PathID)
//line view.html:60
		qw422016.N().S(`"></span>
      </h1>
      `)
//line view.html:62
	}
//line view.html:62
	qw422016.N().S(`

      `)
//line view.html:64
	StreamReadingMeta(qw422016, resp)
//line view.html:64
	qw422016.N().S(`
    </div>

    <div class="noteview__container">
      <div class="noteview__left-column">
        <div class="noteview__markup prose prose-stone prose-lg">
        `)
//line view.html:70
	qw422016.N().S(string(resp.NoteHTML()))
//line view.html:70
	qw422016.N().S(`
        </div>

        `)
//line view.html:73
	if len(resp.Note.InLinks) > 0 {
//line view.html:73
		qw422016.N().S(`
        <div class="noteview__footer">
          <h2 class="sidebar__block-title">Связанные страницы:</h2>

          <div class="sidebar__block-content">
            `)
//line view.html:78
		for k := range resp.Note.InLinks {
//line view.html:78
			qw422016.N().S(`
              `)
//line view.html:79
			if inNote := resp.Notes.GetByPath(k); inNote != nil {
//line view.html:79
				qw422016.N().S(`
                <div class="sidebar__block-link">
                  <a href="`)
//line view.html:81
				qw422016.E().S(resp.Notes.ResolveURL(inNote))
//line view.html:81
				qw422016.N().S(`">`)
//line view.html:81
				qw422016.E().S(inNote.Title)
//line view.html:81
				qw422016.N().S(`</a>
                </div>
              `)
//line view.html:83
			}
//line view.html:83
			qw422016.N().S(`
            `)
//line view.html:84
		}
//line view.html:84
		qw422016.N().S(`
          </div>
        </div>
        `)
//line view.html:87
	}
//line view.html:87
	qw422016.N().S(`
      </div>
      <div class="noteview__sidebar hidden lg:block">
        `)
//line view.html:90
	StreamTableOfContents(qw422016, resp)
//line view.html:90
	qw422016.N().S(`
      </div>
    </div>

  </div>

`)
//line view.html:96
}

//line view.html:96
func WriteNoteContent(qq422016 qtio422016.Writer, resp *Response) {
//line view.html:96
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view.html:96
	StreamNoteContent(qw422016, resp)
//line view.html:96
	qt422016.ReleaseWriter(qw422016)
//line view.html:96
}

//line view.html:96
func NoteContent(resp *Response) string {
//line view.html:96
	qb422016 := qt422016.AcquireByteBuffer()
//line view.html:96
	WriteNoteContent(qb422016, resp)
//line view.html:96
	qs422016 := string(qb422016.B)
//line view.html:96
	qt422016.ReleaseByteBuffer(qb422016)
//line view.html:96
	return qs422016
//line view.html:96
}

//line view.html:98
func StreamLatestBanner(qw422016 *qt422016.Writer, resp *Response) {
//line view.html:98
	qw422016.N().S(`

      `)
//line view.html:100
	if vb := resp.versionBanner; vb != nil {
//line view.html:100
		qw422016.N().S(`
        <div class="sidebar__latest-banner">
          <div>`)
//line view.html:102
		qw422016.N().S(vb.Label)
//line view.html:102
		qw422016.N().S(`</div>
          <a href="`)
//line view.html:103
		qw422016.N().S(vb.Permalink)
//line view.html:103
		qw422016.N().S(`">Перейти</a>
        </div>
      `)
//line view.html:105
	}
//line view.html:105
	qw422016.N().S(`

`)
//line view.html:107
}

//line view.html:107
func WriteLatestBanner(qq422016 qtio422016.Writer, resp *Response) {
//line view.html:107
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view.html:107
	StreamLatestBanner(qw422016, resp)
//line view.html:107
	qt422016.ReleaseWriter(qw422016)
//line view.html:107
}

//line view.html:107
func LatestBanner(resp *Response) string {
//line view.html:107
	qb422016 := qt422016.AcquireByteBuffer()
//line view.html:107
	WriteLatestBanner(qb422016, resp)
//line view.html:107
	qs422016 := string(qb422016.B)
//line view.html:107
	qt422016.ReleaseByteBuffer(qb422016)
//line view.html:107
	return qs422016
//line view.html:107
}

//line view.html:109
func StreamSidebar(qw422016 *qt422016.Writer, resp *Response) {
//line view.html:109
	qw422016.N().S(`

    <div id="noteview-sidebar" class="sidebar">
      `)
//line view.html:112
	StreamLatestBanner(qw422016, resp)
//line view.html:112
	qw422016.N().S(`

      `)
//line view.html:114
	if homePages := resp.Notes.HomePages(resp.Note); len(homePages) > 0 {
//line view.html:114
		qw422016.N().S(`
        <div class="sidebar__homepages">
          `)
//line view.html:116
		for _, homePage := range homePages {
//line view.html:116
			qw422016.N().S(`
          <div class="sidebar__homepage">
            <a href="`)
//line view.html:118
			qw422016.N().S(resp.Notes.ResolveURL(homePage))
//line view.html:118
			qw422016.N().S(`">`)
//line view.html:118
			qw422016.N().S(homePage.Title)
//line view.html:118
			qw422016.N().S(`</a>
          </div>
          `)
//line view.html:120
		}
//line view.html:120
		qw422016.N().S(`
        </div>
      `)
//line view.html:122
	}
//line view.html:122
	qw422016.N().S(`

      `)
//line view.html:124
	if sidebars := resp.Notes.Sidebars(resp.Note); len(sidebars) > 0 {
//line view.html:124
		qw422016.N().S(`
        <div class="sidebar__menus">
          `)
//line view.html:126
		for _, sidebar := range sidebars {
//line view.html:126
			qw422016.N().S(`
          <div class="sidebar__menu">
            `)
//line view.html:128
			qw422016.N().S(string(resp.SidebarHTML(sidebar)))
//line view.html:128
			qw422016.N().S(`
          </div>
          `)
//line view.html:130
		}
//line view.html:130
		qw422016.N().S(`
        </div>
      `)
//line view.html:132
	} else {
//line view.html:132
		qw422016.N().S(`
        <div class="sidebar__menu">
          <ul>
            <li><a href="/">Главная</a></li>
          </ul>
        </div>
      `)
//line view.html:138
	}
//line view.html:138
	qw422016.N().S(`
    </div>

`)
//line view.html:141
}

//line view.html:141
func WriteSidebar(qq422016 qtio422016.Writer, resp *Response) {
//line view.html:141
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view.html:141
	StreamSidebar(qw422016, resp)
//line view.html:141
	qt422016.ReleaseWriter(qw422016)
//line view.html:141
}

//line view.html:141
func Sidebar(resp *Response) string {
//line view.html:141
	qb422016 := qt422016.AcquireByteBuffer()
//line view.html:141
	WriteSidebar(qb422016, resp)
//line view.html:141
	qs422016 := string(qb422016.B)
//line view.html:141
	qt422016.ReleaseByteBuffer(qb422016)
//line view.html:141
	return qs422016
//line view.html:141
}

//line view.html:143
func StreamReadingMeta(qw422016 *qt422016.Writer, resp *Response) {
//line view.html:143
	qw422016.N().S(`
<div class="reading-meta">
  <span class="reading-time">
    <span class="reading-time__label">Создано:</span>
    `)
//line view.html:147
	qw422016.E().S(resp.Note.CreatedAt.Format("2006-01-02 15:04"))
//line view.html:147
	qw422016.N().S(`
  </span>

  `)
//line view.html:150
	if resp.ViewedAt != nil {
//line view.html:150
		qw422016.N().S(`
  <span class="reading-time">
    <span class="reading-time__label">Вы читали:</span>
    `)
//line view.html:153
		qw422016.E().S(resp.ViewedAt.Format("2006-01-02 15:04"))
//line view.html:153
		qw422016.N().S(`
  </span>
  `)
//line view.html:155
	}
//line view.html:155
	qw422016.N().S(`

  `)
//line view.html:157
	if resp.Note.ReadingTime >= 2 {
//line view.html:157
		qw422016.N().S(`
  <span class="reading-time">
    <span class="reading-meta__label">Время чтения:</span>
    `)
//line view.html:160
		qw422016.N().D(resp.Note.ReadingTime)
//line view.html:160
		qw422016.N().S(` мин
  </span>
  `)
//line view.html:162
	}
//line view.html:162
	qw422016.N().S(`

  `)
//line view.html:164
	if resp.Note.ReadingComplexity > 0 {
//line view.html:164
		qw422016.N().S(`
  <span class="reading-complexity">
    <span class="reading-meta__label">Сложность:</span>
    `)
//line view.html:167
		StreamReadingComplexityStars(qw422016, resp.Note.ReadingComplexity)
//line view.html:167
		qw422016.N().S(`
  </span>
  `)
//line view.html:169
	}
//line view.html:169
	qw422016.N().S(`
</div>
`)
//line view.html:171
}

//line view.html:171
func WriteReadingMeta(qq422016 qtio422016.Writer, resp *Response) {
//line view.html:171
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view.html:171
	StreamReadingMeta(qw422016, resp)
//line view.html:171
	qt422016.ReleaseWriter(qw422016)
//line view.html:171
}

//line view.html:171
func ReadingMeta(resp *Response) string {
//line view.html:171
	qb422016 := qt422016.AcquireByteBuffer()
//line view.html:171
	WriteReadingMeta(qb422016, resp)
//line view.html:171
	qs422016 := string(qb422016.B)
//line view.html:171
	qt422016.ReleaseByteBuffer(qb422016)
//line view.html:171
	return qs422016
//line view.html:171
}

//line view.html:173
func StreamReadingComplexityStars(qw422016 *qt422016.Writer, complexity int) {
//line view.html:173
	qw422016.N().S(`
<span class="complexity-stars" title="`)
//line view.html:174
	if complexity == 1 {
//line view.html:174
		qw422016.N().S(`Среднее чтение`)
//line view.html:174
	} else if complexity == 2 {
//line view.html:174
		qw422016.N().S(`Сложное чтение`)
//line view.html:174
	} else {
//line view.html:174
		qw422016.N().S(`Легкое чтение`)
//line view.html:174
	}
//line view.html:174
	qw422016.N().S(`">
  `)
//line view.html:175
	for i := 0; i < complexity; i++ {
//line view.html:175
		qw422016.N().S(`
    <span class="star">★</span>
  `)
//line view.html:177
	}
//line view.html:177
	qw422016.N().S(`
</span>
`)
//line view.html:179
}

//line view.html:179
func WriteReadingComplexityStars(qq422016 qtio422016.Writer, complexity int) {
//line view.html:179
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view.html:179
	StreamReadingComplexityStars(qw422016, complexity)
//line view.html:179
	qt422016.ReleaseWriter(qw422016)
//line view.html:179
}

//line view.html:179
func ReadingComplexityStars(complexity int) string {
//line view.html:179
	qb422016 := qt422016.AcquireByteBuffer()
//line view.html:179
	WriteReadingComplexityStars(qb422016, complexity)
//line view.html:179
	qs422016 := string(qb422016.B)
//line view.html:179
	qt422016.ReleaseByteBuffer(qb422016)
//line view.html:179
	return qs422016
//line view.html:179
}

//line view.html:181
func StreamPayWall(qw422016 *qt422016.Writer, resp *Response, err *PaywallError) {
//line view.html:181
	qw422016.N().S(`

<div class="noteview" id="noteview-layout">
  <div class="noteview__header">
    `)
//line view.html:185
	StreamSidebar(qw422016, resp)
//line view.html:185
	qw422016.N().S(`

    <div class="noteview__header-space"></div>

    <div>
      <div mol_view_root="$trip2g_user_space"></div>
    </div>
  </div>

  <div mol_view_root="$trip2g_user_search"></div>

  <div class="noteview__content" id="noteview-content">
    `)
//line view.html:197
	if !resp.Note.IsHomePage() {
//line view.html:197
		qw422016.N().S(`
    <h1 class="noteview__main-title">`)
//line view.html:198
		qw422016.E().S(resp.Note.Title)
//line view.html:198
		qw422016.N().S(`</h1>
    `)
//line view.html:199
	}
//line view.html:199
	qw422016.N().S(`

    `)
//line view.html:201
	StreamReadingMeta(qw422016, resp)
//line view.html:201
	qw422016.N().S(`


    `)
//line view.html:204
	if len(resp.Note.FreeHTML) > 0 {
//line view.html:204
		qw422016.N().S(`
    `)
//line view.html:205
		qw422016.N().S(string(resp.Note.FreeHTML))
//line view.html:205
		qw422016.N().S(`
    `)
//line view.html:206
	} else {
//line view.html:206
		qw422016.N().S(`
      `)
//line view.html:207
		if resp.Note.Description != nil {
//line view.html:207
			qw422016.N().S(`
      <p class="noteview__description">`)
//line view.html:208
			qw422016.N().S(*resp.Note.Description)
//line view.html:208
			qw422016.N().S(`</p>
      `)
//line view.html:209
		}
//line view.html:209
		qw422016.N().S(`
    `)
//line view.html:210
	}
//line view.html:210
	qw422016.N().S(`

    <script>
      window.__trip2g_paywall = {
        page_id: `)
//line view.html:214
	qw422016.N().DL(resp.Note.PathID)
//line view.html:214
	qw422016.N().S(`,
      }
    </script>

    <div
      id="paywall"
      mol_view_root="$trip2g_user_paywall"
      data-subgraphs="`)
//line view.html:221
	qw422016.E().S(resp.NoteSubgraphsJSON())
//line view.html:221
	qw422016.N().S(`"
      data-path-id="`)
//line view.html:222
	qw422016.N().DL(resp.Note.PathID)
//line view.html:222
	qw422016.N().S(`"
    ></div>
  </div>
</div>

`)
//line view.html:227
}

//line view.html:227
func WritePayWall(qq422016 qtio422016.Writer, resp *Response, err *PaywallError) {
//line view.html:227
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view.html:227
	StreamPayWall(qw422016, resp, err)
//line view.html:227
	qt422016.ReleaseWriter(qw422016)
//line view.html:227
}

//line view.html:227
func PayWall(resp *Response, err *PaywallError) string {
//line view.html:227
	qb422016 := qt422016.AcquireByteBuffer()
//line view.html:227
	WritePayWall(qb422016, resp, err)
//line view.html:227
	qs422016 := string(qb422016.B)
//line view.html:227
	qt422016.ReleaseByteBuffer(qb422016)
//line view.html:227
	return qs422016
//line view.html:227
}

//line view.html:229
func StreamOnboarding(qw422016 *qt422016.Writer, resp *Response) {
//line view.html:229
	qw422016.N().S(`

<div class="noteview" id="noteview-layout" data-onboarding>
  <div class="noteview__header">
    <div id="noteview-sidebar" class="sidebar">
      <div class="sidebar__menu">
        <ul>
          <li><a href="/">Главная</a></li>
        </ul>
      </div>
    </div>

    <div class="noteview__header-space"></div>

    <div>
      <div mol_view_root="$trip2g_user_space"></div>
    </div>
  </div>

  <div class="noteview__content" id="noteview-content">
    <div class="noteview__container">
      <div class="noteview__left-column">
        <div class="noteview__markup prose prose-stone prose-lg">

          `)
//line view.html:253
	if resp.UserToken.IsAdmin() {
//line view.html:253
		qw422016.N().S(`
          <h3>Добро пожаловать!</h3>
          <p>
            Скачайте стартовый архив и откройте его в Obsidian.
            Будет создан API-ключ и упакован в ZIP-архив с демонстрационным хранилищем.
          </p>
          <p>
            Не передавайте этот архив никому, так как он содержит приватный ключ.
            Архив содержит только демонстрационное хранилище. Если у вас уже есть данные,
            двухсторонняя синхронизация предложит скачать актуальный контент с сервера.
          </p>
          <p>
            <a href="/_system/onboarding-vault" class="inline-block px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700">
              Скачать архив
            </a>
          </p>

          <hr>

          <h3>Welcome!</h3>
          <p>
            Download the starter archive and open it in Obsidian.
            An API key will be created and packed into a ZIP archive with a demo vault.
          </p>
          <p>
            Do not share this archive with anyone as it contains a private key.
            The archive contains only a demo vault. If you already have data,
            two-way sync will offer to download current content from the server.
          </p>
          <p>
            <a href="/_system/onboarding-vault" class="inline-block px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700">
              Download archive
            </a>
          </p>
          `)
//line view.html:287
	} else {
//line view.html:287
		qw422016.N().S(`
          <h3>Сайт в процессе настройки</h3>
          <p>Войдите как администратор, чтобы начать работу.</p>
          <p>
            <a href="#!userspace=open" class="inline-block px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700">
              Войти
            </a>
          </p>

          <hr>

          <h3>Site is being set up</h3>
          <p>Log in as administrator to get started.</p>
          <p>
            <a href="#!userspace=open" class="inline-block px-4 py-2 bg-blue-600 text-white rounded hover:bg-blue-700">
              Log in
            </a>
          </p>
          `)
//line view.html:305
	}
//line view.html:305
	qw422016.N().S(`

        </div>
      </div>
    </div>
  </div>
</div>

`)
//line view.html:313
}

//line view.html:313
func WriteOnboarding(qq422016 qtio422016.Writer, resp *Response) {
//line view.html:313
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view.html:313
	StreamOnboarding(qw422016, resp)
//line view.html:313
	qt422016.ReleaseWriter(qw422016)
//line view.html:313
}

//line view.html:313
func Onboarding(resp *Response) string {
//line view.html:313
	qb422016 := qt422016.AcquireByteBuffer()
//line view.html:313
	WriteOnboarding(qb422016, resp)
//line view.html:313
	qs422016 := string(qb422016.B)
//line view.html:313
	qt422016.ReleaseByteBuffer(qb422016)
//line view.html:313
	return qs422016
//line view.html:313
}

//line view.html:315
func StreamLayoutError(qw422016 *qt422016.Writer, resp *Response, layoutName string, warnings []model.NoteWarning) {
//line view.html:315
	qw422016.N().S(`

<div class="noteview" id="noteview-layout">
  <div class="noteview__header">
    `)
//line view.html:319
	StreamSidebar(qw422016, resp)
//line view.html:319
	qw422016.N().S(`

    <div class="noteview__header-space"></div>

    <div>
      <div mol_view_root="$trip2g_user_space"></div>
    </div>
  </div>

  <div class="noteview__content" id="noteview-content">
    <div class="noteview__container">
      <div class="noteview__left-column">
        <div style="background: #fee; border: 1px solid #c00; padding: 16px; margin-bottom: 16px; border-radius: 4px;">
          <h3 style="color: #c00; margin: 0 0 8px 0;">Layout Error: `)
//line view.html:332
	qw422016.E().S(layoutName)
//line view.html:332
	qw422016.N().S(`</h3>
          `)
//line view.html:333
	for _, w := range warnings {
//line view.html:333
		qw422016.N().S(`
          <pre style="background: #fff; padding: 8px; overflow-x: auto; margin: 8px 0;">`)
//line view.html:334
		qw422016.E().S(w.Message)
//line view.html:334
		qw422016.N().S(`</pre>
          `)
//line view.html:335
	}
//line view.html:335
	qw422016.N().S(`
        </div>

        <div class="noteview__markup prose prose-stone prose-lg">
          `)
//line view.html:339
	qw422016.N().S(string(resp.NoteHTML()))
//line view.html:339
	qw422016.N().S(`
        </div>
      </div>
    </div>
  </div>
</div>

`)
//line view.html:346
}

//line view.html:346
func WriteLayoutError(qq422016 qtio422016.Writer, resp *Response, layoutName string, warnings []model.NoteWarning) {
//line view.html:346
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view.html:346
	StreamLayoutError(qw422016, resp, layoutName, warnings)
//line view.html:346
	qt422016.ReleaseWriter(qw422016)
//line view.html:346
}

//line view.html:346
func LayoutError(resp *Response, layoutName string, warnings []model.NoteWarning) string {
//line view.html:346
	qb422016 := qt422016.AcquireByteBuffer()
//line view.html:346
	WriteLayoutError(qb422016, resp, layoutName, warnings)
//line view.html:346
	qs422016 := string(qb422016.B)
//line view.html:346
	qt422016.ReleaseByteBuffer(qb422016)
//line view.html:346
	return qs422016
//line view.html:346
}

//line view.html:348
func StreamTableOfContents(qw422016 *qt422016.Writer, resp *Response) {
//line view.html:348
	qw422016.N().S(`
`)
//line view.html:349
	toc := resp.Note.TOC()

//line view.html:349
	qw422016.N().S(`
`)
//line view.html:350
	if len(toc) > 0 {
//line view.html:350
		qw422016.N().S(`
<div class="noteview__toc toc" id="noteview-toc" id="noteview-toc">
  <h2 class="toc__title">Содержание</h2>
  `)
//line view.html:353
		for _, item := range toc {
//line view.html:353
			qw422016.N().S(`
    <div class="toc__item toc__item--level`)
//line view.html:354
			qw422016.N().D(item.Level)
//line view.html:354
			qw422016.N().S(`">
      <a href="#`)
//line view.html:355
			qw422016.N().S(item.ID)
//line view.html:355
			qw422016.N().S(`" class="toc__link">`)
//line view.html:355
			qw422016.N().S(item.Text)
//line view.html:355
			qw422016.N().S(`</a>
    </div>
  `)
//line view.html:357
		}
//line view.html:357
		qw422016.N().S(`
</div>
`)
//line view.html:359
	}
//line view.html:359
	qw422016.N().S(`
`)
//line view.html:360
}

//line view.html:360
func WriteTableOfContents(qq422016 qtio422016.Writer, resp *Response) {
//line view.html:360
	qw422016 := qt422016.AcquireWriter(qq422016)
//line view.html:360
	StreamTableOfContents(qw422016, resp)
//line view.html:360
	qt422016.ReleaseWriter(qw422016)
//line view.html:360
}

//line view.html:360
func TableOfContents(resp *Response) string {
//line view.html:360
	qb422016 := qt422016.AcquireByteBuffer()
//line view.html:360
	WriteTableOfContents(qb422016, resp)
//line view.html:360
	qs422016 := string(qb422016.B)
//line view.html:360
	qt422016.ReleaseByteBuffer(qb422016)
//line view.html:360
	return qs422016
//line view.html:360
}
