// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package updateboostycredentials_test

import (
	"context"
	"sync"
	"trip2g/internal/case/admin/updateboostycredentials"
	"trip2g/internal/db"
)

// Ensure, that EnvMock does implement updateboostycredentials.Env.
// If this is not the case, regenerate this file with moq.
var _ updateboostycredentials.Env = &EnvMock{}

// EnvMock is a mock implementation of updateboostycredentials.Env.
//
//	func TestSomethingThatUsesEnv(t *testing.T) {
//
//		// make and configure a mocked updateboostycredentials.Env
//		mockedEnv := &EnvMock{
//			BoostyCredentialsFunc: func(ctx context.Context, id int64) (db.BoostyCredential, error) {
//				panic("mock out the BoostyCredentials method")
//			},
//			StartBoostyRefreshBackgroundJobFunc: func(ctx context.Context, credentialsID int64, immediately bool) error {
//				panic("mock out the StartBoostyRefreshBackgroundJob method")
//			},
//			StopBoostyRefreshBackgroundJobFunc: func(ctx context.Context, credentialsID int64) error {
//				panic("mock out the StopBoostyRefreshBackgroundJob method")
//			},
//			UpdateBoostyCredentialsFunc: func(ctx context.Context, arg db.UpdateBoostyCredentialsParams) (db.BoostyCredential, error) {
//				panic("mock out the UpdateBoostyCredentials method")
//			},
//		}
//
//		// use mockedEnv in code that requires updateboostycredentials.Env
//		// and then make assertions.
//
//	}
type EnvMock struct {
	// BoostyCredentialsFunc mocks the BoostyCredentials method.
	BoostyCredentialsFunc func(ctx context.Context, id int64) (db.BoostyCredential, error)

	// StartBoostyRefreshBackgroundJobFunc mocks the StartBoostyRefreshBackgroundJob method.
	StartBoostyRefreshBackgroundJobFunc func(ctx context.Context, credentialsID int64, immediately bool) error

	// StopBoostyRefreshBackgroundJobFunc mocks the StopBoostyRefreshBackgroundJob method.
	StopBoostyRefreshBackgroundJobFunc func(ctx context.Context, credentialsID int64) error

	// UpdateBoostyCredentialsFunc mocks the UpdateBoostyCredentials method.
	UpdateBoostyCredentialsFunc func(ctx context.Context, arg db.UpdateBoostyCredentialsParams) (db.BoostyCredential, error)

	// calls tracks calls to the methods.
	calls struct {
		// BoostyCredentials holds details about calls to the BoostyCredentials method.
		BoostyCredentials []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// StartBoostyRefreshBackgroundJob holds details about calls to the StartBoostyRefreshBackgroundJob method.
		StartBoostyRefreshBackgroundJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// CredentialsID is the credentialsID argument value.
			CredentialsID int64
			// Immediately is the immediately argument value.
			Immediately bool
		}
		// StopBoostyRefreshBackgroundJob holds details about calls to the StopBoostyRefreshBackgroundJob method.
		StopBoostyRefreshBackgroundJob []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// CredentialsID is the credentialsID argument value.
			CredentialsID int64
		}
		// UpdateBoostyCredentials holds details about calls to the UpdateBoostyCredentials method.
		UpdateBoostyCredentials []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.UpdateBoostyCredentialsParams
		}
	}
	lockBoostyCredentials               sync.RWMutex
	lockStartBoostyRefreshBackgroundJob sync.RWMutex
	lockStopBoostyRefreshBackgroundJob  sync.RWMutex
	lockUpdateBoostyCredentials         sync.RWMutex
}

// BoostyCredentials calls BoostyCredentialsFunc.
func (mock *EnvMock) BoostyCredentials(ctx context.Context, id int64) (db.BoostyCredential, error) {
	if mock.BoostyCredentialsFunc == nil {
		panic("EnvMock.BoostyCredentialsFunc: method is nil but Env.BoostyCredentials was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockBoostyCredentials.Lock()
	mock.calls.BoostyCredentials = append(mock.calls.BoostyCredentials, callInfo)
	mock.lockBoostyCredentials.Unlock()
	return mock.BoostyCredentialsFunc(ctx, id)
}

// BoostyCredentialsCalls gets all the calls that were made to BoostyCredentials.
// Check the length with:
//
//	len(mockedEnv.BoostyCredentialsCalls())
func (mock *EnvMock) BoostyCredentialsCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockBoostyCredentials.RLock()
	calls = mock.calls.BoostyCredentials
	mock.lockBoostyCredentials.RUnlock()
	return calls
}

// StartBoostyRefreshBackgroundJob calls StartBoostyRefreshBackgroundJobFunc.
func (mock *EnvMock) StartBoostyRefreshBackgroundJob(ctx context.Context, credentialsID int64, immediately bool) error {
	if mock.StartBoostyRefreshBackgroundJobFunc == nil {
		panic("EnvMock.StartBoostyRefreshBackgroundJobFunc: method is nil but Env.StartBoostyRefreshBackgroundJob was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		CredentialsID int64
		Immediately   bool
	}{
		Ctx:           ctx,
		CredentialsID: credentialsID,
		Immediately:   immediately,
	}
	mock.lockStartBoostyRefreshBackgroundJob.Lock()
	mock.calls.StartBoostyRefreshBackgroundJob = append(mock.calls.StartBoostyRefreshBackgroundJob, callInfo)
	mock.lockStartBoostyRefreshBackgroundJob.Unlock()
	return mock.StartBoostyRefreshBackgroundJobFunc(ctx, credentialsID, immediately)
}

// StartBoostyRefreshBackgroundJobCalls gets all the calls that were made to StartBoostyRefreshBackgroundJob.
// Check the length with:
//
//	len(mockedEnv.StartBoostyRefreshBackgroundJobCalls())
func (mock *EnvMock) StartBoostyRefreshBackgroundJobCalls() []struct {
	Ctx           context.Context
	CredentialsID int64
	Immediately   bool
} {
	var calls []struct {
		Ctx           context.Context
		CredentialsID int64
		Immediately   bool
	}
	mock.lockStartBoostyRefreshBackgroundJob.RLock()
	calls = mock.calls.StartBoostyRefreshBackgroundJob
	mock.lockStartBoostyRefreshBackgroundJob.RUnlock()
	return calls
}

// StopBoostyRefreshBackgroundJob calls StopBoostyRefreshBackgroundJobFunc.
func (mock *EnvMock) StopBoostyRefreshBackgroundJob(ctx context.Context, credentialsID int64) error {
	if mock.StopBoostyRefreshBackgroundJobFunc == nil {
		panic("EnvMock.StopBoostyRefreshBackgroundJobFunc: method is nil but Env.StopBoostyRefreshBackgroundJob was just called")
	}
	callInfo := struct {
		Ctx           context.Context
		CredentialsID int64
	}{
		Ctx:           ctx,
		CredentialsID: credentialsID,
	}
	mock.lockStopBoostyRefreshBackgroundJob.Lock()
	mock.calls.StopBoostyRefreshBackgroundJob = append(mock.calls.StopBoostyRefreshBackgroundJob, callInfo)
	mock.lockStopBoostyRefreshBackgroundJob.Unlock()
	return mock.StopBoostyRefreshBackgroundJobFunc(ctx, credentialsID)
}

// StopBoostyRefreshBackgroundJobCalls gets all the calls that were made to StopBoostyRefreshBackgroundJob.
// Check the length with:
//
//	len(mockedEnv.StopBoostyRefreshBackgroundJobCalls())
func (mock *EnvMock) StopBoostyRefreshBackgroundJobCalls() []struct {
	Ctx           context.Context
	CredentialsID int64
} {
	var calls []struct {
		Ctx           context.Context
		CredentialsID int64
	}
	mock.lockStopBoostyRefreshBackgroundJob.RLock()
	calls = mock.calls.StopBoostyRefreshBackgroundJob
	mock.lockStopBoostyRefreshBackgroundJob.RUnlock()
	return calls
}

// UpdateBoostyCredentials calls UpdateBoostyCredentialsFunc.
func (mock *EnvMock) UpdateBoostyCredentials(ctx context.Context, arg db.UpdateBoostyCredentialsParams) (db.BoostyCredential, error) {
	if mock.UpdateBoostyCredentialsFunc == nil {
		panic("EnvMock.UpdateBoostyCredentialsFunc: method is nil but Env.UpdateBoostyCredentials was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.UpdateBoostyCredentialsParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpdateBoostyCredentials.Lock()
	mock.calls.UpdateBoostyCredentials = append(mock.calls.UpdateBoostyCredentials, callInfo)
	mock.lockUpdateBoostyCredentials.Unlock()
	return mock.UpdateBoostyCredentialsFunc(ctx, arg)
}

// UpdateBoostyCredentialsCalls gets all the calls that were made to UpdateBoostyCredentials.
// Check the length with:
//
//	len(mockedEnv.UpdateBoostyCredentialsCalls())
func (mock *EnvMock) UpdateBoostyCredentialsCalls() []struct {
	Ctx context.Context
	Arg db.UpdateBoostyCredentialsParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.UpdateBoostyCredentialsParams
	}
	mock.lockUpdateBoostyCredentials.RLock()
	calls = mock.calls.UpdateBoostyCredentials
	mock.lockUpdateBoostyCredentials.RUnlock()
	return calls
}
