// Code generated by qtc from "views.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views.html:1
package defaulttemplate

//line views.html:1
import "encoding/json"

//line views.html:2
import "trip2g/internal/templateviews"

//line views.html:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views.html:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views.html:4
func StreamRender(qw422016 *qt422016.Writer, ctx *Ctx) {
//line views.html:4
	qw422016.N().S(`
<!DOCTYPE html>
<html`)
//line views.html:6
	if ctx.HTMLLang != "" {
//line views.html:6
		qw422016.N().S(` lang="`)
//line views.html:6
		qw422016.N().S(ctx.HTMLLang)
//line views.html:6
		qw422016.N().S(`"`)
//line views.html:6
	}
//line views.html:6
	qw422016.N().S(`>
<head>
<meta charset="UTF-8">
<script>try{var d=localStorage.getItem('$mol_lights')!=='true',r=document.documentElement;r.classList.toggle('dark',d);r.classList.toggle('light',!d);r.setAttribute('data-theme',d?'dark':'light')}catch(e){}</script>
<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1" />
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-capable" content="yes">

`)
//line views.html:14
	for _, hl := range ctx.HrefLangs {
//line views.html:14
		qw422016.N().S(`<link rel="alternate" hreflang="`)
//line views.html:15
		qw422016.N().S(hl.Lang)
//line views.html:15
		qw422016.N().S(`" href="`)
//line views.html:15
		qw422016.N().S(hl.Href)
//line views.html:15
		qw422016.N().S(`">
`)
//line views.html:16
	}
//line views.html:17
	if ctx.EnableRSS && ctx.Note != nil {
//line views.html:17
		qw422016.N().S(`
<link rel="alternate" type="application/rss+xml" href="`)
//line views.html:18
		qw422016.N().S(ctx.Note.PermalinkEncoded())
//line views.html:18
		qw422016.N().S(`.rss.xml">
`)
//line views.html:19
	}
//line views.html:19
	qw422016.N().S(`

<link rel="icon" type="image/png" href="/assets/favicon-96x96.png" sizes="96x96" />
<link rel="icon" type="image/svg+xml" href="/assets/favicon.svg" />
<link rel="shortcut icon" href="/assets/favicon.ico" />
<link rel="apple-touch-icon" sizes="180x180" href="/assets/apple-touch-icon.png" />
<link rel="manifest" href="/assets/site.webmanifest" />

`)
//line views.html:27
	if ctx.MetaDescription != nil {
//line views.html:27
		qw422016.N().S(`
<meta name="description" content="`)
//line views.html:28
		qw422016.N().S(*ctx.MetaDescription)
//line views.html:28
		qw422016.N().S(`">
`)
//line views.html:29
	}
//line views.html:29
	qw422016.N().S(`

`)
//line views.html:31
	if len(ctx.MetaRobots) > 0 {
//line views.html:31
		qw422016.N().S(`
<meta name="robots" content="`)
//line views.html:32
		qw422016.N().S(ctx.MetaRobots)
//line views.html:32
		qw422016.N().S(`">
`)
//line views.html:33
	}
//line views.html:33
	qw422016.N().S(`

<meta property="og:title" content="`)
//line views.html:35
	qw422016.E().S(ctx.Title)
//line views.html:35
	qw422016.N().S(`">
`)
//line views.html:36
	if ctx.MetaDescription != nil {
//line views.html:36
		qw422016.N().S(`
<meta property="og:description" content="`)
//line views.html:37
		qw422016.N().S(*ctx.MetaDescription)
//line views.html:37
		qw422016.N().S(`">
`)
//line views.html:38
	}
//line views.html:38
	qw422016.N().S(`

`)
//line views.html:40
	if ctx.OGTags != nil {
//line views.html:40
		qw422016.N().S(`
`)
//line views.html:41
		for property, value := range ctx.OGTags {
//line views.html:41
			qw422016.N().S(`
<meta property="`)
//line views.html:42
			qw422016.N().S(property)
//line views.html:42
			qw422016.N().S(`" content="`)
//line views.html:42
			qw422016.N().S(value)
//line views.html:42
			qw422016.N().S(`">
`)
//line views.html:43
		}
//line views.html:43
		qw422016.N().S(`
`)
//line views.html:44
	}
//line views.html:44
	qw422016.N().S(`

<script>
window.__trip2g_settings = {
  is_dev_mode: `)
//line views.html:48
	qw422016.N().S(ctx.DevMode)
//line views.html:48
	qw422016.N().S(`,
  title: `)
//line views.html:49
	qw422016.N().Q(ctx.Title)
//line views.html:49
	qw422016.N().S(`,
  ui_lang: `)
//line views.html:50
	qw422016.N().Q(ctx.UILang)
//line views.html:50
	qw422016.N().S(`,
  js_urls: [`)
//line views.html:51
	for _, u := range ctx.JSURLs {
//line views.html:51
		qw422016.N().Q(u)
//line views.html:51
		qw422016.N().S(`,`)
//line views.html:51
	}
//line views.html:51
	qw422016.N().S(`],
`)
//line views.html:52
	if ctx.Note != nil {
//line views.html:52
		qw422016.N().S(`  note_lang: `)
//line views.html:52
		qw422016.N().Q(ctx.Note.Lang())
//line views.html:52
		qw422016.N().S(`,
  note_path: `)
//line views.html:53
		qw422016.N().Q(ctx.Note.Path())
//line views.html:53
		qw422016.N().S(`,
  note_path_id: `)
//line views.html:54
		qw422016.N().DL(ctx.Note.PathID())
//line views.html:54
		qw422016.N().S(`,
  note_version_id: `)
//line views.html:55
		qw422016.N().Q(ctx.Note.VersionID())
//line views.html:55
		qw422016.N().S(`,
`)
//line views.html:56
	}
//line views.html:56
	qw422016.N().S(`}
</script>

<title>`)
//line views.html:59
	qw422016.E().S(ctx.Title)
//line views.html:59
	qw422016.N().S(`</title>

`)
//line views.html:61
	if ctx.InlineCSS != "" {
//line views.html:61
		qw422016.N().S(`
<style>`)
//line views.html:62
		qw422016.N().S(ctx.InlineCSS)
//line views.html:62
		qw422016.N().S(`</style>
`)
//line views.html:63
	}
//line views.html:63
	qw422016.N().S(`
`)
//line views.html:64
	for _, url := range ctx.CSSURLs {
//line views.html:64
		qw422016.N().S(`
<link href="`)
//line views.html:65
		qw422016.E().S(url)
//line views.html:65
		qw422016.N().S(`" rel="stylesheet">
`)
//line views.html:66
	}
//line views.html:66
	qw422016.N().S(`

`)
//line views.html:68
	for _, injection := range ctx.HTMLInjections[injectionPlaceholderHead] {
//line views.html:68
		qw422016.N().S(`
`)
//line views.html:69
		qw422016.N().S(injection.Content)
//line views.html:69
		qw422016.N().S(`
`)
//line views.html:70
	}
//line views.html:70
	qw422016.N().S(`

</head>
<body>

`)
//line views.html:75
	if ctx.SigninWallError != nil {
//line views.html:75
		qw422016.N().S(`
  `)
//line views.html:76
		StreamSignInWall(qw422016, ctx)
//line views.html:76
		qw422016.N().S(`
`)
//line views.html:77
	} else if ctx.PaywallError != nil {
//line views.html:77
		qw422016.N().S(`
  `)
//line views.html:78
		StreamPayWall(qw422016, ctx)
//line views.html:78
		qw422016.N().S(`
`)
//line views.html:79
	} else if ctx.OnboardingMode {
//line views.html:79
		qw422016.N().S(`
  `)
//line views.html:80
		StreamOnboarding(qw422016, ctx)
//line views.html:80
		qw422016.N().S(`
`)
//line views.html:81
	} else if ctx.NotFoundMode {
//line views.html:81
		qw422016.N().S(`
  `)
//line views.html:82
		StreamNotFound(qw422016, ctx)
//line views.html:82
		qw422016.N().S(`
`)
//line views.html:83
	} else if ctx.UnsupportedFileExt != "" {
//line views.html:83
		qw422016.N().S(`
  `)
//line views.html:84
		StreamUnsupportedFile(qw422016, ctx)
//line views.html:84
		qw422016.N().S(`
`)
//line views.html:85
	} else {
//line views.html:85
		qw422016.N().S(`
  `)
//line views.html:86
		StreamNotePage(qw422016, ctx)
//line views.html:86
		qw422016.N().S(`
`)
//line views.html:87
	}
//line views.html:87
	qw422016.N().S(`

`)
//line views.html:89
	for _, url := range ctx.JSURLs {
//line views.html:89
		qw422016.N().S(`
<script src="`)
//line views.html:90
		qw422016.E().S(url)
//line views.html:90
		qw422016.N().S(`" defer></script>
`)
//line views.html:91
	}
//line views.html:91
	qw422016.N().S(`

`)
//line views.html:93
	for _, injection := range ctx.HTMLInjections[injectionPlaceholderBodyEnd] {
//line views.html:93
		qw422016.N().S(`
`)
//line views.html:94
		qw422016.N().S(injection.Content)
//line views.html:94
		qw422016.N().S(`
`)
//line views.html:95
	}
//line views.html:95
	qw422016.N().S(`

</body>
</html>
`)
//line views.html:99
}

//line views.html:99
func WriteRender(qq422016 qtio422016.Writer, ctx *Ctx) {
//line views.html:99
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:99
	StreamRender(qw422016, ctx)
//line views.html:99
	qt422016.ReleaseWriter(qw422016)
//line views.html:99
}

//line views.html:99
func Render(ctx *Ctx) string {
//line views.html:99
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:99
	WriteRender(qb422016, ctx)
//line views.html:99
	qs422016 := string(qb422016.B)
//line views.html:99
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:99
	return qs422016
//line views.html:99
}

//line views.html:101
func StreamNotePage(qw422016 *qt422016.Writer, ctx *Ctx) {
//line views.html:101
	qw422016.N().S(`
`)
//line views.html:103
	headerRef := ctx.HeaderRef()
	footerRef := ctx.FooterRef()
	leftWidgets := ctx.SidebarWidgets("left")
	rightWidgets := ctx.SidebarWidgets("right")
	hasLeft := len(leftWidgets) > 0
	hasRight := len(rightWidgets) > 0
	layoutClass := "layout"
	if !hasLeft && !hasRight {
		layoutClass = "layout layout--no-sidebars"
	} else if !hasLeft {
		layoutClass = "layout layout--no-left"
	} else if !hasRight {
		layoutClass = "layout layout--no-right"
	}

//line views.html:117
	qw422016.N().S(`

`)
//line views.html:119
	var headerNote *templateviews.Note

//line views.html:119
	qw422016.N().S(`
`)
//line views.html:120
	if headerRef.Kind != ContentRefNone {
//line views.html:120
		qw422016.N().S(`
  `)
//line views.html:121
		headerNote = ctx.resolveNoteRef(headerRef)

//line views.html:121
		qw422016.N().S(`
`)
//line views.html:122
	}
//line views.html:122
	qw422016.N().S(`
`)
//line views.html:123
	hasNavLinks := headerNote != nil && headerNote.FirstListHTML() != ""

//line views.html:123
	qw422016.N().S(`

`)
//line views.html:125
	if headerNote != nil {
//line views.html:125
		qw422016.N().S(`
  `)
//line views.html:126
		StreamSiteHeader(qw422016, ctx, headerNote, hasLeft || hasNavLinks, hasRight)
//line views.html:126
		qw422016.N().S(`
`)
//line views.html:127
	}
//line views.html:127
	qw422016.N().S(`

<div class="sidebar-backdrop" id="backdrop"></div>

<div class="`)
//line views.html:131
	qw422016.N().S(layoutClass)
//line views.html:131
	qw422016.N().S(`">
  `)
//line views.html:132
	if hasLeft || hasNavLinks {
//line views.html:132
		qw422016.N().S(`
  `)
//line views.html:133
		StreamNoteSidebar(qw422016, ctx, "left", leftWidgets, headerNote)
//line views.html:133
		qw422016.N().S(`
  `)
//line views.html:134
	}
//line views.html:134
	qw422016.N().S(`

  `)
//line views.html:136
	StreamNoteContent(qw422016, ctx)
//line views.html:136
	qw422016.N().S(`

  `)
//line views.html:138
	if hasRight {
//line views.html:138
		qw422016.N().S(`
  `)
//line views.html:139
		StreamNoteSidebar(qw422016, ctx, "right", rightWidgets, nil)
//line views.html:139
		qw422016.N().S(`
  `)
//line views.html:140
	}
//line views.html:140
	qw422016.N().S(`
</div>

`)
//line views.html:143
	if footerRef.Kind != ContentRefNone {
//line views.html:143
		qw422016.N().S(`
  `)
//line views.html:144
		footerNote := ctx.resolveNoteRef(footerRef)

//line views.html:144
		qw422016.N().S(`
  `)
//line views.html:145
		if footerNote != nil {
//line views.html:145
			qw422016.N().S(`
    `)
//line views.html:146
			StreamSiteFooter(qw422016, ctx, footerNote)
//line views.html:146
			qw422016.N().S(`
  `)
//line views.html:147
		}
//line views.html:147
		qw422016.N().S(`
`)
//line views.html:148
	}
//line views.html:148
	qw422016.N().S(`
`)
//line views.html:149
}

//line views.html:149
func WriteNotePage(qq422016 qtio422016.Writer, ctx *Ctx) {
//line views.html:149
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:149
	StreamNotePage(qw422016, ctx)
//line views.html:149
	qt422016.ReleaseWriter(qw422016)
//line views.html:149
}

//line views.html:149
func NotePage(ctx *Ctx) string {
//line views.html:149
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:149
	WriteNotePage(qb422016, ctx)
//line views.html:149
	qs422016 := string(qb422016.B)
//line views.html:149
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:149
	return qs422016
//line views.html:149
}

//line views.html:151
func StreamNoteSidebar(qw422016 *qt422016.Writer, ctx *Ctx, position string, widgets []WidgetRef, headerNote *templateviews.Note) {
//line views.html:151
	qw422016.N().S(`
<aside class="layout__sidebar layout__sidebar--`)
//line views.html:152
	qw422016.N().S(position)
//line views.html:152
	qw422016.N().S(`">
  `)
//line views.html:153
	if position == "left" && headerNote != nil {
//line views.html:153
		qw422016.N().S(`
  `)
//line views.html:154
		navHTML := headerNote.FirstListHTML()

//line views.html:154
		qw422016.N().S(`
  `)
//line views.html:155
		if navHTML != "" {
//line views.html:155
			qw422016.N().S(`
  <nav class="sidebar-nav">`)
//line views.html:156
			qw422016.N().S(navHTML)
//line views.html:156
			qw422016.N().S(`</nav>
  `)
//line views.html:157
		}
//line views.html:157
		qw422016.N().S(`
  `)
//line views.html:158
	}
//line views.html:158
	qw422016.N().S(`

  `)
//line views.html:160
	for _, w := range widgets {
//line views.html:160
		qw422016.N().S(`
    `)
//line views.html:161
		switch w.Kind {
//line views.html:162
		case WidgetTOC:
//line views.html:162
			qw422016.N().S(`
      `)
//line views.html:163
			StreamTOCWidget(qw422016, ctx)
//line views.html:163
			qw422016.N().S(`
    `)
//line views.html:164
		case WidgetInLinks:
//line views.html:164
			qw422016.N().S(`
      `)
//line views.html:165
			StreamInLinksWidget(qw422016, ctx)
//line views.html:165
			qw422016.N().S(`
    `)
//line views.html:166
		case WidgetOutLinks:
//line views.html:166
			qw422016.N().S(`
      `)
//line views.html:167
			StreamOutLinksWidget(qw422016, ctx)
//line views.html:167
			qw422016.N().S(`
    `)
//line views.html:168
		case WidgetSimilar:
//line views.html:168
			qw422016.N().S(`
      `)
//line views.html:169
			StreamSimilarWidget(qw422016, ctx)
//line views.html:169
			qw422016.N().S(`
    `)
//line views.html:170
		case WidgetContent:
//line views.html:170
			qw422016.N().S(`
      `)
//line views.html:172
			ref := ContentRef{Kind: ContentRefWikiLink, Value: w.Value}
			wNote := ctx.resolveNoteRef(ref)
			if wNote == nil {
				ref = ContentRef{Kind: ContentRefFile, Value: w.Value}
				wNote = ctx.resolveNoteRef(ref)
			}

//line views.html:178
			qw422016.N().S(`
      `)
//line views.html:179
			if wNote != nil {
//line views.html:179
				qw422016.N().S(`
      <div class="widget widget--content">
        <div class="widget__content">`)
//line views.html:181
				qw422016.N().S(wNote.HTMLString())
//line views.html:181
				qw422016.N().S(`</div>
      </div>
      `)
//line views.html:183
			}
//line views.html:183
			qw422016.N().S(`
    `)
//line views.html:184
		}
//line views.html:184
		qw422016.N().S(`
  `)
//line views.html:185
	}
//line views.html:185
	qw422016.N().S(`
</aside>
`)
//line views.html:187
}

//line views.html:187
func WriteNoteSidebar(qq422016 qtio422016.Writer, ctx *Ctx, position string, widgets []WidgetRef, headerNote *templateviews.Note) {
//line views.html:187
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:187
	StreamNoteSidebar(qw422016, ctx, position, widgets, headerNote)
//line views.html:187
	qt422016.ReleaseWriter(qw422016)
//line views.html:187
}

//line views.html:187
func NoteSidebar(ctx *Ctx, position string, widgets []WidgetRef, headerNote *templateviews.Note) string {
//line views.html:187
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:187
	WriteNoteSidebar(qb422016, ctx, position, widgets, headerNote)
//line views.html:187
	qs422016 := string(qb422016.B)
//line views.html:187
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:187
	return qs422016
//line views.html:187
}

//line views.html:189
func StreamTOCWidget(qw422016 *qt422016.Writer, ctx *Ctx) {
//line views.html:189
	qw422016.N().S(`
`)
//line views.html:190
	if ctx.Note != nil {
//line views.html:190
		qw422016.N().S(`
`)
//line views.html:191
		toc := ctx.Note.TOC()

//line views.html:191
		qw422016.N().S(`
`)
//line views.html:192
		if len(toc) > 0 {
//line views.html:192
			qw422016.N().S(`
`)
//line views.html:193
			tocJSON, _ := json.Marshal(toc)

//line views.html:193
			qw422016.N().S(`
<div class="widget widget--toc">
  <h3 class="widget__title">`)
//line views.html:195
			qw422016.E().S(ctx.T("toc_title"))
//line views.html:195
			qw422016.N().S(`</h3>
  <script type="application/json" class="widget__data">`)
//line views.html:196
			qw422016.N().S(string(tocJSON))
//line views.html:196
			qw422016.N().S(`</script>
  <nav class="widget__content widget__toc" id="dt-toc-nav">
    `)
//line views.html:198
			for _, item := range toc {
//line views.html:198
				qw422016.N().S(`
    <div class="toc__item toc__item--level`)
//line views.html:199
				qw422016.N().D(item.Level)
//line views.html:199
				qw422016.N().S(`">
      <a href="#`)
//line views.html:200
				qw422016.N().S(item.ID)
//line views.html:200
				qw422016.N().S(`" class="toc__link">`)
//line views.html:200
				qw422016.N().S(item.Text)
//line views.html:200
				qw422016.N().S(`</a>
    </div>
    `)
//line views.html:202
			}
//line views.html:202
			qw422016.N().S(`
  </nav>
</div>
`)
//line views.html:205
		}
//line views.html:205
		qw422016.N().S(`
`)
//line views.html:206
	}
//line views.html:206
	qw422016.N().S(`
`)
//line views.html:207
}

//line views.html:207
func WriteTOCWidget(qq422016 qtio422016.Writer, ctx *Ctx) {
//line views.html:207
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:207
	StreamTOCWidget(qw422016, ctx)
//line views.html:207
	qt422016.ReleaseWriter(qw422016)
//line views.html:207
}

//line views.html:207
func TOCWidget(ctx *Ctx) string {
//line views.html:207
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:207
	WriteTOCWidget(qb422016, ctx)
//line views.html:207
	qs422016 := string(qb422016.B)
//line views.html:207
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:207
	return qs422016
//line views.html:207
}

//line views.html:209
func StreamInLinksWidget(qw422016 *qt422016.Writer, ctx *Ctx) {
//line views.html:209
	qw422016.N().S(`
`)
//line views.html:210
	if ctx.Note != nil && ctx.Notes != nil {
//line views.html:210
		qw422016.N().S(`
`)
//line views.html:211
		backlinks := ctx.Notes.BackLinks(ctx.Note)

//line views.html:211
		qw422016.N().S(`
`)
//line views.html:212
		if len(backlinks) > 0 {
//line views.html:212
			qw422016.N().S(`
<div class="widget widget--inlinks">
  <h3 class="widget__title">`)
//line views.html:214
			qw422016.E().S(ctx.T("backlinks_title"))
//line views.html:214
			qw422016.N().S(`</h3>
  <ul class="widget__list">
    `)
//line views.html:216
			for _, bl := range backlinks {
//line views.html:216
				qw422016.N().S(`
    <li class="widget__item"><a class="widget__link" href="`)
//line views.html:217
				qw422016.N().S(bl.PermalinkEncoded())
//line views.html:217
				qw422016.N().S(`">`)
//line views.html:217
				qw422016.E().S(bl.Title())
//line views.html:217
				qw422016.N().S(`</a></li>
    `)
//line views.html:218
			}
//line views.html:218
			qw422016.N().S(`
  </ul>
</div>
`)
//line views.html:221
		}
//line views.html:221
		qw422016.N().S(`
`)
//line views.html:222
	}
//line views.html:222
	qw422016.N().S(`
`)
//line views.html:223
}

//line views.html:223
func WriteInLinksWidget(qq422016 qtio422016.Writer, ctx *Ctx) {
//line views.html:223
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:223
	StreamInLinksWidget(qw422016, ctx)
//line views.html:223
	qt422016.ReleaseWriter(qw422016)
//line views.html:223
}

//line views.html:223
func InLinksWidget(ctx *Ctx) string {
//line views.html:223
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:223
	WriteInLinksWidget(qb422016, ctx)
//line views.html:223
	qs422016 := string(qb422016.B)
//line views.html:223
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:223
	return qs422016
//line views.html:223
}

//line views.html:225
func StreamOutLinksWidget(qw422016 *qt422016.Writer, ctx *Ctx) {
//line views.html:225
	qw422016.N().S(`
`)
//line views.html:226
	if ctx.Note != nil && ctx.Notes != nil {
//line views.html:226
		qw422016.N().S(`
`)
//line views.html:227
		outlinks := ctx.Notes.OutLinks(ctx.Note)

//line views.html:227
		qw422016.N().S(`
`)
//line views.html:228
		if len(outlinks) > 0 {
//line views.html:228
			qw422016.N().S(`
<div class="widget widget--outlinks">
  <h3 class="widget__title">`)
//line views.html:230
			qw422016.E().S(ctx.T("outlinks_title"))
//line views.html:230
			qw422016.N().S(`</h3>
  <ul class="widget__list">
    `)
//line views.html:232
			for _, ol := range outlinks {
//line views.html:232
				qw422016.N().S(`
    <li class="widget__item"><a class="widget__link" href="`)
//line views.html:233
				qw422016.N().S(ol.PermalinkEncoded())
//line views.html:233
				qw422016.N().S(`">`)
//line views.html:233
				qw422016.E().S(ol.Title())
//line views.html:233
				qw422016.N().S(`</a></li>
    `)
//line views.html:234
			}
//line views.html:234
			qw422016.N().S(`
  </ul>
</div>
`)
//line views.html:237
		}
//line views.html:237
		qw422016.N().S(`
`)
//line views.html:238
	}
//line views.html:238
	qw422016.N().S(`
`)
//line views.html:239
}

//line views.html:239
func WriteOutLinksWidget(qq422016 qtio422016.Writer, ctx *Ctx) {
//line views.html:239
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:239
	StreamOutLinksWidget(qw422016, ctx)
//line views.html:239
	qt422016.ReleaseWriter(qw422016)
//line views.html:239
}

//line views.html:239
func OutLinksWidget(ctx *Ctx) string {
//line views.html:239
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:239
	WriteOutLinksWidget(qb422016, ctx)
//line views.html:239
	qs422016 := string(qb422016.B)
//line views.html:239
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:239
	return qs422016
//line views.html:239
}

//line views.html:241
func StreamSimilarWidget(qw422016 *qt422016.Writer, ctx *Ctx) {
//line views.html:241
	qw422016.N().S(`
`)
//line views.html:242
	if len(ctx.SimilarNotes) > 0 {
//line views.html:242
		qw422016.N().S(`
<div class="widget widget--similar">
  <h3 class="widget__title">`)
//line views.html:244
		qw422016.E().S(ctx.T("similar_title"))
//line views.html:244
		qw422016.N().S(`</h3>
  <ul class="widget__list">
    `)
//line views.html:246
		for _, note := range ctx.SimilarNotes {
//line views.html:246
			qw422016.N().S(`
    <li class="widget__item"><a class="widget__link" href="`)
//line views.html:247
			qw422016.N().S(note.PermalinkEncoded())
//line views.html:247
			qw422016.N().S(`">`)
//line views.html:247
			qw422016.E().S(note.Title)
//line views.html:247
			qw422016.N().S(`</a></li>
    `)
//line views.html:248
		}
//line views.html:248
		qw422016.N().S(`
  </ul>
</div>
`)
//line views.html:251
	}
//line views.html:251
	qw422016.N().S(`
`)
//line views.html:252
}

//line views.html:252
func WriteSimilarWidget(qq422016 qtio422016.Writer, ctx *Ctx) {
//line views.html:252
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:252
	StreamSimilarWidget(qw422016, ctx)
//line views.html:252
	qt422016.ReleaseWriter(qw422016)
//line views.html:252
}

//line views.html:252
func SimilarWidget(ctx *Ctx) string {
//line views.html:252
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:252
	WriteSimilarWidget(qb422016, ctx)
//line views.html:252
	qs422016 := string(qb422016.B)
//line views.html:252
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:252
	return qs422016
//line views.html:252
}

//line views.html:254
func StreamNoteContent(qw422016 *qt422016.Writer, ctx *Ctx) {
//line views.html:254
	qw422016.N().S(`
<main class="layout__main">
  `)
//line views.html:256
	for _, ref := range ctx.ContentRefs() {
//line views.html:256
		qw422016.N().S(`
    `)
//line views.html:257
		switch ref.Kind {
//line views.html:258
		case ContentRefSelfContent:
//line views.html:258
			qw422016.N().S(`
      `)
//line views.html:259
			StreamSelfContent(qw422016, ctx)
//line views.html:259
			qw422016.N().S(`
    `)
//line views.html:260
		case ContentRefMagazine:
//line views.html:260
			qw422016.N().S(`
      `)
//line views.html:261
			StreamMagazine(qw422016, ctx)
//line views.html:261
			qw422016.N().S(`
    `)
//line views.html:262
		case ContentRefWikiLink:
//line views.html:262
			qw422016.N().S(`
      `)
//line views.html:263
			refNote := ctx.resolveNoteRef(ref)

//line views.html:263
			qw422016.N().S(`
      `)
//line views.html:264
			if refNote != nil {
//line views.html:264
				qw422016.N().S(`
      <div class="content__body">`)
//line views.html:265
				qw422016.N().S(refNote.HTMLString())
//line views.html:265
				qw422016.N().S(`</div>
      `)
//line views.html:266
			}
//line views.html:266
			qw422016.N().S(`
    `)
//line views.html:267
		case ContentRefFile:
//line views.html:267
			qw422016.N().S(`
      `)
//line views.html:268
			refNote := ctx.resolveNoteRef(ref)

//line views.html:268
			qw422016.N().S(`
      `)
//line views.html:269
			if refNote != nil {
//line views.html:269
				qw422016.N().S(`
      <div class="content__body">`)
//line views.html:270
				qw422016.N().S(refNote.HTMLString())
//line views.html:270
				qw422016.N().S(`</div>
      `)
//line views.html:271
			}
//line views.html:271
			qw422016.N().S(`
    `)
//line views.html:272
		}
//line views.html:272
		qw422016.N().S(`
  `)
//line views.html:273
	}
//line views.html:273
	qw422016.N().S(`
</main>
`)
//line views.html:275
}

//line views.html:275
func WriteNoteContent(qq422016 qtio422016.Writer, ctx *Ctx) {
//line views.html:275
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:275
	StreamNoteContent(qw422016, ctx)
//line views.html:275
	qt422016.ReleaseWriter(qw422016)
//line views.html:275
}

//line views.html:275
func NoteContent(ctx *Ctx) string {
//line views.html:275
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:275
	WriteNoteContent(qb422016, ctx)
//line views.html:275
	qs422016 := string(qb422016.B)
//line views.html:275
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:275
	return qs422016
//line views.html:275
}

//line views.html:277
func StreamSelfContent(qw422016 *qt422016.Writer, ctx *Ctx) {
//line views.html:277
	qw422016.N().S(`
`)
//line views.html:278
	if ctx.Note != nil {
//line views.html:278
		qw422016.N().S(`
<article class="content">
  `)
//line views.html:280
		if ctx.Note != nil && ctx.Note.HasLangAlternatives() {
//line views.html:280
			qw422016.N().S(`
  <div class="lang-switcher">
    <span class="lang-switcher__label">Read in:</span>
    <details class="lang-switcher__picker">
      <summary class="lang-switcher__current lang-switcher__current--`)
//line views.html:284
			qw422016.N().S(ctx.Note.Lang())
//line views.html:284
			qw422016.N().S(`">`)
//line views.html:284
			qw422016.N().S(ctx.Note.LangName())
//line views.html:284
			qw422016.N().S(`</summary>
      <div class="lang-switcher__dropdown">
        `)
//line views.html:286
			for _, alt := range ctx.Note.LangAlternativesList() {
//line views.html:286
				qw422016.N().S(`
        <a href="`)
//line views.html:287
				qw422016.N().S(alt.PermalinkEncoded())
//line views.html:287
				qw422016.N().S(`" class="lang-switcher__alt lang-switcher__alt--`)
//line views.html:287
				qw422016.N().S(alt.Lang())
//line views.html:287
				qw422016.N().S(`">`)
//line views.html:287
				qw422016.N().S(alt.LangName())
//line views.html:287
				qw422016.N().S(`</a>
        `)
//line views.html:288
			}
//line views.html:288
			qw422016.N().S(`
      </div>
    </details>
  </div>
  `)
//line views.html:292
		}
//line views.html:292
		qw422016.N().S(`
  `)
//line views.html:293
		tgLinks := ctx.AllTelegramLinks()

//line views.html:293
		qw422016.N().S(`
  `)
//line views.html:294
		if len(tgLinks) > 0 {
//line views.html:294
			qw422016.N().S(`
  <div class="tg-buttons">
    `)
//line views.html:296
			for _, link := range tgLinks {
//line views.html:296
				qw422016.N().S(`
    <a href="`)
//line views.html:297
				qw422016.N().S(link.URL)
//line views.html:297
				qw422016.N().S(`" class="tg-button" target="_blank" rel="noopener">
      <span class="tg-button__icon"></span>
      `)
//line views.html:299
				if link.ChatTitle != "" {
//line views.html:299
					qw422016.E().S(ctx.T("tg_read_on"))
//line views.html:299
					qw422016.N().S(` @`)
//line views.html:299
					qw422016.E().S(link.ChatTitle)
//line views.html:299
				} else {
//line views.html:299
					qw422016.E().S(ctx.T("tg_read"))
//line views.html:299
				}
//line views.html:299
				qw422016.N().S(`
    </a>
    `)
//line views.html:301
			}
//line views.html:301
			qw422016.N().S(`
  </div>
  `)
//line views.html:303
		}
//line views.html:303
		qw422016.N().S(`
  `)
//line views.html:304
		if !ctx.Note.HasH1() {
//line views.html:304
			qw422016.N().S(`<h1 class="content__title">`)
//line views.html:304
			qw422016.E().S(ctx.Note.Title())
//line views.html:304
			qw422016.N().S(`</h1>`)
//line views.html:304
		}
//line views.html:304
		qw422016.N().S(`
  <div class="content__body">`)
//line views.html:305
		qw422016.N().S(ctx.Note.HTMLString())
//line views.html:305
		qw422016.N().S(`</div>
`)
//line views.html:306
		if specJSON := ctx.FormSpecJSON(); specJSON != nil {
//line views.html:306
			qw422016.N().S(`
<script id="form-spec" data-nvid="`)
//line views.html:307
			qw422016.N().S(ctx.Note.VersionID())
//line views.html:307
			qw422016.N().S(`" type="application/json">`)
//line views.html:307
			qw422016.N().Z(specJSON)
//line views.html:307
			qw422016.N().S(`</script>
`)
//line views.html:308
		}
//line views.html:308
		qw422016.N().S(`
</article>
`)
//line views.html:310
	}
//line views.html:310
	qw422016.N().S(`
`)
//line views.html:311
}

//line views.html:311
func WriteSelfContent(qq422016 qtio422016.Writer, ctx *Ctx) {
//line views.html:311
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:311
	StreamSelfContent(qw422016, ctx)
//line views.html:311
	qt422016.ReleaseWriter(qw422016)
//line views.html:311
}

//line views.html:311
func SelfContent(ctx *Ctx) string {
//line views.html:311
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:311
	WriteSelfContent(qb422016, ctx)
//line views.html:311
	qs422016 := string(qb422016.B)
//line views.html:311
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:311
	return qs422016
//line views.html:311
}

//line views.html:313
func StreamMagazine(qw422016 *qt422016.Writer, ctx *Ctx) {
//line views.html:313
	qw422016.N().S(`
`)
//line views.html:314
	items := ctx.MagazineItems()

//line views.html:314
	qw422016.N().S(`
`)
//line views.html:315
	if len(items) > 0 {
//line views.html:315
		qw422016.N().S(`
<div class="magazine">
  `)
//line views.html:317
		StreamMagazineCard(qw422016, ctx, items[0], "")
//line views.html:317
		qw422016.N().S(`

  `)
//line views.html:319
		if len(items) > 1 {
//line views.html:319
			qw422016.N().S(`
  `)
//line views.html:321
			gridEnd := len(items)
			if gridEnd > 5 {
				gridEnd = 5
			}

//line views.html:323
			qw422016.N().S(`
  <div class="magazine__grid">
    `)
//line views.html:325
			for _, item := range items[1:gridEnd] {
//line views.html:325
				qw422016.N().S(`
    `)
//line views.html:326
				StreamMagazineCard(qw422016, ctx, item, "magazine-item--grid")
//line views.html:326
				qw422016.N().S(`
    `)
//line views.html:327
			}
//line views.html:327
			qw422016.N().S(`
  </div>
  `)
//line views.html:329
		}
//line views.html:329
		qw422016.N().S(`

  `)
//line views.html:331
		if len(items) > 5 {
//line views.html:331
			qw422016.N().S(`
  <div class="magazine__list">
    `)
//line views.html:333
			for _, item := range items[5:] {
//line views.html:333
				qw422016.N().S(`
    `)
//line views.html:334
				StreamMagazineCard(qw422016, ctx, item, "")
//line views.html:334
				qw422016.N().S(`
    `)
//line views.html:335
			}
//line views.html:335
			qw422016.N().S(`
  </div>
  `)
//line views.html:337
		}
//line views.html:337
		qw422016.N().S(`
</div>
`)
//line views.html:339
	}
//line views.html:339
	qw422016.N().S(`
`)
//line views.html:340
}

//line views.html:340
func WriteMagazine(qq422016 qtio422016.Writer, ctx *Ctx) {
//line views.html:340
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:340
	StreamMagazine(qw422016, ctx)
//line views.html:340
	qt422016.ReleaseWriter(qw422016)
//line views.html:340
}

//line views.html:340
func Magazine(ctx *Ctx) string {
//line views.html:340
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:340
	WriteMagazine(qb422016, ctx)
//line views.html:340
	qs422016 := string(qb422016.B)
//line views.html:340
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:340
	return qs422016
//line views.html:340
}

//line views.html:342
func StreamMagazineCard(qw422016 *qt422016.Writer, ctx *Ctx, item MagazineItem, extraClass string) {
//line views.html:342
	qw422016.N().S(`
`)
//line views.html:344
	itemClass := "magazine-item magazine-item--list"
	if item.Size == MagazineItemFeatured {
		itemClass = "magazine-item magazine-item--featured"
	} else if item.Size == MagazineItemSmall {
		itemClass = "magazine-item magazine-item--small"
	}
	if extraClass != "" {
		itemClass += " " + extraClass
	}

//line views.html:353
	qw422016.N().S(`
<article class="`)
//line views.html:354
	qw422016.N().S(itemClass)
//line views.html:354
	qw422016.N().S(`">
`)
//line views.html:355
	if item.Size == MagazineItemFeatured {
//line views.html:355
		qw422016.N().S(`
  <h2 class="magazine-item__title"><a class="magazine-item__link" href="`)
//line views.html:356
		qw422016.N().S(item.Note.PermalinkEncoded())
//line views.html:356
		qw422016.N().S(`">`)
//line views.html:356
		qw422016.E().S(item.Note.Title())
//line views.html:356
		qw422016.N().S(`</a></h2>
  `)
//line views.html:357
	} else {
//line views.html:357
		qw422016.N().S(`
  <h3 class="magazine-item__title"><a class="magazine-item__link" href="`)
//line views.html:358
		qw422016.N().S(item.Note.PermalinkEncoded())
//line views.html:358
		qw422016.N().S(`">`)
//line views.html:358
		qw422016.E().S(item.Note.Title())
//line views.html:358
		qw422016.N().S(`</a></h3>
  `)
//line views.html:359
	}
//line views.html:359
	qw422016.N().S(`
  `)
//line views.html:360
	pr := item.Note.PartialRenderer()

//line views.html:360
	qw422016.N().S(`
  `)
//line views.html:361
	if pr != nil {
//line views.html:361
		qw422016.N().S(`
  `)
//line views.html:362
		intro := pr.Introduce()

//line views.html:362
		qw422016.N().S(`
  `)
//line views.html:363
		if intro.ContentHTML != "" {
//line views.html:363
			qw422016.N().S(`
  <p class="magazine-item__excerpt">`)
//line views.html:364
			qw422016.N().S(intro.ContentHTML)
//line views.html:364
			qw422016.N().S(`</p>
  `)
//line views.html:365
		}
//line views.html:365
		qw422016.N().S(`
  `)
//line views.html:366
	}
//line views.html:366
	qw422016.N().S(`
  <div class="magazine-item__footer">
    <a class="magazine-item__readmore" href="`)
//line views.html:368
	qw422016.N().S(item.Note.PermalinkEncoded())
//line views.html:368
	qw422016.N().S(`">`)
//line views.html:368
	qw422016.E().S(ctx.T("readmore"))
//line views.html:368
	qw422016.N().S(`</a>
    <time class="magazine-item__date">`)
//line views.html:369
	qw422016.E().S(item.Note.CreatedAt().Format("2006-01-02"))
//line views.html:369
	qw422016.N().S(`</time>
  </div>
</article>
`)
//line views.html:372
}

//line views.html:372
func WriteMagazineCard(qq422016 qtio422016.Writer, ctx *Ctx, item MagazineItem, extraClass string) {
//line views.html:372
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:372
	StreamMagazineCard(qw422016, ctx, item, extraClass)
//line views.html:372
	qt422016.ReleaseWriter(qw422016)
//line views.html:372
}

//line views.html:372
func MagazineCard(ctx *Ctx, item MagazineItem, extraClass string) string {
//line views.html:372
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:372
	WriteMagazineCard(qb422016, ctx, item, extraClass)
//line views.html:372
	qs422016 := string(qb422016.B)
//line views.html:372
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:372
	return qs422016
//line views.html:372
}

//line views.html:374
func StreamSiteHeader(qw422016 *qt422016.Writer, ctx *Ctx, headerNote *templateviews.Note, hasLeft bool, hasRight bool) {
//line views.html:374
	qw422016.N().S(`
<header class="site-header">
  <div class="site-header__content">
    `)
//line views.html:377
	if hasLeft {
//line views.html:377
		qw422016.N().S(`
    <button class="site-header__hamburger site-header__hamburger--left" aria-label="Open menu" id="btn-left">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="12" x2="21" y2="12"/><line x1="3" y1="18" x2="21" y2="18"/></svg>
    </button>
    `)
//line views.html:381
	}
//line views.html:381
	qw422016.N().S(`
    `)
//line views.html:382
	logoURL := headerNote.FirstImageURL()

//line views.html:382
	qw422016.N().S(`
    `)
//line views.html:383
	if logoURL != "" {
//line views.html:383
		qw422016.N().S(`
    <a class="site-header__logo" href="/"><img src="`)
//line views.html:384
		qw422016.N().S(logoURL)
//line views.html:384
		qw422016.N().S(`" alt="Logo"></a>
    `)
//line views.html:385
	}
//line views.html:385
	qw422016.N().S(`
    `)
//line views.html:386
	navHTML := headerNote.FirstListHTML()

//line views.html:386
	qw422016.N().S(`
    `)
//line views.html:387
	if navHTML != "" {
//line views.html:387
		qw422016.N().S(`
    <nav class="site-header__nav">`)
//line views.html:388
		qw422016.N().S(navHTML)
//line views.html:388
		qw422016.N().S(`</nav>
    `)
//line views.html:389
	}
//line views.html:389
	qw422016.N().S(`

    <div class="site-header__space" mol_view_root="$trip2g_user_space"></div>
    `)
//line views.html:392
	if hasRight {
//line views.html:392
		qw422016.N().S(`
    <button class="site-header__hamburger site-header__hamburger--right" aria-label="Open related" id="btn-right">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></svg>
    </button>
    `)
//line views.html:396
	}
//line views.html:396
	qw422016.N().S(`
  </div>
</header>

<div class="search-wrapper">
  <div mol_view_root="$trip2g_user_search"></div>
</div>
`)
//line views.html:403
}

//line views.html:403
func WriteSiteHeader(qq422016 qtio422016.Writer, ctx *Ctx, headerNote *templateviews.Note, hasLeft bool, hasRight bool) {
//line views.html:403
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:403
	StreamSiteHeader(qw422016, ctx, headerNote, hasLeft, hasRight)
//line views.html:403
	qt422016.ReleaseWriter(qw422016)
//line views.html:403
}

//line views.html:403
func SiteHeader(ctx *Ctx, headerNote *templateviews.Note, hasLeft bool, hasRight bool) string {
//line views.html:403
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:403
	WriteSiteHeader(qb422016, ctx, headerNote, hasLeft, hasRight)
//line views.html:403
	qs422016 := string(qb422016.B)
//line views.html:403
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:403
	return qs422016
//line views.html:403
}

//line views.html:405
func StreamSiteFooter(qw422016 *qt422016.Writer, ctx *Ctx, footerNote *templateviews.Note) {
//line views.html:405
	qw422016.N().S(`
<footer class="site-footer">
  <div class="site-footer__content">
    `)
//line views.html:408
	intro := footerNote.PartialRenderer().Introduce()

//line views.html:408
	qw422016.N().S(`
    `)
//line views.html:409
	if intro.ContentHTML != "" {
//line views.html:409
		qw422016.N().S(`
    <div class="site-footer__brand">
      `)
//line views.html:411
		qw422016.N().S(intro.ContentHTML)
//line views.html:411
		qw422016.N().S(`
    </div>
    `)
//line views.html:413
	}
//line views.html:413
	qw422016.N().S(`
    `)
//line views.html:414
	sections := footerNote.PartialRenderer().Sections(3)

//line views.html:414
	qw422016.N().S(`
    `)
//line views.html:415
	if len(sections) > 1 {
//line views.html:415
		qw422016.N().S(`
    <div class="site-footer__links site-footer__links--columns">
      `)
//line views.html:417
		for _, sec := range sections {
//line views.html:417
			qw422016.N().S(`
      <div class="site-footer__column">
        <p class="site-footer__column-title">`)
//line views.html:419
			qw422016.N().S(sec.TitleHTML)
//line views.html:419
			qw422016.N().S(`</p>
        `)
//line views.html:420
			qw422016.N().S(sec.ContentHTML)
//line views.html:420
			qw422016.N().S(`
      </div>
      `)
//line views.html:422
		}
//line views.html:422
		qw422016.N().S(`
    </div>
    `)
//line views.html:424
	} else {
//line views.html:424
		qw422016.N().S(`
    `)
//line views.html:425
		listHTML := footerNote.FirstListHTML()

//line views.html:425
		qw422016.N().S(`
    `)
//line views.html:426
		if listHTML != "" {
//line views.html:426
			qw422016.N().S(`
    <div class="site-footer__links site-footer__links--inline">`)
//line views.html:427
			qw422016.N().S(listHTML)
//line views.html:427
			qw422016.N().S(`</div>
    `)
//line views.html:428
		}
//line views.html:428
		qw422016.N().S(`
    `)
//line views.html:429
	}
//line views.html:429
	qw422016.N().S(`
  </div>
</footer>
`)
//line views.html:432
}

//line views.html:432
func WriteSiteFooter(qq422016 qtio422016.Writer, ctx *Ctx, footerNote *templateviews.Note) {
//line views.html:432
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:432
	StreamSiteFooter(qw422016, ctx, footerNote)
//line views.html:432
	qt422016.ReleaseWriter(qw422016)
//line views.html:432
}

//line views.html:432
func SiteFooter(ctx *Ctx, footerNote *templateviews.Note) string {
//line views.html:432
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:432
	WriteSiteFooter(qb422016, ctx, footerNote)
//line views.html:432
	qs422016 := string(qb422016.B)
//line views.html:432
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:432
	return qs422016
//line views.html:432
}

//line views.html:434
func StreamSignInWall(qw422016 *qt422016.Writer, ctx *Ctx) {
//line views.html:434
	qw422016.N().S(`
<div class="paywall-page">
  <div class="paywall-page__header">
    <a class="paywall-page__home" href="/">`)
//line views.html:437
	qw422016.E().S(ctx.T("signinwall_home"))
//line views.html:437
	qw422016.N().S(`</a>
    <div mol_view_root="$trip2g_user_space"></div>
  </div>

  `)
//line views.html:441
	if ctx.SigninWallError != nil && ctx.SigninWallError.Note != nil {
//line views.html:441
		qw422016.N().S(`
  <h1 class="content__title">`)
//line views.html:442
		qw422016.E().S(ctx.SigninWallError.Note.Title())
//line views.html:442
		qw422016.N().S(`</h1>
  `)
//line views.html:443
		if ctx.SigninWallError.Note.Description() != "" {
//line views.html:443
			qw422016.N().S(`
  <p>`)
//line views.html:444
			qw422016.E().S(ctx.SigninWallError.Note.Description())
//line views.html:444
			qw422016.N().S(`</p>
  `)
//line views.html:445
		}
//line views.html:445
		qw422016.N().S(`
  `)
//line views.html:446
	}
//line views.html:446
	qw422016.N().S(`

  <div id="signinwall" mol_view_root="$trip2g_user_signinwall"></div>
</div>
`)
//line views.html:450
}

//line views.html:450
func WriteSignInWall(qq422016 qtio422016.Writer, ctx *Ctx) {
//line views.html:450
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:450
	StreamSignInWall(qw422016, ctx)
//line views.html:450
	qt422016.ReleaseWriter(qw422016)
//line views.html:450
}

//line views.html:450
func SignInWall(ctx *Ctx) string {
//line views.html:450
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:450
	WriteSignInWall(qb422016, ctx)
//line views.html:450
	qs422016 := string(qb422016.B)
//line views.html:450
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:450
	return qs422016
//line views.html:450
}

//line views.html:452
func StreamPayWall(qw422016 *qt422016.Writer, ctx *Ctx) {
//line views.html:452
	qw422016.N().S(`
<div class="paywall-page">
  <div class="paywall-page__header">
    <a class="paywall-page__home" href="/">`)
//line views.html:455
	qw422016.E().S(ctx.T("paywall_home"))
//line views.html:455
	qw422016.N().S(`</a>
    <div mol_view_root="$trip2g_user_space"></div>
  </div>

  `)
//line views.html:459
	if ctx.Note != nil {
//line views.html:459
		qw422016.N().S(`
  <h1 class="content__title">`)
//line views.html:460
		qw422016.E().S(ctx.Note.Title())
//line views.html:460
		qw422016.N().S(`</h1>

  `)
//line views.html:462
		if ctx.Note.Description() != "" {
//line views.html:462
			qw422016.N().S(`
  <p>`)
//line views.html:463
			qw422016.E().S(ctx.Note.Description())
//line views.html:463
			qw422016.N().S(`</p>
  `)
//line views.html:464
		}
//line views.html:464
		qw422016.N().S(`

  `)
//line views.html:466
		if ctx.PaywallError != nil {
//line views.html:466
			qw422016.N().S(`
  <script>
    window.__trip2g_paywall = {
      page_id: `)
//line views.html:469
			qw422016.N().DL(ctx.Note.PathID())
//line views.html:469
			qw422016.N().S(`,
    }
  </script>
  <div
    id="paywall"
    mol_view_root="$trip2g_user_paywall"
    data-subgraphs="`)
//line views.html:475
			qw422016.E().S(ctx.PaywallError.SubgraphsJSON)
//line views.html:475
			qw422016.N().S(`"
    data-path-id="`)
//line views.html:476
			qw422016.N().DL(ctx.Note.PathID())
//line views.html:476
			qw422016.N().S(`"
  ></div>
  `)
//line views.html:478
		}
//line views.html:478
		qw422016.N().S(`
  `)
//line views.html:479
	}
//line views.html:479
	qw422016.N().S(`
</div>
`)
//line views.html:481
}

//line views.html:481
func WritePayWall(qq422016 qtio422016.Writer, ctx *Ctx) {
//line views.html:481
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:481
	StreamPayWall(qw422016, ctx)
//line views.html:481
	qt422016.ReleaseWriter(qw422016)
//line views.html:481
}

//line views.html:481
func PayWall(ctx *Ctx) string {
//line views.html:481
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:481
	WritePayWall(qb422016, ctx)
//line views.html:481
	qs422016 := string(qb422016.B)
//line views.html:481
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:481
	return qs422016
//line views.html:481
}

//line views.html:483
func StreamNotFound(qw422016 *qt422016.Writer, ctx *Ctx) {
//line views.html:483
	qw422016.N().S(`
`)
//line views.html:485
	headerRef := ctx.HeaderRef()
	footerRef := ctx.FooterRef()

//line views.html:487
	qw422016.N().S(`
`)
//line views.html:488
	var headerNote *templateviews.Note

//line views.html:488
	qw422016.N().S(`
`)
//line views.html:489
	if headerRef.Kind != ContentRefNone {
//line views.html:489
		qw422016.N().S(`
  `)
//line views.html:490
		headerNote = ctx.resolveNoteRef(headerRef)

//line views.html:490
		qw422016.N().S(`
`)
//line views.html:491
	}
//line views.html:491
	qw422016.N().S(`
`)
//line views.html:492
	if headerNote != nil {
//line views.html:492
		qw422016.N().S(`
  `)
//line views.html:493
		StreamSiteHeader(qw422016, ctx, headerNote, false, false)
//line views.html:493
		qw422016.N().S(`
`)
//line views.html:494
	}
//line views.html:494
	qw422016.N().S(`
<div class="layout layout--no-sidebars">
  <main class="notfound">
    <div class="notfound__code">404</div>
    <p class="notfound__message">Page not found</p>
    <a class="notfound__home" href="/">← Home</a>
  </main>
</div>
`)
//line views.html:502
	if footerRef.Kind != ContentRefNone {
//line views.html:502
		qw422016.N().S(`
  `)
//line views.html:503
		footerNote := ctx.resolveNoteRef(footerRef)

//line views.html:503
		qw422016.N().S(`
  `)
//line views.html:504
		if footerNote != nil {
//line views.html:504
			qw422016.N().S(`
    `)
//line views.html:505
			StreamSiteFooter(qw422016, ctx, footerNote)
//line views.html:505
			qw422016.N().S(`
  `)
//line views.html:506
		}
//line views.html:506
		qw422016.N().S(`
`)
//line views.html:507
	}
//line views.html:507
	qw422016.N().S(`
`)
//line views.html:508
}

//line views.html:508
func WriteNotFound(qq422016 qtio422016.Writer, ctx *Ctx) {
//line views.html:508
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:508
	StreamNotFound(qw422016, ctx)
//line views.html:508
	qt422016.ReleaseWriter(qw422016)
//line views.html:508
}

//line views.html:508
func NotFound(ctx *Ctx) string {
//line views.html:508
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:508
	WriteNotFound(qb422016, ctx)
//line views.html:508
	qs422016 := string(qb422016.B)
//line views.html:508
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:508
	return qs422016
//line views.html:508
}

//line views.html:510
func StreamUnsupportedFile(qw422016 *qt422016.Writer, ctx *Ctx) {
//line views.html:510
	qw422016.N().S(`
<main class="layout__main">
  <article class="content">
    <div class="content__body">
      `)
//line views.html:514
	if ctx.UnsupportedFileExt == ".canvas" {
//line views.html:514
		qw422016.N().S(`
      <p>Canvas files are not supported yet.</p>
      `)
//line views.html:516
	} else if ctx.UnsupportedFileExt == ".excalidraw" {
//line views.html:516
		qw422016.N().S(`
      <p>Excalidraw files are not supported yet.</p>
      `)
//line views.html:518
	} else {
//line views.html:518
		qw422016.N().S(`
      <p>Bases are not supported yet.</p>
      `)
//line views.html:520
	}
//line views.html:520
	qw422016.N().S(`
    </div>
  </article>
</main>
`)
//line views.html:524
}

//line views.html:524
func WriteUnsupportedFile(qq422016 qtio422016.Writer, ctx *Ctx) {
//line views.html:524
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:524
	StreamUnsupportedFile(qw422016, ctx)
//line views.html:524
	qt422016.ReleaseWriter(qw422016)
//line views.html:524
}

//line views.html:524
func UnsupportedFile(ctx *Ctx) string {
//line views.html:524
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:524
	WriteUnsupportedFile(qb422016, ctx)
//line views.html:524
	qs422016 := string(qb422016.B)
//line views.html:524
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:524
	return qs422016
//line views.html:524
}

//line views.html:526
func StreamOnboarding(qw422016 *qt422016.Writer, ctx *Ctx) {
//line views.html:526
	qw422016.N().S(`
<div class="onboarding" data-onboarding>
  `)
//line views.html:528
	if ctx.UserToken.IsAdmin() {
//line views.html:528
		qw422016.N().S(`
  <h3>Welcome!</h3>
  <p>
    Download the starter archive and open it in Obsidian.
    An API key will be created and packed into a ZIP archive with a demo vault.
  </p>
  <p>
    Do not share this archive with anyone as it contains a private key.
    The archive contains only a demo vault. If you already have data,
    two-way sync will offer to download current content from the server.
  </p>
  <p>
    <a href="/_system/onboarding-vault" class="onboarding__cta">
      Download archive
    </a>
  </p>
  `)
//line views.html:544
	} else {
//line views.html:544
		qw422016.N().S(`
  <h3>`)
//line views.html:545
		qw422016.E().S(ctx.T("onboarding_title"))
//line views.html:545
		qw422016.N().S(`</h3>
  <p>`)
//line views.html:546
		qw422016.E().S(ctx.T("onboarding_subtitle"))
//line views.html:546
		qw422016.N().S(`</p>
  `)
//line views.html:547
	}
//line views.html:547
	qw422016.N().S(`
  <div mol_view_root="$trip2g_user_space"></div>
</div>
`)
//line views.html:550
}

//line views.html:550
func WriteOnboarding(qq422016 qtio422016.Writer, ctx *Ctx) {
//line views.html:550
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:550
	StreamOnboarding(qw422016, ctx)
//line views.html:550
	qt422016.ReleaseWriter(qw422016)
//line views.html:550
}

//line views.html:550
func Onboarding(ctx *Ctx) string {
//line views.html:550
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:550
	WriteOnboarding(qb422016, ctx)
//line views.html:550
	qs422016 := string(qb422016.B)
//line views.html:550
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:550
	return qs422016
//line views.html:550
}
