// Code generated by qtc from "views.html". DO NOT EDIT.
// See https://github.com/valyala/quicktemplate for details.

//line views.html:1
package defaulttemplate

//line views.html:1
import "encoding/json"

//line views.html:2
import "trip2g/internal/templateviews"

//line views.html:4
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line views.html:4
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line views.html:4
func StreamRender(qw422016 *qt422016.Writer, ctx *Ctx) {
//line views.html:4
	qw422016.N().S(`
<!DOCTYPE html>
<html`)
//line views.html:6
	if ctx.HTMLLang != "" {
//line views.html:6
		qw422016.N().S(` lang="`)
//line views.html:6
		qw422016.N().S(ctx.HTMLLang)
//line views.html:6
		qw422016.N().S(`"`)
//line views.html:6
	}
//line views.html:6
	qw422016.N().S(`>
<head>
<meta charset="UTF-8">
<script>try{var d=localStorage.getItem('$mol_lights')!=='true',r=document.documentElement;r.classList.toggle('dark',d);r.classList.toggle('light',!d);r.setAttribute('data-theme',d?'dark':'light')}catch(e){}</script>
<meta name="viewport" content="width=device-width, height=device-height, initial-scale=1" />
<meta name="mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-capable" content="yes">

`)
//line views.html:14
	for _, hl := range ctx.HrefLangs {
//line views.html:14
		qw422016.N().S(`<link rel="alternate" hreflang="`)
//line views.html:15
		qw422016.N().S(hl.Lang)
//line views.html:15
		qw422016.N().S(`" href="`)
//line views.html:15
		qw422016.N().S(hl.Href)
//line views.html:15
		qw422016.N().S(`">
`)
//line views.html:16
	}
//line views.html:17
	if ctx.EnableRSS && ctx.Note != nil {
//line views.html:17
		qw422016.N().S(`
<link rel="alternate" type="application/rss+xml" href="`)
//line views.html:18
		qw422016.N().S(ctx.Note.PermalinkEncoded())
//line views.html:18
		qw422016.N().S(`.rss.xml">
`)
//line views.html:19
	}
//line views.html:19
	qw422016.N().S(`

<link rel="icon" type="image/png" href="/assets/favicon-96x96.png" sizes="96x96" />
<link rel="icon" type="image/svg+xml" href="/assets/favicon.svg" />
<link rel="shortcut icon" href="/assets/favicon.ico" />
<link rel="apple-touch-icon" sizes="180x180" href="/assets/apple-touch-icon.png" />
<link rel="manifest" href="/assets/site.webmanifest" />

`)
//line views.html:27
	if ctx.MetaDescription != nil {
//line views.html:27
		qw422016.N().S(`
<meta name="description" content="`)
//line views.html:28
		qw422016.N().S(*ctx.MetaDescription)
//line views.html:28
		qw422016.N().S(`">
`)
//line views.html:29
	}
//line views.html:29
	qw422016.N().S(`

`)
//line views.html:31
	if len(ctx.MetaRobots) > 0 {
//line views.html:31
		qw422016.N().S(`
<meta name="robots" content="`)
//line views.html:32
		qw422016.N().S(ctx.MetaRobots)
//line views.html:32
		qw422016.N().S(`">
`)
//line views.html:33
	}
//line views.html:33
	qw422016.N().S(`

`)
//line views.html:35
	canonical := ""

//line views.html:35
	qw422016.N().S(`
`)
//line views.html:36
	if ctx.OGTags != nil {
//line views.html:36
		canonical = ctx.OGTags["og:url"]

//line views.html:36
	}
//line views.html:36
	qw422016.N().S(`
`)
//line views.html:37
	if canonical != "" {
//line views.html:37
		qw422016.N().S(`
<link rel="canonical" href="`)
//line views.html:38
		qw422016.N().S(canonical)
//line views.html:38
		qw422016.N().S(`">
`)
//line views.html:39
	}
//line views.html:39
	qw422016.N().S(`

<meta property="og:title" content="`)
//line views.html:41
	qw422016.E().S(ctx.Title)
//line views.html:41
	qw422016.N().S(`">
`)
//line views.html:42
	if ctx.MetaDescription != nil {
//line views.html:42
		qw422016.N().S(`
<meta property="og:description" content="`)
//line views.html:43
		qw422016.N().S(*ctx.MetaDescription)
//line views.html:43
		qw422016.N().S(`">
`)
//line views.html:44
	}
//line views.html:44
	qw422016.N().S(`

`)
//line views.html:46
	if ctx.OGTags != nil {
//line views.html:46
		qw422016.N().S(`
`)
//line views.html:47
		for property, value := range ctx.OGTags {
//line views.html:47
			qw422016.N().S(`
<meta property="`)
//line views.html:48
			qw422016.N().S(property)
//line views.html:48
			qw422016.N().S(`" content="`)
//line views.html:48
			qw422016.N().S(value)
//line views.html:48
			qw422016.N().S(`">
`)
//line views.html:49
		}
//line views.html:49
		qw422016.N().S(`
`)
//line views.html:50
	}
//line views.html:50
	qw422016.N().S(`

<script>
window.__trip2g_settings = {
  is_dev_mode: `)
//line views.html:54
	qw422016.N().S(ctx.DevMode)
//line views.html:54
	qw422016.N().S(`,
  title: `)
//line views.html:55
	qw422016.N().Q(ctx.Title)
//line views.html:55
	qw422016.N().S(`,
  ui_lang: `)
//line views.html:56
	qw422016.N().Q(ctx.UILang)
//line views.html:56
	qw422016.N().S(`,
  js_urls: [`)
//line views.html:57
	for _, u := range ctx.JSURLs {
//line views.html:57
		qw422016.N().Q(u)
//line views.html:57
		qw422016.N().S(`,`)
//line views.html:57
	}
//line views.html:57
	qw422016.N().S(`],
`)
//line views.html:58
	if ctx.Note != nil {
//line views.html:58
		qw422016.N().S(`  note_lang: `)
//line views.html:58
		qw422016.N().Q(ctx.Note.Lang())
//line views.html:58
		qw422016.N().S(`,
  note_path: `)
//line views.html:59
		qw422016.N().Q(ctx.Note.Path())
//line views.html:59
		qw422016.N().S(`,
  note_path_id: `)
//line views.html:60
		qw422016.N().DL(ctx.Note.PathID())
//line views.html:60
		qw422016.N().S(`,
  note_version_id: `)
//line views.html:61
		qw422016.N().Q(ctx.Note.VersionID())
//line views.html:61
		qw422016.N().S(`,
`)
//line views.html:62
	}
//line views.html:62
	qw422016.N().S(`}
</script>

<title>`)
//line views.html:65
	qw422016.E().S(ctx.Title)
//line views.html:65
	qw422016.N().S(`</title>

`)
//line views.html:67
	if ctx.InlineCSS != "" {
//line views.html:67
		qw422016.N().S(`
<style>`)
//line views.html:68
		qw422016.N().S(ctx.InlineCSS)
//line views.html:68
		qw422016.N().S(`</style>
`)
//line views.html:69
	}
//line views.html:69
	qw422016.N().S(`
`)
//line views.html:70
	for _, url := range ctx.CSSURLs {
//line views.html:70
		qw422016.N().S(`
<link href="`)
//line views.html:71
		qw422016.E().S(url)
//line views.html:71
		qw422016.N().S(`" rel="stylesheet">
`)
//line views.html:72
	}
//line views.html:72
	qw422016.N().S(`

`)
//line views.html:74
	for _, injection := range ctx.HTMLInjections[injectionPlaceholderHead] {
//line views.html:74
		qw422016.N().S(`
`)
//line views.html:75
		qw422016.N().S(injection.Content)
//line views.html:75
		qw422016.N().S(`
`)
//line views.html:76
	}
//line views.html:76
	qw422016.N().S(`

</head>
<body tabindex="-1">

`)
//line views.html:81
	if ctx.SigninWallError != nil {
//line views.html:81
		qw422016.N().S(`
  `)
//line views.html:82
		StreamSignInWall(qw422016, ctx)
//line views.html:82
		qw422016.N().S(`
`)
//line views.html:83
	} else if ctx.PaywallError != nil {
//line views.html:83
		qw422016.N().S(`
  `)
//line views.html:84
		StreamPayWall(qw422016, ctx)
//line views.html:84
		qw422016.N().S(`
`)
//line views.html:85
	} else if ctx.OnboardingMode {
//line views.html:85
		qw422016.N().S(`
  `)
//line views.html:86
		StreamOnboarding(qw422016, ctx)
//line views.html:86
		qw422016.N().S(`
`)
//line views.html:87
	} else if ctx.NotFoundMode {
//line views.html:87
		qw422016.N().S(`
  `)
//line views.html:88
		StreamNotFound(qw422016, ctx)
//line views.html:88
		qw422016.N().S(`
`)
//line views.html:89
	} else if ctx.UnsupportedFileExt != "" {
//line views.html:89
		qw422016.N().S(`
  `)
//line views.html:90
		StreamUnsupportedFile(qw422016, ctx)
//line views.html:90
		qw422016.N().S(`
`)
//line views.html:91
	} else {
//line views.html:91
		qw422016.N().S(`
  `)
//line views.html:92
		StreamNotePage(qw422016, ctx)
//line views.html:92
		qw422016.N().S(`
`)
//line views.html:93
	}
//line views.html:93
	qw422016.N().S(`

`)
//line views.html:95
	for _, url := range ctx.JSURLs {
//line views.html:95
		qw422016.N().S(`
<script src="`)
//line views.html:96
		qw422016.E().S(url)
//line views.html:96
		qw422016.N().S(`" defer></script>
`)
//line views.html:97
	}
//line views.html:97
	qw422016.N().S(`

`)
//line views.html:99
	for _, injection := range ctx.HTMLInjections[injectionPlaceholderBodyEnd] {
//line views.html:99
		qw422016.N().S(`
`)
//line views.html:100
		qw422016.N().S(injection.Content)
//line views.html:100
		qw422016.N().S(`
`)
//line views.html:101
	}
//line views.html:101
	qw422016.N().S(`

</body>
</html>
`)
//line views.html:105
}

//line views.html:105
func WriteRender(qq422016 qtio422016.Writer, ctx *Ctx) {
//line views.html:105
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:105
	StreamRender(qw422016, ctx)
//line views.html:105
	qt422016.ReleaseWriter(qw422016)
//line views.html:105
}

//line views.html:105
func Render(ctx *Ctx) string {
//line views.html:105
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:105
	WriteRender(qb422016, ctx)
//line views.html:105
	qs422016 := string(qb422016.B)
//line views.html:105
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:105
	return qs422016
//line views.html:105
}

//line views.html:107
func StreamNotePage(qw422016 *qt422016.Writer, ctx *Ctx) {
//line views.html:107
	qw422016.N().S(`
`)
//line views.html:109
	headerRef := ctx.HeaderRef()
	footerRef := ctx.FooterRef()
	leftWidgets := ctx.SidebarWidgets("left")
	rightWidgets := ctx.SidebarWidgets("right")
	hasLeft := len(leftWidgets) > 0
	hasRight := len(rightWidgets) > 0
	layoutClass := "layout"
	if !hasLeft && !hasRight {
		layoutClass = "layout layout--no-sidebars"
	} else if !hasLeft {
		layoutClass = "layout layout--no-left"
	} else if !hasRight {
		layoutClass = "layout layout--no-right"
	}

//line views.html:123
	qw422016.N().S(`

`)
//line views.html:125
	var headerNote *templateviews.Note

//line views.html:125
	qw422016.N().S(`
`)
//line views.html:126
	if headerRef.Kind != ContentRefNone {
//line views.html:126
		qw422016.N().S(`
  `)
//line views.html:127
		headerNote = ctx.resolveNoteRef(headerRef)

//line views.html:127
		qw422016.N().S(`
`)
//line views.html:128
	}
//line views.html:128
	qw422016.N().S(`
`)
//line views.html:129
	hasNavLinks := headerNote != nil && headerNote.FirstListHTML() != ""

//line views.html:129
	qw422016.N().S(`

`)
//line views.html:131
	if headerNote != nil {
//line views.html:131
		qw422016.N().S(`
  `)
//line views.html:132
		StreamSiteHeader(qw422016, ctx, headerNote, hasLeft || hasNavLinks, hasRight)
//line views.html:132
		qw422016.N().S(`
`)
//line views.html:133
	}
//line views.html:133
	qw422016.N().S(`

<div class="sidebar-backdrop" id="backdrop"></div>

<div class="`)
//line views.html:137
	qw422016.N().S(layoutClass)
//line views.html:137
	qw422016.N().S(`">
  `)
//line views.html:138
	if hasLeft || hasNavLinks {
//line views.html:138
		qw422016.N().S(`
  `)
//line views.html:139
		StreamNoteSidebar(qw422016, ctx, "left", leftWidgets, headerNote)
//line views.html:139
		qw422016.N().S(`
  `)
//line views.html:140
	}
//line views.html:140
	qw422016.N().S(`

  `)
//line views.html:142
	StreamNoteContent(qw422016, ctx)
//line views.html:142
	qw422016.N().S(`

  `)
//line views.html:144
	if hasRight {
//line views.html:144
		qw422016.N().S(`
  `)
//line views.html:145
		StreamNoteSidebar(qw422016, ctx, "right", rightWidgets, nil)
//line views.html:145
		qw422016.N().S(`
  `)
//line views.html:146
	}
//line views.html:146
	qw422016.N().S(`
</div>

`)
//line views.html:149
	if footerRef.Kind != ContentRefNone {
//line views.html:149
		qw422016.N().S(`
  `)
//line views.html:150
		footerNote := ctx.resolveNoteRef(footerRef)

//line views.html:150
		qw422016.N().S(`
  `)
//line views.html:151
		if footerNote != nil {
//line views.html:151
			qw422016.N().S(`
    `)
//line views.html:152
			StreamSiteFooter(qw422016, ctx, footerNote)
//line views.html:152
			qw422016.N().S(`
  `)
//line views.html:153
		}
//line views.html:153
		qw422016.N().S(`
`)
//line views.html:154
	}
//line views.html:154
	qw422016.N().S(`
`)
//line views.html:155
}

//line views.html:155
func WriteNotePage(qq422016 qtio422016.Writer, ctx *Ctx) {
//line views.html:155
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:155
	StreamNotePage(qw422016, ctx)
//line views.html:155
	qt422016.ReleaseWriter(qw422016)
//line views.html:155
}

//line views.html:155
func NotePage(ctx *Ctx) string {
//line views.html:155
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:155
	WriteNotePage(qb422016, ctx)
//line views.html:155
	qs422016 := string(qb422016.B)
//line views.html:155
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:155
	return qs422016
//line views.html:155
}

//line views.html:157
func StreamNoteSidebar(qw422016 *qt422016.Writer, ctx *Ctx, position string, widgets []WidgetRef, headerNote *templateviews.Note) {
//line views.html:157
	qw422016.N().S(`
<aside class="layout__sidebar layout__sidebar--`)
//line views.html:158
	qw422016.N().S(position)
//line views.html:158
	qw422016.N().S(`">
  `)
//line views.html:159
	if position == "left" && headerNote != nil {
//line views.html:159
		qw422016.N().S(`
  `)
//line views.html:160
		navHTML := headerNote.FirstListHTML()

//line views.html:160
		qw422016.N().S(`
  `)
//line views.html:161
		if navHTML != "" {
//line views.html:161
			qw422016.N().S(`
  <nav class="sidebar-nav">`)
//line views.html:162
			qw422016.N().S(navHTML)
//line views.html:162
			qw422016.N().S(`</nav>
  `)
//line views.html:163
		}
//line views.html:163
		qw422016.N().S(`
  `)
//line views.html:164
	}
//line views.html:164
	qw422016.N().S(`

  `)
//line views.html:166
	for _, w := range widgets {
//line views.html:166
		qw422016.N().S(`
    `)
//line views.html:167
		switch w.Kind {
//line views.html:168
		case WidgetTOC:
//line views.html:168
			qw422016.N().S(`
      `)
//line views.html:169
			StreamTOCWidget(qw422016, ctx)
//line views.html:169
			qw422016.N().S(`
    `)
//line views.html:170
		case WidgetInLinks:
//line views.html:170
			qw422016.N().S(`
      `)
//line views.html:171
			StreamInLinksWidget(qw422016, ctx)
//line views.html:171
			qw422016.N().S(`
    `)
//line views.html:172
		case WidgetOutLinks:
//line views.html:172
			qw422016.N().S(`
      `)
//line views.html:173
			StreamOutLinksWidget(qw422016, ctx)
//line views.html:173
			qw422016.N().S(`
    `)
//line views.html:174
		case WidgetSimilar:
//line views.html:174
			qw422016.N().S(`
      `)
//line views.html:175
			StreamSimilarWidget(qw422016, ctx)
//line views.html:175
			qw422016.N().S(`
    `)
//line views.html:176
		case WidgetContent:
//line views.html:176
			qw422016.N().S(`
      `)
//line views.html:178
			ref := ContentRef{Kind: ContentRefWikiLink, Value: w.Value}
			wNote := ctx.resolveNoteRef(ref)
			if wNote == nil {
				ref = ContentRef{Kind: ContentRefFile, Value: w.Value}
				wNote = ctx.resolveNoteRef(ref)
			}

//line views.html:184
			qw422016.N().S(`
      `)
//line views.html:185
			if wNote != nil {
//line views.html:185
				qw422016.N().S(`
      <div class="widget widget--content">
        <div class="widget__content">`)
//line views.html:187
				qw422016.N().S(wNote.HTMLString())
//line views.html:187
				qw422016.N().S(`</div>
      </div>
      `)
//line views.html:189
			}
//line views.html:189
			qw422016.N().S(`
    `)
//line views.html:190
		}
//line views.html:190
		qw422016.N().S(`
  `)
//line views.html:191
	}
//line views.html:191
	qw422016.N().S(`
</aside>
`)
//line views.html:193
}

//line views.html:193
func WriteNoteSidebar(qq422016 qtio422016.Writer, ctx *Ctx, position string, widgets []WidgetRef, headerNote *templateviews.Note) {
//line views.html:193
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:193
	StreamNoteSidebar(qw422016, ctx, position, widgets, headerNote)
//line views.html:193
	qt422016.ReleaseWriter(qw422016)
//line views.html:193
}

//line views.html:193
func NoteSidebar(ctx *Ctx, position string, widgets []WidgetRef, headerNote *templateviews.Note) string {
//line views.html:193
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:193
	WriteNoteSidebar(qb422016, ctx, position, widgets, headerNote)
//line views.html:193
	qs422016 := string(qb422016.B)
//line views.html:193
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:193
	return qs422016
//line views.html:193
}

//line views.html:195
func StreamTOCWidget(qw422016 *qt422016.Writer, ctx *Ctx) {
//line views.html:195
	qw422016.N().S(`
`)
//line views.html:196
	if ctx.Note != nil {
//line views.html:196
		qw422016.N().S(`
`)
//line views.html:197
		toc := ctx.Note.TOC()

//line views.html:197
		qw422016.N().S(`
`)
//line views.html:198
		if len(toc) > 0 {
//line views.html:198
			qw422016.N().S(`
`)
//line views.html:199
			tocJSON, _ := json.Marshal(toc)

//line views.html:199
			qw422016.N().S(`
<div class="widget widget--toc">
  <h3 class="widget__title">`)
//line views.html:201
			qw422016.E().S(ctx.T("toc_title"))
//line views.html:201
			qw422016.N().S(`</h3>
  <script type="application/json" class="widget__data">`)
//line views.html:202
			qw422016.N().S(string(tocJSON))
//line views.html:202
			qw422016.N().S(`</script>
  <nav class="widget__content widget__toc" id="dt-toc-nav">
    `)
//line views.html:204
			for _, item := range toc {
//line views.html:204
				qw422016.N().S(`
    <div class="toc__item toc__item--level`)
//line views.html:205
				qw422016.N().D(item.Level)
//line views.html:205
				qw422016.N().S(`">
      <a href="#`)
//line views.html:206
				qw422016.N().S(item.ID)
//line views.html:206
				qw422016.N().S(`" class="toc__link">`)
//line views.html:206
				qw422016.N().S(item.Text)
//line views.html:206
				qw422016.N().S(`</a>
    </div>
    `)
//line views.html:208
			}
//line views.html:208
			qw422016.N().S(`
  </nav>
</div>
`)
//line views.html:211
		}
//line views.html:211
		qw422016.N().S(`
`)
//line views.html:212
	}
//line views.html:212
	qw422016.N().S(`
`)
//line views.html:213
}

//line views.html:213
func WriteTOCWidget(qq422016 qtio422016.Writer, ctx *Ctx) {
//line views.html:213
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:213
	StreamTOCWidget(qw422016, ctx)
//line views.html:213
	qt422016.ReleaseWriter(qw422016)
//line views.html:213
}

//line views.html:213
func TOCWidget(ctx *Ctx) string {
//line views.html:213
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:213
	WriteTOCWidget(qb422016, ctx)
//line views.html:213
	qs422016 := string(qb422016.B)
//line views.html:213
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:213
	return qs422016
//line views.html:213
}

//line views.html:215
func StreamInLinksWidget(qw422016 *qt422016.Writer, ctx *Ctx) {
//line views.html:215
	qw422016.N().S(`
`)
//line views.html:216
	if ctx.Note != nil && ctx.Notes != nil {
//line views.html:216
		qw422016.N().S(`
`)
//line views.html:217
		backlinks := ctx.Notes.BackLinks(ctx.Note)

//line views.html:217
		qw422016.N().S(`
`)
//line views.html:218
		if len(backlinks) > 0 {
//line views.html:218
			qw422016.N().S(`
<div class="widget widget--inlinks">
  <h3 class="widget__title">`)
//line views.html:220
			qw422016.E().S(ctx.T("backlinks_title"))
//line views.html:220
			qw422016.N().S(`</h3>
  <ul class="widget__list">
    `)
//line views.html:222
			for _, bl := range backlinks {
//line views.html:222
				qw422016.N().S(`
    <li class="widget__item"><a class="widget__link" href="`)
//line views.html:223
				qw422016.N().S(bl.PermalinkEncoded())
//line views.html:223
				qw422016.N().S(`">`)
//line views.html:223
				qw422016.E().S(bl.Title())
//line views.html:223
				qw422016.N().S(`</a></li>
    `)
//line views.html:224
			}
//line views.html:224
			qw422016.N().S(`
  </ul>
</div>
`)
//line views.html:227
		}
//line views.html:227
		qw422016.N().S(`
`)
//line views.html:228
	}
//line views.html:228
	qw422016.N().S(`
`)
//line views.html:229
}

//line views.html:229
func WriteInLinksWidget(qq422016 qtio422016.Writer, ctx *Ctx) {
//line views.html:229
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:229
	StreamInLinksWidget(qw422016, ctx)
//line views.html:229
	qt422016.ReleaseWriter(qw422016)
//line views.html:229
}

//line views.html:229
func InLinksWidget(ctx *Ctx) string {
//line views.html:229
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:229
	WriteInLinksWidget(qb422016, ctx)
//line views.html:229
	qs422016 := string(qb422016.B)
//line views.html:229
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:229
	return qs422016
//line views.html:229
}

//line views.html:231
func StreamOutLinksWidget(qw422016 *qt422016.Writer, ctx *Ctx) {
//line views.html:231
	qw422016.N().S(`
`)
//line views.html:232
	if ctx.Note != nil && ctx.Notes != nil {
//line views.html:232
		qw422016.N().S(`
`)
//line views.html:233
		outlinks := ctx.Notes.OutLinks(ctx.Note)

//line views.html:233
		qw422016.N().S(`
`)
//line views.html:234
		if len(outlinks) > 0 {
//line views.html:234
			qw422016.N().S(`
<div class="widget widget--outlinks">
  <h3 class="widget__title">`)
//line views.html:236
			qw422016.E().S(ctx.T("outlinks_title"))
//line views.html:236
			qw422016.N().S(`</h3>
  <ul class="widget__list">
    `)
//line views.html:238
			for _, ol := range outlinks {
//line views.html:238
				qw422016.N().S(`
    <li class="widget__item"><a class="widget__link" href="`)
//line views.html:239
				qw422016.N().S(ol.PermalinkEncoded())
//line views.html:239
				qw422016.N().S(`">`)
//line views.html:239
				qw422016.E().S(ol.Title())
//line views.html:239
				qw422016.N().S(`</a></li>
    `)
//line views.html:240
			}
//line views.html:240
			qw422016.N().S(`
  </ul>
</div>
`)
//line views.html:243
		}
//line views.html:243
		qw422016.N().S(`
`)
//line views.html:244
	}
//line views.html:244
	qw422016.N().S(`
`)
//line views.html:245
}

//line views.html:245
func WriteOutLinksWidget(qq422016 qtio422016.Writer, ctx *Ctx) {
//line views.html:245
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:245
	StreamOutLinksWidget(qw422016, ctx)
//line views.html:245
	qt422016.ReleaseWriter(qw422016)
//line views.html:245
}

//line views.html:245
func OutLinksWidget(ctx *Ctx) string {
//line views.html:245
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:245
	WriteOutLinksWidget(qb422016, ctx)
//line views.html:245
	qs422016 := string(qb422016.B)
//line views.html:245
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:245
	return qs422016
//line views.html:245
}

//line views.html:247
func StreamSimilarWidget(qw422016 *qt422016.Writer, ctx *Ctx) {
//line views.html:247
	qw422016.N().S(`
`)
//line views.html:248
	if len(ctx.SimilarNotes) > 0 {
//line views.html:248
		qw422016.N().S(`
<div class="widget widget--similar">
  <h3 class="widget__title">`)
//line views.html:250
		qw422016.E().S(ctx.T("similar_title"))
//line views.html:250
		qw422016.N().S(`</h3>
  <ul class="widget__list">
    `)
//line views.html:252
		for _, note := range ctx.SimilarNotes {
//line views.html:252
			qw422016.N().S(`
    <li class="widget__item"><a class="widget__link" href="`)
//line views.html:253
			qw422016.N().S(note.PermalinkEncoded())
//line views.html:253
			qw422016.N().S(`">`)
//line views.html:253
			qw422016.E().S(note.Title)
//line views.html:253
			qw422016.N().S(`</a></li>
    `)
//line views.html:254
		}
//line views.html:254
		qw422016.N().S(`
  </ul>
</div>
`)
//line views.html:257
	}
//line views.html:257
	qw422016.N().S(`
`)
//line views.html:258
}

//line views.html:258
func WriteSimilarWidget(qq422016 qtio422016.Writer, ctx *Ctx) {
//line views.html:258
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:258
	StreamSimilarWidget(qw422016, ctx)
//line views.html:258
	qt422016.ReleaseWriter(qw422016)
//line views.html:258
}

//line views.html:258
func SimilarWidget(ctx *Ctx) string {
//line views.html:258
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:258
	WriteSimilarWidget(qb422016, ctx)
//line views.html:258
	qs422016 := string(qb422016.B)
//line views.html:258
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:258
	return qs422016
//line views.html:258
}

//line views.html:260
func StreamNoteContent(qw422016 *qt422016.Writer, ctx *Ctx) {
//line views.html:260
	qw422016.N().S(`
<main class="layout__main">
  `)
//line views.html:262
	for _, ref := range ctx.ContentRefs() {
//line views.html:262
		qw422016.N().S(`
    `)
//line views.html:263
		switch ref.Kind {
//line views.html:264
		case ContentRefSelfContent:
//line views.html:264
			qw422016.N().S(`
      `)
//line views.html:265
			StreamSelfContent(qw422016, ctx)
//line views.html:265
			qw422016.N().S(`
    `)
//line views.html:266
		case ContentRefMagazine:
//line views.html:266
			qw422016.N().S(`
      `)
//line views.html:267
			StreamMagazine(qw422016, ctx)
//line views.html:267
			qw422016.N().S(`
    `)
//line views.html:268
		case ContentRefWikiLink:
//line views.html:268
			qw422016.N().S(`
      `)
//line views.html:269
			refNote := ctx.resolveNoteRef(ref)

//line views.html:269
			qw422016.N().S(`
      `)
//line views.html:270
			if refNote != nil {
//line views.html:270
				qw422016.N().S(`
      <div class="content__body">`)
//line views.html:271
				qw422016.N().S(refNote.HTMLString())
//line views.html:271
				qw422016.N().S(`</div>
      `)
//line views.html:272
			}
//line views.html:272
			qw422016.N().S(`
    `)
//line views.html:273
		case ContentRefFile:
//line views.html:273
			qw422016.N().S(`
      `)
//line views.html:274
			refNote := ctx.resolveNoteRef(ref)

//line views.html:274
			qw422016.N().S(`
      `)
//line views.html:275
			if refNote != nil {
//line views.html:275
				qw422016.N().S(`
      <div class="content__body">`)
//line views.html:276
				qw422016.N().S(refNote.HTMLString())
//line views.html:276
				qw422016.N().S(`</div>
      `)
//line views.html:277
			}
//line views.html:277
			qw422016.N().S(`
    `)
//line views.html:278
		}
//line views.html:278
		qw422016.N().S(`
  `)
//line views.html:279
	}
//line views.html:279
	qw422016.N().S(`
</main>
`)
//line views.html:281
}

//line views.html:281
func WriteNoteContent(qq422016 qtio422016.Writer, ctx *Ctx) {
//line views.html:281
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:281
	StreamNoteContent(qw422016, ctx)
//line views.html:281
	qt422016.ReleaseWriter(qw422016)
//line views.html:281
}

//line views.html:281
func NoteContent(ctx *Ctx) string {
//line views.html:281
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:281
	WriteNoteContent(qb422016, ctx)
//line views.html:281
	qs422016 := string(qb422016.B)
//line views.html:281
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:281
	return qs422016
//line views.html:281
}

//line views.html:283
func StreamSelfContent(qw422016 *qt422016.Writer, ctx *Ctx) {
//line views.html:283
	qw422016.N().S(`
`)
//line views.html:284
	if ctx.Note != nil {
//line views.html:284
		qw422016.N().S(`
<article class="content">
  `)
//line views.html:286
		if ctx.Note != nil && ctx.Note.HasLangAlternatives() {
//line views.html:286
			qw422016.N().S(`
  <div class="lang-switcher">
    <span class="lang-switcher__label">Read in:</span>
    <details class="lang-switcher__picker">
      <summary class="lang-switcher__current lang-switcher__current--`)
//line views.html:290
			qw422016.N().S(ctx.Note.Lang())
//line views.html:290
			qw422016.N().S(`">`)
//line views.html:290
			qw422016.N().S(ctx.Note.LangName())
//line views.html:290
			qw422016.N().S(`</summary>
      <div class="lang-switcher__dropdown">
        `)
//line views.html:292
			for _, alt := range ctx.Note.LangAlternativesList() {
//line views.html:292
				qw422016.N().S(`
        <a href="`)
//line views.html:293
				qw422016.N().S(alt.PermalinkEncoded())
//line views.html:293
				qw422016.N().S(`" class="lang-switcher__alt lang-switcher__alt--`)
//line views.html:293
				qw422016.N().S(alt.Lang())
//line views.html:293
				qw422016.N().S(`">`)
//line views.html:293
				qw422016.N().S(alt.LangName())
//line views.html:293
				qw422016.N().S(`</a>
        `)
//line views.html:294
			}
//line views.html:294
			qw422016.N().S(`
      </div>
    </details>
  </div>
  `)
//line views.html:298
		}
//line views.html:298
		qw422016.N().S(`
  `)
//line views.html:299
		tgLinks := ctx.AllTelegramLinks()

//line views.html:299
		qw422016.N().S(`
  `)
//line views.html:300
		if len(tgLinks) > 0 {
//line views.html:300
			qw422016.N().S(`
  <div class="tg-buttons">
    `)
//line views.html:302
			for _, link := range tgLinks {
//line views.html:302
				qw422016.N().S(`
    <a href="`)
//line views.html:303
				qw422016.N().S(link.URL)
//line views.html:303
				qw422016.N().S(`" class="tg-button" target="_blank" rel="noopener">
      <span class="tg-button__icon"></span>
      `)
//line views.html:305
				if link.ChatTitle != "" {
//line views.html:305
					qw422016.E().S(ctx.T("tg_read_on"))
//line views.html:305
					qw422016.N().S(` @`)
//line views.html:305
					qw422016.E().S(link.ChatTitle)
//line views.html:305
				} else {
//line views.html:305
					qw422016.E().S(ctx.T("tg_read"))
//line views.html:305
				}
//line views.html:305
				qw422016.N().S(`
    </a>
    `)
//line views.html:307
			}
//line views.html:307
			qw422016.N().S(`
  </div>
  `)
//line views.html:309
		}
//line views.html:309
		qw422016.N().S(`
  `)
//line views.html:310
		if !ctx.Note.HasH1() {
//line views.html:310
			qw422016.N().S(`<h1 class="content__title">`)
//line views.html:310
			qw422016.E().S(ctx.Note.Title())
//line views.html:310
			qw422016.N().S(`</h1>`)
//line views.html:310
		}
//line views.html:310
		qw422016.N().S(`
  <div class="content__body">`)
//line views.html:311
		qw422016.N().S(ctx.Note.HTMLString())
//line views.html:311
		qw422016.N().S(`</div>
`)
//line views.html:312
		if specJSON := ctx.FormSpecJSON(); specJSON != nil {
//line views.html:312
			qw422016.N().S(`
<script id="form-spec" data-nvid="`)
//line views.html:313
			qw422016.N().S(ctx.Note.VersionID())
//line views.html:313
			qw422016.N().S(`" type="application/json">`)
//line views.html:313
			qw422016.N().Z(specJSON)
//line views.html:313
			qw422016.N().S(`</script>
`)
//line views.html:314
		}
//line views.html:314
		qw422016.N().S(`
</article>
`)
//line views.html:316
	}
//line views.html:316
	qw422016.N().S(`
`)
//line views.html:317
}

//line views.html:317
func WriteSelfContent(qq422016 qtio422016.Writer, ctx *Ctx) {
//line views.html:317
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:317
	StreamSelfContent(qw422016, ctx)
//line views.html:317
	qt422016.ReleaseWriter(qw422016)
//line views.html:317
}

//line views.html:317
func SelfContent(ctx *Ctx) string {
//line views.html:317
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:317
	WriteSelfContent(qb422016, ctx)
//line views.html:317
	qs422016 := string(qb422016.B)
//line views.html:317
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:317
	return qs422016
//line views.html:317
}

//line views.html:319
func StreamMagazine(qw422016 *qt422016.Writer, ctx *Ctx) {
//line views.html:319
	qw422016.N().S(`
`)
//line views.html:320
	items := ctx.MagazineItems()

//line views.html:320
	qw422016.N().S(`
`)
//line views.html:321
	if len(items) > 0 {
//line views.html:321
		qw422016.N().S(`
<div class="magazine">
  `)
//line views.html:323
		StreamMagazineCard(qw422016, ctx, items[0], "")
//line views.html:323
		qw422016.N().S(`

  `)
//line views.html:325
		if len(items) > 1 {
//line views.html:325
			qw422016.N().S(`
  `)
//line views.html:327
			gridEnd := len(items)
			if gridEnd > 5 {
				gridEnd = 5
			}

//line views.html:329
			qw422016.N().S(`
  <div class="magazine__grid">
    `)
//line views.html:331
			for _, item := range items[1:gridEnd] {
//line views.html:331
				qw422016.N().S(`
    `)
//line views.html:332
				StreamMagazineCard(qw422016, ctx, item, "magazine-item--grid")
//line views.html:332
				qw422016.N().S(`
    `)
//line views.html:333
			}
//line views.html:333
			qw422016.N().S(`
  </div>
  `)
//line views.html:335
		}
//line views.html:335
		qw422016.N().S(`

  `)
//line views.html:337
		if len(items) > 5 {
//line views.html:337
			qw422016.N().S(`
  <div class="magazine__list">
    `)
//line views.html:339
			for _, item := range items[5:] {
//line views.html:339
				qw422016.N().S(`
    `)
//line views.html:340
				StreamMagazineCard(qw422016, ctx, item, "")
//line views.html:340
				qw422016.N().S(`
    `)
//line views.html:341
			}
//line views.html:341
			qw422016.N().S(`
  </div>
  `)
//line views.html:343
		}
//line views.html:343
		qw422016.N().S(`
</div>
`)
//line views.html:345
	}
//line views.html:345
	qw422016.N().S(`
`)
//line views.html:346
}

//line views.html:346
func WriteMagazine(qq422016 qtio422016.Writer, ctx *Ctx) {
//line views.html:346
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:346
	StreamMagazine(qw422016, ctx)
//line views.html:346
	qt422016.ReleaseWriter(qw422016)
//line views.html:346
}

//line views.html:346
func Magazine(ctx *Ctx) string {
//line views.html:346
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:346
	WriteMagazine(qb422016, ctx)
//line views.html:346
	qs422016 := string(qb422016.B)
//line views.html:346
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:346
	return qs422016
//line views.html:346
}

//line views.html:348
func StreamMagazineCard(qw422016 *qt422016.Writer, ctx *Ctx, item MagazineItem, extraClass string) {
//line views.html:348
	qw422016.N().S(`
`)
//line views.html:350
	itemClass := "magazine-item magazine-item--list"
	if item.Size == MagazineItemFeatured {
		itemClass = "magazine-item magazine-item--featured"
	} else if item.Size == MagazineItemSmall {
		itemClass = "magazine-item magazine-item--small"
	}
	if extraClass != "" {
		itemClass += " " + extraClass
	}

//line views.html:359
	qw422016.N().S(`
<article class="`)
//line views.html:360
	qw422016.N().S(itemClass)
//line views.html:360
	qw422016.N().S(`">
`)
//line views.html:361
	if item.Size == MagazineItemFeatured {
//line views.html:361
		qw422016.N().S(`
  <h2 class="magazine-item__title"><a class="magazine-item__link" href="`)
//line views.html:362
		qw422016.N().S(item.Note.PermalinkEncoded())
//line views.html:362
		qw422016.N().S(`">`)
//line views.html:362
		qw422016.E().S(item.Note.Title())
//line views.html:362
		qw422016.N().S(`</a></h2>
  `)
//line views.html:363
	} else {
//line views.html:363
		qw422016.N().S(`
  <h3 class="magazine-item__title"><a class="magazine-item__link" href="`)
//line views.html:364
		qw422016.N().S(item.Note.PermalinkEncoded())
//line views.html:364
		qw422016.N().S(`">`)
//line views.html:364
		qw422016.E().S(item.Note.Title())
//line views.html:364
		qw422016.N().S(`</a></h3>
  `)
//line views.html:365
	}
//line views.html:365
	qw422016.N().S(`
  `)
//line views.html:366
	pr := item.Note.PartialRenderer()

//line views.html:366
	qw422016.N().S(`
  `)
//line views.html:367
	if pr != nil {
//line views.html:367
		qw422016.N().S(`
  `)
//line views.html:368
		intro := pr.Introduce()

//line views.html:368
		qw422016.N().S(`
  `)
//line views.html:369
		if intro.ContentHTML != "" {
//line views.html:369
			qw422016.N().S(`
  <p class="magazine-item__excerpt">`)
//line views.html:370
			qw422016.N().S(intro.ContentHTML)
//line views.html:370
			qw422016.N().S(`</p>
  `)
//line views.html:371
		}
//line views.html:371
		qw422016.N().S(`
  `)
//line views.html:372
	}
//line views.html:372
	qw422016.N().S(`
  <div class="magazine-item__footer">
    <a class="magazine-item__readmore" href="`)
//line views.html:374
	qw422016.N().S(item.Note.PermalinkEncoded())
//line views.html:374
	qw422016.N().S(`">`)
//line views.html:374
	qw422016.E().S(ctx.T("readmore"))
//line views.html:374
	qw422016.N().S(`</a>
    <time class="magazine-item__date">`)
//line views.html:375
	qw422016.E().S(item.Note.CreatedAt().Format("2006-01-02"))
//line views.html:375
	qw422016.N().S(`</time>
  </div>
</article>
`)
//line views.html:378
}

//line views.html:378
func WriteMagazineCard(qq422016 qtio422016.Writer, ctx *Ctx, item MagazineItem, extraClass string) {
//line views.html:378
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:378
	StreamMagazineCard(qw422016, ctx, item, extraClass)
//line views.html:378
	qt422016.ReleaseWriter(qw422016)
//line views.html:378
}

//line views.html:378
func MagazineCard(ctx *Ctx, item MagazineItem, extraClass string) string {
//line views.html:378
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:378
	WriteMagazineCard(qb422016, ctx, item, extraClass)
//line views.html:378
	qs422016 := string(qb422016.B)
//line views.html:378
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:378
	return qs422016
//line views.html:378
}

//line views.html:380
func StreamSiteHeader(qw422016 *qt422016.Writer, ctx *Ctx, headerNote *templateviews.Note, hasLeft bool, hasRight bool) {
//line views.html:380
	qw422016.N().S(`
<header class="site-header">
  <div class="site-header__content">
    `)
//line views.html:383
	if hasLeft {
//line views.html:383
		qw422016.N().S(`
    <button class="site-header__hamburger site-header__hamburger--left" aria-label="Open menu" id="btn-left">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><line x1="3" y1="6" x2="21" y2="6"/><line x1="3" y1="12" x2="21" y2="12"/><line x1="3" y1="18" x2="21" y2="18"/></svg>
    </button>
    `)
//line views.html:387
	}
//line views.html:387
	qw422016.N().S(`
    `)
//line views.html:388
	logoURL := headerNote.FirstImageURL()

//line views.html:388
	qw422016.N().S(`
    `)
//line views.html:389
	if logoURL != "" {
//line views.html:389
		qw422016.N().S(`
    <a class="site-header__logo" href="/"><img src="`)
//line views.html:390
		qw422016.N().S(logoURL)
//line views.html:390
		qw422016.N().S(`" alt="Logo"></a>
    `)
//line views.html:391
	}
//line views.html:391
	qw422016.N().S(`
    `)
//line views.html:392
	navHTML := headerNote.FirstListHTML()

//line views.html:392
	qw422016.N().S(`
    `)
//line views.html:393
	if navHTML != "" {
//line views.html:393
		qw422016.N().S(`
    <nav class="site-header__nav">`)
//line views.html:394
		qw422016.N().S(navHTML)
//line views.html:394
		qw422016.N().S(`</nav>
    `)
//line views.html:395
	}
//line views.html:395
	qw422016.N().S(`

    <div class="site-header__space" mol_view_root="$trip2g_user_space"></div>
    `)
//line views.html:398
	if hasRight {
//line views.html:398
		qw422016.N().S(`
    <button class="site-header__hamburger site-header__hamburger--right" aria-label="Open related" id="btn-right">
      <svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><rect x="3" y="3" width="7" height="7"/><rect x="14" y="3" width="7" height="7"/><rect x="3" y="14" width="7" height="7"/><rect x="14" y="14" width="7" height="7"/></svg>
    </button>
    `)
//line views.html:402
	}
//line views.html:402
	qw422016.N().S(`
  </div>
</header>

<div class="search-wrapper">
  <div mol_view_root="$trip2g_user_search"></div>
</div>
`)
//line views.html:409
}

//line views.html:409
func WriteSiteHeader(qq422016 qtio422016.Writer, ctx *Ctx, headerNote *templateviews.Note, hasLeft bool, hasRight bool) {
//line views.html:409
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:409
	StreamSiteHeader(qw422016, ctx, headerNote, hasLeft, hasRight)
//line views.html:409
	qt422016.ReleaseWriter(qw422016)
//line views.html:409
}

//line views.html:409
func SiteHeader(ctx *Ctx, headerNote *templateviews.Note, hasLeft bool, hasRight bool) string {
//line views.html:409
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:409
	WriteSiteHeader(qb422016, ctx, headerNote, hasLeft, hasRight)
//line views.html:409
	qs422016 := string(qb422016.B)
//line views.html:409
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:409
	return qs422016
//line views.html:409
}

//line views.html:411
func StreamSiteFooter(qw422016 *qt422016.Writer, ctx *Ctx, footerNote *templateviews.Note) {
//line views.html:411
	qw422016.N().S(`
<footer class="site-footer">
  <div class="site-footer__content">
    `)
//line views.html:414
	intro := footerNote.PartialRenderer().Introduce()

//line views.html:414
	qw422016.N().S(`
    `)
//line views.html:415
	if intro.ContentHTML != "" {
//line views.html:415
		qw422016.N().S(`
    <div class="site-footer__brand">
      `)
//line views.html:417
		qw422016.N().S(intro.ContentHTML)
//line views.html:417
		qw422016.N().S(`
    </div>
    `)
//line views.html:419
	}
//line views.html:419
	qw422016.N().S(`
    `)
//line views.html:420
	sections := footerNote.PartialRenderer().Sections(3)

//line views.html:420
	qw422016.N().S(`
    `)
//line views.html:421
	if len(sections) > 1 {
//line views.html:421
		qw422016.N().S(`
    <div class="site-footer__links site-footer__links--columns">
      `)
//line views.html:423
		for _, sec := range sections {
//line views.html:423
			qw422016.N().S(`
      <div class="site-footer__column">
        <p class="site-footer__column-title">`)
//line views.html:425
			qw422016.N().S(sec.TitleHTML)
//line views.html:425
			qw422016.N().S(`</p>
        `)
//line views.html:426
			qw422016.N().S(sec.ContentHTML)
//line views.html:426
			qw422016.N().S(`
      </div>
      `)
//line views.html:428
		}
//line views.html:428
		qw422016.N().S(`
    </div>
    `)
//line views.html:430
	} else {
//line views.html:430
		qw422016.N().S(`
    `)
//line views.html:431
		listHTML := footerNote.FirstListHTML()

//line views.html:431
		qw422016.N().S(`
    `)
//line views.html:432
		if listHTML != "" {
//line views.html:432
			qw422016.N().S(`
    <div class="site-footer__links site-footer__links--inline">`)
//line views.html:433
			qw422016.N().S(listHTML)
//line views.html:433
			qw422016.N().S(`</div>
    `)
//line views.html:434
		}
//line views.html:434
		qw422016.N().S(`
    `)
//line views.html:435
	}
//line views.html:435
	qw422016.N().S(`
  </div>
</footer>
`)
//line views.html:438
}

//line views.html:438
func WriteSiteFooter(qq422016 qtio422016.Writer, ctx *Ctx, footerNote *templateviews.Note) {
//line views.html:438
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:438
	StreamSiteFooter(qw422016, ctx, footerNote)
//line views.html:438
	qt422016.ReleaseWriter(qw422016)
//line views.html:438
}

//line views.html:438
func SiteFooter(ctx *Ctx, footerNote *templateviews.Note) string {
//line views.html:438
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:438
	WriteSiteFooter(qb422016, ctx, footerNote)
//line views.html:438
	qs422016 := string(qb422016.B)
//line views.html:438
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:438
	return qs422016
//line views.html:438
}

//line views.html:440
func StreamSignInWall(qw422016 *qt422016.Writer, ctx *Ctx) {
//line views.html:440
	qw422016.N().S(`
<div class="paywall-page">
  <div class="paywall-page__header">
    <a class="paywall-page__home" href="/">`)
//line views.html:443
	qw422016.E().S(ctx.T("signinwall_home"))
//line views.html:443
	qw422016.N().S(`</a>
    <div mol_view_root="$trip2g_user_space"></div>
  </div>

  `)
//line views.html:447
	if ctx.SigninWallError != nil && ctx.SigninWallError.Note != nil {
//line views.html:447
		qw422016.N().S(`
  <h1 class="content__title">`)
//line views.html:448
		qw422016.E().S(ctx.SigninWallError.Note.Title())
//line views.html:448
		qw422016.N().S(`</h1>
  `)
//line views.html:449
		if ctx.SigninWallError.Note.Description() != "" {
//line views.html:449
			qw422016.N().S(`
  <p>`)
//line views.html:450
			qw422016.E().S(ctx.SigninWallError.Note.Description())
//line views.html:450
			qw422016.N().S(`</p>
  `)
//line views.html:451
		}
//line views.html:451
		qw422016.N().S(`
  `)
//line views.html:452
	}
//line views.html:452
	qw422016.N().S(`

  <div id="signinwall" mol_view_root="$trip2g_user_signinwall"></div>
</div>
`)
//line views.html:456
}

//line views.html:456
func WriteSignInWall(qq422016 qtio422016.Writer, ctx *Ctx) {
//line views.html:456
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:456
	StreamSignInWall(qw422016, ctx)
//line views.html:456
	qt422016.ReleaseWriter(qw422016)
//line views.html:456
}

//line views.html:456
func SignInWall(ctx *Ctx) string {
//line views.html:456
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:456
	WriteSignInWall(qb422016, ctx)
//line views.html:456
	qs422016 := string(qb422016.B)
//line views.html:456
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:456
	return qs422016
//line views.html:456
}

//line views.html:458
func StreamPayWall(qw422016 *qt422016.Writer, ctx *Ctx) {
//line views.html:458
	qw422016.N().S(`
<div class="paywall-page">
  <div class="paywall-page__header">
    <a class="paywall-page__home" href="/">`)
//line views.html:461
	qw422016.E().S(ctx.T("paywall_home"))
//line views.html:461
	qw422016.N().S(`</a>
    <div mol_view_root="$trip2g_user_space"></div>
  </div>

  `)
//line views.html:465
	if ctx.Note != nil {
//line views.html:465
		qw422016.N().S(`
  <h1 class="content__title">`)
//line views.html:466
		qw422016.E().S(ctx.Note.Title())
//line views.html:466
		qw422016.N().S(`</h1>

  `)
//line views.html:468
		if ctx.Note.Description() != "" {
//line views.html:468
			qw422016.N().S(`
  <p>`)
//line views.html:469
			qw422016.E().S(ctx.Note.Description())
//line views.html:469
			qw422016.N().S(`</p>
  `)
//line views.html:470
		}
//line views.html:470
		qw422016.N().S(`

  `)
//line views.html:472
		if ctx.PaywallError != nil {
//line views.html:472
			qw422016.N().S(`
  <script>
    window.__trip2g_paywall = {
      page_id: `)
//line views.html:475
			qw422016.N().DL(ctx.Note.PathID())
//line views.html:475
			qw422016.N().S(`,
    }
  </script>
  <div
    id="paywall"
    mol_view_root="$trip2g_user_paywall"
    data-subgraphs="`)
//line views.html:481
			qw422016.E().S(ctx.PaywallError.SubgraphsJSON)
//line views.html:481
			qw422016.N().S(`"
    data-path-id="`)
//line views.html:482
			qw422016.N().DL(ctx.Note.PathID())
//line views.html:482
			qw422016.N().S(`"
  ></div>
  `)
//line views.html:484
		}
//line views.html:484
		qw422016.N().S(`
  `)
//line views.html:485
	}
//line views.html:485
	qw422016.N().S(`
</div>
`)
//line views.html:487
}

//line views.html:487
func WritePayWall(qq422016 qtio422016.Writer, ctx *Ctx) {
//line views.html:487
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:487
	StreamPayWall(qw422016, ctx)
//line views.html:487
	qt422016.ReleaseWriter(qw422016)
//line views.html:487
}

//line views.html:487
func PayWall(ctx *Ctx) string {
//line views.html:487
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:487
	WritePayWall(qb422016, ctx)
//line views.html:487
	qs422016 := string(qb422016.B)
//line views.html:487
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:487
	return qs422016
//line views.html:487
}

//line views.html:489
func StreamNotFound(qw422016 *qt422016.Writer, ctx *Ctx) {
//line views.html:489
	qw422016.N().S(`
`)
//line views.html:491
	headerRef := ctx.HeaderRef()
	footerRef := ctx.FooterRef()

//line views.html:493
	qw422016.N().S(`
`)
//line views.html:494
	var headerNote *templateviews.Note

//line views.html:494
	qw422016.N().S(`
`)
//line views.html:495
	if headerRef.Kind != ContentRefNone {
//line views.html:495
		qw422016.N().S(`
  `)
//line views.html:496
		headerNote = ctx.resolveNoteRef(headerRef)

//line views.html:496
		qw422016.N().S(`
`)
//line views.html:497
	}
//line views.html:497
	qw422016.N().S(`
`)
//line views.html:498
	if headerNote != nil {
//line views.html:498
		qw422016.N().S(`
  `)
//line views.html:499
		StreamSiteHeader(qw422016, ctx, headerNote, false, false)
//line views.html:499
		qw422016.N().S(`
`)
//line views.html:500
	}
//line views.html:500
	qw422016.N().S(`
<div class="layout layout--no-sidebars">
  <main class="notfound">
    <div class="notfound__code">404</div>
    <p class="notfound__message">Page not found</p>
    <a class="notfound__home" href="/">← Home</a>
  </main>
</div>
`)
//line views.html:508
	if footerRef.Kind != ContentRefNone {
//line views.html:508
		qw422016.N().S(`
  `)
//line views.html:509
		footerNote := ctx.resolveNoteRef(footerRef)

//line views.html:509
		qw422016.N().S(`
  `)
//line views.html:510
		if footerNote != nil {
//line views.html:510
			qw422016.N().S(`
    `)
//line views.html:511
			StreamSiteFooter(qw422016, ctx, footerNote)
//line views.html:511
			qw422016.N().S(`
  `)
//line views.html:512
		}
//line views.html:512
		qw422016.N().S(`
`)
//line views.html:513
	}
//line views.html:513
	qw422016.N().S(`
`)
//line views.html:514
}

//line views.html:514
func WriteNotFound(qq422016 qtio422016.Writer, ctx *Ctx) {
//line views.html:514
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:514
	StreamNotFound(qw422016, ctx)
//line views.html:514
	qt422016.ReleaseWriter(qw422016)
//line views.html:514
}

//line views.html:514
func NotFound(ctx *Ctx) string {
//line views.html:514
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:514
	WriteNotFound(qb422016, ctx)
//line views.html:514
	qs422016 := string(qb422016.B)
//line views.html:514
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:514
	return qs422016
//line views.html:514
}

//line views.html:516
func StreamUnsupportedFile(qw422016 *qt422016.Writer, ctx *Ctx) {
//line views.html:516
	qw422016.N().S(`
<main class="layout__main">
  <article class="content">
    <div class="content__body">
      `)
//line views.html:520
	if ctx.UnsupportedFileExt == ".canvas" {
//line views.html:520
		qw422016.N().S(`
      <p>Canvas files are not supported yet.</p>
      `)
//line views.html:522
	} else if ctx.UnsupportedFileExt == ".excalidraw" {
//line views.html:522
		qw422016.N().S(`
      <p>Excalidraw files are not supported yet.</p>
      `)
//line views.html:524
	} else {
//line views.html:524
		qw422016.N().S(`
      <p>Bases are not supported yet.</p>
      `)
//line views.html:526
	}
//line views.html:526
	qw422016.N().S(`
    </div>
  </article>
</main>
`)
//line views.html:530
}

//line views.html:530
func WriteUnsupportedFile(qq422016 qtio422016.Writer, ctx *Ctx) {
//line views.html:530
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:530
	StreamUnsupportedFile(qw422016, ctx)
//line views.html:530
	qt422016.ReleaseWriter(qw422016)
//line views.html:530
}

//line views.html:530
func UnsupportedFile(ctx *Ctx) string {
//line views.html:530
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:530
	WriteUnsupportedFile(qb422016, ctx)
//line views.html:530
	qs422016 := string(qb422016.B)
//line views.html:530
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:530
	return qs422016
//line views.html:530
}

//line views.html:532
func StreamOnboarding(qw422016 *qt422016.Writer, ctx *Ctx) {
//line views.html:532
	qw422016.N().S(`
<div class="onboarding" data-onboarding>
  `)
//line views.html:534
	if ctx.UserToken.IsAdmin() {
//line views.html:534
		qw422016.N().S(`
  <h3>Welcome!</h3>
  <p>
    Download the starter archive and open it in Obsidian.
    An API key will be created and packed into a ZIP archive with a demo vault.
  </p>
  <p>
    Do not share this archive with anyone as it contains a private key.
    The archive contains only a demo vault. If you already have data,
    two-way sync will offer to download current content from the server.
  </p>
  <p>
    <a href="/_system/onboarding-vault" class="onboarding__cta">
      Download archive
    </a>
  </p>
  `)
//line views.html:550
	} else {
//line views.html:550
		qw422016.N().S(`
  <h3>`)
//line views.html:551
		qw422016.E().S(ctx.T("onboarding_title"))
//line views.html:551
		qw422016.N().S(`</h3>
  <p>`)
//line views.html:552
		qw422016.E().S(ctx.T("onboarding_subtitle"))
//line views.html:552
		qw422016.N().S(`</p>
  `)
//line views.html:553
	}
//line views.html:553
	qw422016.N().S(`
  <div mol_view_root="$trip2g_user_space"></div>
</div>
`)
//line views.html:556
}

//line views.html:556
func WriteOnboarding(qq422016 qtio422016.Writer, ctx *Ctx) {
//line views.html:556
	qw422016 := qt422016.AcquireWriter(qq422016)
//line views.html:556
	StreamOnboarding(qw422016, ctx)
//line views.html:556
	qt422016.ReleaseWriter(qw422016)
//line views.html:556
}

//line views.html:556
func Onboarding(ctx *Ctx) string {
//line views.html:556
	qb422016 := qt422016.AcquireByteBuffer()
//line views.html:556
	WriteOnboarding(qb422016, ctx)
//line views.html:556
	qs422016 := string(qb422016.B)
//line views.html:556
	qt422016.ReleaseByteBuffer(qb422016)
//line views.html:556
	return qs422016
//line views.html:556
}
