// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"trip2g/internal/db"
	"trip2g/internal/usertoken"
)

type RequestEmailSignInCodeOrErrorPayload interface {
	IsRequestEmailSignInCodeOrErrorPayload()
}

type SignInOrErrorPayload interface {
	IsSignInOrErrorPayload()
}

type SignOutOrErrorPayload interface {
	IsSignOutOrErrorPayload()
}

type UpdateSubgraphOrErrorPayload interface {
	IsUpdateSubgraphOrErrorPayload()
}

type AdminMutation struct {
	UpdateSubgraph UpdateSubgraphOrErrorPayload `json:"updateSubgraph"`
}

type AdminQuery struct {
	AllUsers                *AdminUsersConnection                `json:"allUsers"`
	AllSubgraphs            *AdminSubgraphsConnection            `json:"allSubgraphs"`
	AllUserSubgraphAccesses *AdminUserSubgraphAccessesConnection `json:"allUserSubgraphAccesses"`
}

type AdminSubgraphsConnection struct {
	Nodes []db.Subgraph `json:"nodes"`
}

type AdminUserSubgraphAccessesConnection struct {
	Nodes []db.UserSubgraphAccess `json:"nodes"`
}

type AdminUsersConnection struct {
	Nodes []db.User `json:"nodes"`
}

type ErrorPayload struct {
	Message  string         `json:"message"`
	ByFields []FieldMessage `json:"byFields"`
}

func (ErrorPayload) IsRequestEmailSignInCodeOrErrorPayload() {}

func (ErrorPayload) IsSignInOrErrorPayload() {}

func (ErrorPayload) IsSignOutOrErrorPayload() {}

func (ErrorPayload) IsUpdateSubgraphOrErrorPayload() {}

type FieldMessage struct {
	Name  string `json:"name"`
	Value string `json:"value"`
}

type Mutation struct {
}

type Query struct {
}

type RequestEmailSignInCodePayload struct {
	Success bool `json:"success"`
}

func (RequestEmailSignInCodePayload) IsRequestEmailSignInCodeOrErrorPayload() {}

type SignInPayload struct {
	Token  string  `json:"token"`
	Viewer *Viewer `json:"viewer"`
}

func (SignInPayload) IsSignInOrErrorPayload() {}

type SignOutPayload struct {
	Viewer *Viewer `json:"viewer"`
}

func (SignOutPayload) IsSignOutOrErrorPayload() {}

type UpdateSubgraphPayload struct {
	Subgraph *db.Subgraph `json:"subgraph"`
}

func (UpdateSubgraphPayload) IsUpdateSubgraphOrErrorPayload() {}

type Viewer struct {
	ID        string          `json:"id"`
	User      *db.User        `json:"user,omitempty"`
	UserID    *int64          `json:"-"`
	UserToken *usertoken.Data `json:"-"`
}
