// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type trip2g_admin_deliverytrace_catalog_listQueryVariables = Exact<{
  withEmpty: Scalars['Boolean']['input'];
}>;


export type trip2g_admin_deliverytrace_catalog_listQuery = { __typename?: 'Query', admin: { __typename?: 'AdminQuery', deliveryTraces: Array<{ __typename?: 'AdminDeliveryTrace', trace?: string | null, startedAt: any, lastAt: any, deliveries: any, depthReached: any, writes: any, totalCosts: Array<{ __typename?: 'AdminCost', id: string, value: number }> }> } };


export function $trip2g_admin_deliverytrace_catalog_list(variables: trip2g_admin_deliverytrace_catalog_listQueryVariables, opts?: { revalidate?: boolean }): trip2g_admin_deliverytrace_catalog_listQuery {
	return $trip2g_gql_request(`query trip2g_admin_deliverytrace_catalog_list(\u0024withEmpty: Boolean!) {
  admin {
    deliveryTraces(limit: 50, withEmpty: \u0024withEmpty) {
      trace
      startedAt
      lastAt
      deliveries
      depthReached
      totalCosts {
        id
        value
      }
      writes
    }
  }
}`, variables, opts) as trip2g_admin_deliverytrace_catalog_listQuery
}

}
