// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package deleteredirect

import (
	"context"
	"sync"
	"trip2g/internal/usertoken"
)

// Ensure, that EnvMock does implement Env.
// If this is not the case, regenerate this file with moq.
var _ Env = &EnvMock{}

// EnvMock is a mock implementation of Env.
//
//	func TestSomethingThatUsesEnv(t *testing.T) {
//
//		// make and configure a mocked Env
//		mockedEnv := &EnvMock{
//			CurrentAdminUserTokenFunc: func(ctx context.Context) (*usertoken.Data, error) {
//				panic("mock out the CurrentAdminUserToken method")
//			},
//			DeleteRedirectFunc: func(ctx context.Context, id int64) error {
//				panic("mock out the DeleteRedirect method")
//			},
//		}
//
//		// use mockedEnv in code that requires Env
//		// and then make assertions.
//
//	}
type EnvMock struct {
	// CurrentAdminUserTokenFunc mocks the CurrentAdminUserToken method.
	CurrentAdminUserTokenFunc func(ctx context.Context) (*usertoken.Data, error)

	// DeleteRedirectFunc mocks the DeleteRedirect method.
	DeleteRedirectFunc func(ctx context.Context, id int64) error

	// calls tracks calls to the methods.
	calls struct {
		// CurrentAdminUserToken holds details about calls to the CurrentAdminUserToken method.
		CurrentAdminUserToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// DeleteRedirect holds details about calls to the DeleteRedirect method.
		DeleteRedirect []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
	}
	lockCurrentAdminUserToken sync.RWMutex
	lockDeleteRedirect        sync.RWMutex
}

// CurrentAdminUserToken calls CurrentAdminUserTokenFunc.
func (mock *EnvMock) CurrentAdminUserToken(ctx context.Context) (*usertoken.Data, error) {
	if mock.CurrentAdminUserTokenFunc == nil {
		panic("EnvMock.CurrentAdminUserTokenFunc: method is nil but Env.CurrentAdminUserToken was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCurrentAdminUserToken.Lock()
	mock.calls.CurrentAdminUserToken = append(mock.calls.CurrentAdminUserToken, callInfo)
	mock.lockCurrentAdminUserToken.Unlock()
	return mock.CurrentAdminUserTokenFunc(ctx)
}

// CurrentAdminUserTokenCalls gets all the calls that were made to CurrentAdminUserToken.
// Check the length with:
//
//	len(mockedEnv.CurrentAdminUserTokenCalls())
func (mock *EnvMock) CurrentAdminUserTokenCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCurrentAdminUserToken.RLock()
	calls = mock.calls.CurrentAdminUserToken
	mock.lockCurrentAdminUserToken.RUnlock()
	return calls
}

// DeleteRedirect calls DeleteRedirectFunc.
func (mock *EnvMock) DeleteRedirect(ctx context.Context, id int64) error {
	if mock.DeleteRedirectFunc == nil {
		panic("EnvMock.DeleteRedirectFunc: method is nil but Env.DeleteRedirect was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockDeleteRedirect.Lock()
	mock.calls.DeleteRedirect = append(mock.calls.DeleteRedirect, callInfo)
	mock.lockDeleteRedirect.Unlock()
	return mock.DeleteRedirectFunc(ctx, id)
}

// DeleteRedirectCalls gets all the calls that were made to DeleteRedirect.
// Check the length with:
//
//	len(mockedEnv.DeleteRedirectCalls())
func (mock *EnvMock) DeleteRedirectCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockDeleteRedirect.RLock()
	calls = mock.calls.DeleteRedirect
	mock.lockDeleteRedirect.RUnlock()
	return calls
}
