// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package handletgnavigationupdate

import (
	"context"
	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api/v5"
	"sync"
	"trip2g/internal/db"
	"trip2g/internal/logger"
	"trip2g/internal/model"
)

// Ensure, that EnvMock does implement Env.
// If this is not the case, regenerate this file with moq.
var _ Env = &EnvMock{}

// EnvMock is a mock implementation of Env.
//
//	func TestSomethingThatUsesEnv(t *testing.T) {
//
//		// make and configure a mocked Env
//		mockedEnv := &EnvMock{
//			BotIDFunc: func() int64 {
//				panic("mock out the BotID method")
//			},
//			BotLinkFunc: func() string {
//				panic("mock out the BotLink method")
//			},
//			LatestNoteViewsFunc: func() *model.NoteViews {
//				panic("mock out the LatestNoteViews method")
//			},
//			LoggerFunc: func() logger.Logger {
//				panic("mock out the Logger method")
//			},
//			RequestFunc: func(c tgbotapi.Chattable) (*tgbotapi.APIResponse, error) {
//				panic("mock out the Request method")
//			},
//			SendFunc: func(msg tgbotapi.Chattable) (tgbotapi.Message, error) {
//				panic("mock out the Send method")
//			},
//			TgUserStateByBotIDAndChatIDFunc: func(ctx context.Context, arg db.TgUserStateByBotIDAndChatIDParams) (db.TgUserState, error) {
//				panic("mock out the TgUserStateByBotIDAndChatID method")
//			},
//			UpsertTgUserStateFunc: func(ctx context.Context, arg db.UpsertTgUserStateParams) error {
//				panic("mock out the UpsertTgUserState method")
//			},
//		}
//
//		// use mockedEnv in code that requires Env
//		// and then make assertions.
//
//	}
type EnvMock struct {
	// BotIDFunc mocks the BotID method.
	BotIDFunc func() int64

	// BotLinkFunc mocks the BotLink method.
	BotLinkFunc func() string

	// LatestNoteViewsFunc mocks the LatestNoteViews method.
	LatestNoteViewsFunc func() *model.NoteViews

	// LoggerFunc mocks the Logger method.
	LoggerFunc func() logger.Logger

	// RequestFunc mocks the Request method.
	RequestFunc func(c tgbotapi.Chattable) (*tgbotapi.APIResponse, error)

	// SendFunc mocks the Send method.
	SendFunc func(msg tgbotapi.Chattable) (tgbotapi.Message, error)

	// TgUserStateByBotIDAndChatIDFunc mocks the TgUserStateByBotIDAndChatID method.
	TgUserStateByBotIDAndChatIDFunc func(ctx context.Context, arg db.TgUserStateByBotIDAndChatIDParams) (db.TgUserState, error)

	// UpsertTgUserStateFunc mocks the UpsertTgUserState method.
	UpsertTgUserStateFunc func(ctx context.Context, arg db.UpsertTgUserStateParams) error

	// calls tracks calls to the methods.
	calls struct {
		// BotID holds details about calls to the BotID method.
		BotID []struct {
		}
		// BotLink holds details about calls to the BotLink method.
		BotLink []struct {
		}
		// LatestNoteViews holds details about calls to the LatestNoteViews method.
		LatestNoteViews []struct {
		}
		// Logger holds details about calls to the Logger method.
		Logger []struct {
		}
		// Request holds details about calls to the Request method.
		Request []struct {
			// C is the c argument value.
			C tgbotapi.Chattable
		}
		// Send holds details about calls to the Send method.
		Send []struct {
			// Msg is the msg argument value.
			Msg tgbotapi.Chattable
		}
		// TgUserStateByBotIDAndChatID holds details about calls to the TgUserStateByBotIDAndChatID method.
		TgUserStateByBotIDAndChatID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.TgUserStateByBotIDAndChatIDParams
		}
		// UpsertTgUserState holds details about calls to the UpsertTgUserState method.
		UpsertTgUserState []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.UpsertTgUserStateParams
		}
	}
	lockBotID                       sync.RWMutex
	lockBotLink                     sync.RWMutex
	lockLatestNoteViews             sync.RWMutex
	lockLogger                      sync.RWMutex
	lockRequest                     sync.RWMutex
	lockSend                        sync.RWMutex
	lockTgUserStateByBotIDAndChatID sync.RWMutex
	lockUpsertTgUserState           sync.RWMutex
}

// BotID calls BotIDFunc.
func (mock *EnvMock) BotID() int64 {
	if mock.BotIDFunc == nil {
		panic("EnvMock.BotIDFunc: method is nil but Env.BotID was just called")
	}
	callInfo := struct {
	}{}
	mock.lockBotID.Lock()
	mock.calls.BotID = append(mock.calls.BotID, callInfo)
	mock.lockBotID.Unlock()
	return mock.BotIDFunc()
}

// BotIDCalls gets all the calls that were made to BotID.
// Check the length with:
//
//	len(mockedEnv.BotIDCalls())
func (mock *EnvMock) BotIDCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockBotID.RLock()
	calls = mock.calls.BotID
	mock.lockBotID.RUnlock()
	return calls
}

// BotLink calls BotLinkFunc.
func (mock *EnvMock) BotLink() string {
	if mock.BotLinkFunc == nil {
		panic("EnvMock.BotLinkFunc: method is nil but Env.BotLink was just called")
	}
	callInfo := struct {
	}{}
	mock.lockBotLink.Lock()
	mock.calls.BotLink = append(mock.calls.BotLink, callInfo)
	mock.lockBotLink.Unlock()
	return mock.BotLinkFunc()
}

// BotLinkCalls gets all the calls that were made to BotLink.
// Check the length with:
//
//	len(mockedEnv.BotLinkCalls())
func (mock *EnvMock) BotLinkCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockBotLink.RLock()
	calls = mock.calls.BotLink
	mock.lockBotLink.RUnlock()
	return calls
}

// LatestNoteViews calls LatestNoteViewsFunc.
func (mock *EnvMock) LatestNoteViews() *model.NoteViews {
	if mock.LatestNoteViewsFunc == nil {
		panic("EnvMock.LatestNoteViewsFunc: method is nil but Env.LatestNoteViews was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLatestNoteViews.Lock()
	mock.calls.LatestNoteViews = append(mock.calls.LatestNoteViews, callInfo)
	mock.lockLatestNoteViews.Unlock()
	return mock.LatestNoteViewsFunc()
}

// LatestNoteViewsCalls gets all the calls that were made to LatestNoteViews.
// Check the length with:
//
//	len(mockedEnv.LatestNoteViewsCalls())
func (mock *EnvMock) LatestNoteViewsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLatestNoteViews.RLock()
	calls = mock.calls.LatestNoteViews
	mock.lockLatestNoteViews.RUnlock()
	return calls
}

// Logger calls LoggerFunc.
func (mock *EnvMock) Logger() logger.Logger {
	if mock.LoggerFunc == nil {
		panic("EnvMock.LoggerFunc: method is nil but Env.Logger was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLogger.Lock()
	mock.calls.Logger = append(mock.calls.Logger, callInfo)
	mock.lockLogger.Unlock()
	return mock.LoggerFunc()
}

// LoggerCalls gets all the calls that were made to Logger.
// Check the length with:
//
//	len(mockedEnv.LoggerCalls())
func (mock *EnvMock) LoggerCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLogger.RLock()
	calls = mock.calls.Logger
	mock.lockLogger.RUnlock()
	return calls
}

// Request calls RequestFunc.
func (mock *EnvMock) Request(c tgbotapi.Chattable) (*tgbotapi.APIResponse, error) {
	if mock.RequestFunc == nil {
		panic("EnvMock.RequestFunc: method is nil but Env.Request was just called")
	}
	callInfo := struct {
		C tgbotapi.Chattable
	}{
		C: c,
	}
	mock.lockRequest.Lock()
	mock.calls.Request = append(mock.calls.Request, callInfo)
	mock.lockRequest.Unlock()
	return mock.RequestFunc(c)
}

// RequestCalls gets all the calls that were made to Request.
// Check the length with:
//
//	len(mockedEnv.RequestCalls())
func (mock *EnvMock) RequestCalls() []struct {
	C tgbotapi.Chattable
} {
	var calls []struct {
		C tgbotapi.Chattable
	}
	mock.lockRequest.RLock()
	calls = mock.calls.Request
	mock.lockRequest.RUnlock()
	return calls
}

// Send calls SendFunc.
func (mock *EnvMock) Send(msg tgbotapi.Chattable) (tgbotapi.Message, error) {
	if mock.SendFunc == nil {
		panic("EnvMock.SendFunc: method is nil but Env.Send was just called")
	}
	callInfo := struct {
		Msg tgbotapi.Chattable
	}{
		Msg: msg,
	}
	mock.lockSend.Lock()
	mock.calls.Send = append(mock.calls.Send, callInfo)
	mock.lockSend.Unlock()
	return mock.SendFunc(msg)
}

// SendCalls gets all the calls that were made to Send.
// Check the length with:
//
//	len(mockedEnv.SendCalls())
func (mock *EnvMock) SendCalls() []struct {
	Msg tgbotapi.Chattable
} {
	var calls []struct {
		Msg tgbotapi.Chattable
	}
	mock.lockSend.RLock()
	calls = mock.calls.Send
	mock.lockSend.RUnlock()
	return calls
}

// TgUserStateByBotIDAndChatID calls TgUserStateByBotIDAndChatIDFunc.
func (mock *EnvMock) TgUserStateByBotIDAndChatID(ctx context.Context, arg db.TgUserStateByBotIDAndChatIDParams) (db.TgUserState, error) {
	if mock.TgUserStateByBotIDAndChatIDFunc == nil {
		panic("EnvMock.TgUserStateByBotIDAndChatIDFunc: method is nil but Env.TgUserStateByBotIDAndChatID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.TgUserStateByBotIDAndChatIDParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockTgUserStateByBotIDAndChatID.Lock()
	mock.calls.TgUserStateByBotIDAndChatID = append(mock.calls.TgUserStateByBotIDAndChatID, callInfo)
	mock.lockTgUserStateByBotIDAndChatID.Unlock()
	return mock.TgUserStateByBotIDAndChatIDFunc(ctx, arg)
}

// TgUserStateByBotIDAndChatIDCalls gets all the calls that were made to TgUserStateByBotIDAndChatID.
// Check the length with:
//
//	len(mockedEnv.TgUserStateByBotIDAndChatIDCalls())
func (mock *EnvMock) TgUserStateByBotIDAndChatIDCalls() []struct {
	Ctx context.Context
	Arg db.TgUserStateByBotIDAndChatIDParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.TgUserStateByBotIDAndChatIDParams
	}
	mock.lockTgUserStateByBotIDAndChatID.RLock()
	calls = mock.calls.TgUserStateByBotIDAndChatID
	mock.lockTgUserStateByBotIDAndChatID.RUnlock()
	return calls
}

// UpsertTgUserState calls UpsertTgUserStateFunc.
func (mock *EnvMock) UpsertTgUserState(ctx context.Context, arg db.UpsertTgUserStateParams) error {
	if mock.UpsertTgUserStateFunc == nil {
		panic("EnvMock.UpsertTgUserStateFunc: method is nil but Env.UpsertTgUserState was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.UpsertTgUserStateParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpsertTgUserState.Lock()
	mock.calls.UpsertTgUserState = append(mock.calls.UpsertTgUserState, callInfo)
	mock.lockUpsertTgUserState.Unlock()
	return mock.UpsertTgUserStateFunc(ctx, arg)
}

// UpsertTgUserStateCalls gets all the calls that were made to UpsertTgUserState.
// Check the length with:
//
//	len(mockedEnv.UpsertTgUserStateCalls())
func (mock *EnvMock) UpsertTgUserStateCalls() []struct {
	Ctx context.Context
	Arg db.UpsertTgUserStateParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.UpsertTgUserStateParams
	}
	mock.lockUpsertTgUserState.RLock()
	calls = mock.calls.UpsertTgUserState
	mock.lockUpsertTgUserState.RUnlock()
	return calls
}
