package doclint

import (
	"bufio"
	"context"
	"fmt"
	"io"
	"os"
	"sort"
	"strings"

	"trip2g/internal/logger"
	"trip2g/internal/mdloader"
	"trip2g/internal/model"
	"trip2g/internal/noteloader"
)

// Options controls optional behaviour of Run / RunWithOptions.
type Options struct {
	// BaselineFile is the path to a baseline-ratchet file generated by
	// GenerateBaseline. Warnings whose stable signature appears in the
	// baseline are grandfathered (suppressed from output, don't cause exit 1).
	// Empty string means no baseline is applied.
	BaselineFile string
}

// lintLine is a single lint finding collected before printing.
type lintLine struct {
	path    string
	message string
	level   model.NoteWarningLevel
}

// Run runs the DB-free linter over dir, writes sorted results to w and returns
// exit code 1 if any warnings were found, 0 if clean.
// log may be nil (falls back to DummyLogger).
// It is a thin wrapper around RunWithOptions with an empty Options{}.
func Run(ctx context.Context, dir string, w io.Writer, log logger.Logger) (exitCode int, err error) {
	return RunWithOptions(ctx, dir, w, log, Options{})
}

// RunWithOptions is the full entry-point for the DB-free linter.
// Writes sorted, non-baselined results to w and returns exit code 1 if any
// non-baselined warnings remain, 0 if clean.
func RunWithOptions(ctx context.Context, dir string, w io.Writer, log logger.Logger, opts Options) (exitCode int, err error) {
	if log == nil {
		log = &logger.DummyLogger{}
	}

	lines, loadErr := collectWarnings(ctx, dir, log)
	if loadErr != nil {
		return 1, loadErr
	}

	baseline, baseErr := loadBaseline(opts.BaselineFile)
	if baseErr != nil {
		return 1, baseErr
	}

	var newLines []lintLine
	for _, line := range lines {
		if !baseline[stableSignature(line)] {
			newLines = append(newLines, line)
		}
	}

	for _, line := range newLines {
		fmt.Fprintf(w, "%s:0: %s %s\n", line.path, levelStr(line.level), line.message)
	}

	if len(newLines) > 0 {
		return 1, nil
	}
	return 0, nil
}

// GenerateBaseline runs the linter over dir and writes a baseline-ratchet file
// to baselineFile. Each line in the file is the stable signature of one warning
// (relpath\tlevel\tmessage). Existing baselined warnings are replaced entirely.
func GenerateBaseline(ctx context.Context, dir string, baselineFile string, log logger.Logger) error {
	if log == nil {
		log = &logger.DummyLogger{}
	}

	lines, err := collectWarnings(ctx, dir, log)
	if err != nil {
		return err
	}

	f, err := os.Create(baselineFile)
	if err != nil {
		return fmt.Errorf("doclint: create baseline: %w", err)
	}
	defer f.Close()

	for _, line := range lines {
		if _, werr := fmt.Fprintln(f, stableSignature(line)); werr != nil {
			return fmt.Errorf("doclint: write baseline: %w", werr)
		}
	}
	return nil
}

// collectWarnings loads the vault and returns all lint findings, sorted.
func collectWarnings(ctx context.Context, dir string, log logger.Logger) ([]lintLine, error) {
	env := newFsEnv(dir, log)
	ldr := noteloader.New("lint", env, mdloader.Config{})

	if loadErr := ldr.Load(ctx, noteloader.LoadOptions{SkipSearchIndex: true}); loadErr != nil {
		return nil, fmt.Errorf("doclint: load failed: %w", loadErr)
	}

	nvs := ldr.NoteViews()
	layouts := ldr.Layouts()

	var lines []lintLine

	// --- per-note warnings from the loader pipeline ---
	for _, note := range nvs.List {
		for _, nw := range note.Warnings {
			lines = append(lines, lintLine{
				path:    note.Path,
				message: nw.Message,
				level:   nw.Level,
			})
		}

		// --- lint-added checks on ResolvedLinks ---
		noteLang := pathLangPrefix(note.Path)

		// Collect targets to iterate in sorted order (map iteration is non-deterministic).
		targets := make([]string, 0, len(note.ResolvedLinks))
		for target := range note.ResolvedLinks {
			targets = append(targets, target)
		}
		sort.Strings(targets)

		for _, target := range targets {
			permalink := note.ResolvedLinks[target]
			// Only bare wikilinks (no path separator) are checked.
			if strings.Contains(target, "/") {
				continue
			}

			// Ambiguous bare wikilink: basename maps to >1 note.
			// When ambiguous, resolution is non-deterministic (Go map order); we
			// only report ambiguity, not a cross-language leak (which would be racy).
			basename := strings.ToLower(target)
			candidates := nvs.BasenameMap[basename]
			if len(candidates) > 1 {
				paths := make([]string, len(candidates))
				for i, c := range candidates {
					paths[i] = c.Path
				}
				sort.Strings(paths) // deterministic candidate order
				lines = append(lines, lintLine{
					path: note.Path,
					message: fmt.Sprintf(
						"ambiguous bare wikilink [[%s]]: %d candidates (%s)",
						target, len(candidates), strings.Join(paths, ", "),
					),
					level: model.NoteWarningWarning,
				})
			}

			// Cross-language leak: bare wikilink in an en/ note resolves
			// under ru/ (or vice-versa), keyed on path prefix not frontmatter lang.
			// Only checked when the wikilink is UNAMBIGUOUS (exactly one candidate);
			// ambiguous links are already reported above, and their resolution is
			// non-deterministic (map-order), which would produce a flaky baseline.
			if noteLang != "" && len(candidates) == 1 {
				other := otherLang(noteLang)
				if strings.HasPrefix(permalink, "/"+other+"/") || permalink == "/"+other {
					lines = append(lines, lintLine{
						path: note.Path,
						message: fmt.Sprintf(
							"cross-language wikilink leak: [[%s]] resolves to %s (note lang=%s, link lang=%s)",
							target, permalink, noteLang, other,
						),
						level: model.NoteWarningWarning,
					})
				}
			}
		}
	}

	// --- layout render warnings (from smokeRenderLayouts) ---
	if layouts != nil {
		for _, layout := range layouts.Map {
			for _, lw := range layout.Warnings {
				lines = append(lines, lintLine{
					path:    layout.Path,
					message: lw.Message,
					level:   lw.Level,
				})
			}
		}
	}

	// Sort by path, then message for deterministic output.
	sort.Slice(lines, func(i, j int) bool {
		if lines[i].path != lines[j].path {
			return lines[i].path < lines[j].path
		}
		return lines[i].message < lines[j].message
	})

	return lines, nil
}

// stableSignature returns a tab-separated stable key for a lint line suitable
// for use in a baseline file. It intentionally excludes line numbers so that
// reformatting surrounding content doesn't invalidate the entry.
func stableSignature(l lintLine) string {
	return l.path + "\t" + levelStr(l.level) + "\t" + l.message
}

// loadBaseline reads a baseline file and returns a set of stable signatures.
// If baselineFile is empty or the file does not exist, an empty set is returned.
func loadBaseline(baselineFile string) (map[string]bool, error) {
	if baselineFile == "" {
		return nil, nil
	}
	f, err := os.Open(baselineFile)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("doclint: open baseline: %w", err)
	}
	defer f.Close()

	set := make(map[string]bool)
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		if line != "" {
			set[line] = true
		}
	}
	return set, scanner.Err()
}

// pathLangPrefix returns "en" or "ru" if the relative note path starts with
// that prefix, otherwise "".
func pathLangPrefix(path string) string {
	if strings.HasPrefix(path, "en/") {
		return "en"
	}
	if strings.HasPrefix(path, "ru/") {
		return "ru"
	}
	return ""
}

// otherLang returns the opposite language code for en/ru pairs.
func otherLang(lang string) string {
	switch lang {
	case "en":
		return "ru"
	case "ru":
		return "en"
	}
	return ""
}

// levelStr converts a NoteWarningLevel to its string label.
func levelStr(l model.NoteWarningLevel) string {
	switch l {
	case model.NoteWarningWarning:
		return "warning"
	case model.NoteWarningCritical:
		return "critical"
	default:
		return "info"
	}
}
