package doclint

import (
	"bufio"
	"context"
	"fmt"
	"io"
	"os"
	"sort"
	"strings"

	"trip2g/internal/logger"
	"trip2g/internal/mdloader"
	"trip2g/internal/model"
	"trip2g/internal/noteloader"
)

// Options controls optional behaviour of Run / RunWithOptions.
type Options struct {
	// BaselineFile is the path to a baseline-ratchet file generated by
	// GenerateBaseline. Warnings whose stable signature appears in the
	// baseline are grandfathered (suppressed from output, don't cause exit 1).
	// Empty string means no baseline is applied.
	BaselineFile string
}

// lintLine is a single lint finding collected before printing.
type lintLine struct {
	path    string
	message string
	level   model.NoteWarningLevel
}

// Run runs the DB-free linter over dir, writes sorted results to w and returns
// exit code 1 if any warnings (level >= NoteWarningWarning) were found, 0 if
// only info-level (advisory) findings or none.
// log may be nil (falls back to DummyLogger).
// It is a thin wrapper around RunWithOptions with an empty Options{}.
func Run(ctx context.Context, dir string, w io.Writer, log logger.Logger) (int, error) {
	return RunWithOptions(ctx, dir, w, log, Options{})
}

// RunWithOptions is the full entry-point for the DB-free linter.
// All non-baselined findings are printed; exit code 1 is returned only when at
// least one printed finding has level >= NoteWarningWarning. Info-level
// findings are advisory: they are printed but do not cause a non-zero exit.
func RunWithOptions(ctx context.Context, dir string, w io.Writer, log logger.Logger, opts Options) (int, error) {
	if log == nil {
		log = &logger.DummyLogger{}
	}

	lines, loadErr := collectWarnings(ctx, dir, log)
	if loadErr != nil {
		return 1, loadErr
	}

	baseline, baseErr := loadBaseline(opts.BaselineFile)
	if baseErr != nil {
		return 1, baseErr
	}

	var newLines []lintLine
	for _, line := range lines {
		if !baseline[stableSignature(line)] {
			newLines = append(newLines, line)
		}
	}

	var hasWarning bool
	for _, line := range newLines {
		fmt.Fprintf(w, "%s:0: %s %s\n", line.path, levelStr(line.level), line.message)
		if line.level >= model.NoteWarningWarning {
			hasWarning = true
		}
	}

	// Info-level findings are advisory: printed but do not fail the run.
	if hasWarning {
		return 1, nil
	}
	return 0, nil
}

// GenerateBaseline runs the linter over dir and writes a baseline-ratchet file
// to baselineFile. Each line in the file is the stable signature of one warning
// (relpath\tlevel\tmessage). Existing baselined warnings are replaced entirely.
func GenerateBaseline(ctx context.Context, dir string, baselineFile string, log logger.Logger) error {
	if log == nil {
		log = &logger.DummyLogger{}
	}

	lines, err := collectWarnings(ctx, dir, log)
	if err != nil {
		return err
	}

	f, err := os.Create(baselineFile)
	if err != nil {
		return fmt.Errorf("doclint: create baseline: %w", err)
	}
	defer f.Close()

	for _, line := range lines {
		if _, werr := fmt.Fprintln(f, stableSignature(line)); werr != nil {
			return fmt.Errorf("doclint: write baseline: %w", werr)
		}
	}
	return nil
}

// collectWarnings loads the vault and returns all lint findings, sorted.
func collectWarnings(ctx context.Context, dir string, log logger.Logger) ([]lintLine, error) {
	env := newFsEnv(dir, log)
	ldr := noteloader.New("lint", env, mdloader.Config{})

	if loadErr := ldr.Load(ctx, noteloader.LoadOptions{SkipSearchIndex: true}); loadErr != nil {
		return nil, fmt.Errorf("doclint: load failed: %w", loadErr)
	}

	nvs := ldr.NoteViews()
	layouts := ldr.Layouts()

	var lines []lintLine

	// --- per-note warnings from the loader pipeline ---
	for _, note := range nvs.List {
		for _, nw := range note.Warnings {
			lines = append(lines, lintLine{
				path:    note.Path,
				message: nw.Message,
				level:   nw.Level,
			})
		}

		// --- lint-added checks on ResolvedLinks ---
		noteLang := model.PathLangPrefix(note.Path)

		// Collect targets to iterate in sorted order (map iteration is non-deterministic).
		targets := make([]string, 0, len(note.ResolvedLinks))
		for target := range note.ResolvedLinks {
			targets = append(targets, target)
		}
		sort.Strings(targets)

		for _, target := range targets {
			permalink := note.ResolvedLinks[target]
			// Only bare wikilinks (no path separator) are checked.
			if strings.Contains(target, "/") {
				continue
			}

			// Cross-language leak: bare wikilink in an en/ note resolves
			// under ru/ (or vice-versa), keyed on path prefix not frontmatter lang.
			// The resolver picks bare wikilinks via a deterministic lang-aware
			// ladder (same folder → same language → global shallowest, see
			// model.NoteViews.ResolveWikilinkTarget), so a bare link that still
			// lands under the other language prefix has no same-lang candidate
			// at all — a genuine leak, flagged regardless of candidate count.
			// It usually signals a missing translation.
			if noteLang != "" {
				other := otherLang(noteLang)
				if other != "" && (strings.HasPrefix(permalink, "/"+other+"/") || permalink == "/"+other) {
					lines = append(lines, lintLine{
						path: note.Path,
						message: fmt.Sprintf(
							"cross-language wikilink leak: [[%s]] resolves to %s (note lang=%s, link lang=%s)",
							target, permalink, noteLang, other,
						),
						level: model.NoteWarningWarning,
					})
				}
			}
		}
	}

	// --- layout render warnings (from smokeRenderLayouts) ---
	if layouts != nil {
		for _, layout := range layouts.Map {
			for _, lw := range layout.Warnings {
				lines = append(lines, lintLine{
					path:    layout.Path,
					message: lw.Message,
					level:   lw.Level,
				})
			}
		}
	}

	// Sort by path, then message for deterministic output.
	sort.Slice(lines, func(i, j int) bool {
		if lines[i].path != lines[j].path {
			return lines[i].path < lines[j].path
		}
		return lines[i].message < lines[j].message
	})

	return lines, nil
}

// stableSignature returns a tab-separated stable key for a lint line suitable
// for use in a baseline file. It intentionally excludes line numbers so that
// reformatting surrounding content doesn't invalidate the entry.
func stableSignature(l lintLine) string {
	return l.path + "\t" + levelStr(l.level) + "\t" + l.message
}

// loadBaseline reads a baseline file and returns a set of stable signatures.
// If baselineFile is empty or the file does not exist, an empty set is returned.
func loadBaseline(baselineFile string) (map[string]bool, error) {
	if baselineFile == "" {
		return nil, nil
	}
	f, err := os.Open(baselineFile)
	if os.IsNotExist(err) {
		return nil, nil
	}
	if err != nil {
		return nil, fmt.Errorf("doclint: open baseline: %w", err)
	}
	defer f.Close()

	set := make(map[string]bool)
	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		line := scanner.Text()
		if line != "" {
			set[line] = true
		}
	}
	return set, scanner.Err()
}

// otherLang returns the opposite language code for en/ru pairs.
func otherLang(lang string) string {
	switch lang {
	case "en":
		return "ru"
	case "ru":
		return "en"
	}
	return ""
}

// levelStr converts a NoteWarningLevel to its string label.
func levelStr(l model.NoteWarningLevel) string {
	switch l {
	case model.NoteWarningWarning:
		return "warning"
	case model.NoteWarningCritical:
		return "critical"
	case model.NoteWarningInfo:
		return "info"
	default:
		return "info"
	}
}
