// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type trip2g_admin_telegramaccount_create_step0_startMutationVariables = Exact<{
  input: AdminStartTelegramAccountAuthInput;
}>;


export type trip2g_admin_telegramaccount_create_step0_startMutation = { __typename?: 'Mutation', admin: { __typename?: 'AdminMutation', payload: { __typename: 'AdminStartTelegramAccountAuthPayload', authState: { __typename?: 'AdminTelegramAccountAuthState', phone: string, state: AdminTelegramAccountAuthStateEnum, passwordHint?: string | null } } | { __typename: 'ErrorPayload', message: string } } };


export function $trip2g_admin_telegramaccount_create_step0_start(variables: trip2g_admin_telegramaccount_create_step0_startMutationVariables, opts?: { revalidate?: boolean }): trip2g_admin_telegramaccount_create_step0_startMutation {
	return $trip2g_gql_request(`mutation trip2g_admin_telegramaccount_create_step0_start(\u0024input: AdminStartTelegramAccountAuthInput!) {
  admin {
    payload: startTelegramAccountAuth(input: \u0024input) {
      __typename
      ... on AdminStartTelegramAccountAuthPayload {
        authState {
          phone
          state
          passwordHint
        }
      }
      ... on ErrorPayload {
        message
      }
    }
  }
}`, variables, opts) as trip2g_admin_telegramaccount_create_step0_startMutation
}

}
