// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type trip2g_admin_federation_catalog_listQueryVariables = Exact<{ [key: string]: never; }>;


export type trip2g_admin_federation_catalog_listQuery = { __typename?: 'Query', admin: { __typename?: 'AdminQuery', federationSecrets: Array<{ __typename?: 'AdminFederationSecret', id: any, kid: string, kbUrl?: string | null, description?: string | null, createdAt: any, createdBy: any, revokedAt?: any | null, rotatedAt?: any | null, subgraphCount: any }> } };


export function $trip2g_admin_federation_catalog_list(opts?: { revalidate?: boolean }): trip2g_admin_federation_catalog_listQuery {
	return $trip2g_gql_request(`query trip2g_admin_federation_catalog_list {
  admin {
    federationSecrets {
      id
      kid
      kbUrl
      description
      createdAt
      createdBy
      revokedAt
      rotatedAt
      subgraphCount
    }
  }
}`, undefined, opts) as trip2g_admin_federation_catalog_listQuery
}

}
