// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package federationtopology_test

import (
	"context"
	"sync"
	"trip2g/internal/case/system/federationtopology"
	"trip2g/internal/db"
	"trip2g/internal/model"
)

// Ensure, that EnvMock does implement federationtopology.Env.
// If this is not the case, regenerate this file with moq.
var _ federationtopology.Env = &EnvMock{}

// EnvMock is a mock implementation of federationtopology.Env.
//
//	func TestSomethingThatUsesEnv(t *testing.T) {
//
//		// make and configure a mocked federationtopology.Env
//		mockedEnv := &EnvMock{
//			LatestNoteViewsFunc: func() *model.NoteViews {
//				panic("mock out the LatestNoteViews method")
//			},
//			ListAllFederationSecretScopesFunc: func(ctx context.Context) ([]db.ListAllFederationSecretScopesRow, error) {
//				panic("mock out the ListAllFederationSecretScopes method")
//			},
//			ListAllSubgraphsFunc: func(ctx context.Context) ([]db.Subgraph, error) {
//				panic("mock out the ListAllSubgraphs method")
//			},
//			ListFederationSecretsFunc: func(ctx context.Context) ([]db.ListFederationSecretsRow, error) {
//				panic("mock out the ListFederationSecrets method")
//			},
//			LoadSiteConfigFunc: func(ctx context.Context) (model.SiteConfig, error) {
//				panic("mock out the LoadSiteConfig method")
//			},
//			PublicURLFunc: func() string {
//				panic("mock out the PublicURL method")
//			},
//		}
//
//		// use mockedEnv in code that requires federationtopology.Env
//		// and then make assertions.
//
//	}
type EnvMock struct {
	// LatestNoteViewsFunc mocks the LatestNoteViews method.
	LatestNoteViewsFunc func() *model.NoteViews

	// ListAllFederationSecretScopesFunc mocks the ListAllFederationSecretScopes method.
	ListAllFederationSecretScopesFunc func(ctx context.Context) ([]db.ListAllFederationSecretScopesRow, error)

	// ListAllSubgraphsFunc mocks the ListAllSubgraphs method.
	ListAllSubgraphsFunc func(ctx context.Context) ([]db.Subgraph, error)

	// ListFederationSecretsFunc mocks the ListFederationSecrets method.
	ListFederationSecretsFunc func(ctx context.Context) ([]db.ListFederationSecretsRow, error)

	// LoadSiteConfigFunc mocks the LoadSiteConfig method.
	LoadSiteConfigFunc func(ctx context.Context) (model.SiteConfig, error)

	// PublicURLFunc mocks the PublicURL method.
	PublicURLFunc func() string

	// calls tracks calls to the methods.
	calls struct {
		// LatestNoteViews holds details about calls to the LatestNoteViews method.
		LatestNoteViews []struct {
		}
		// ListAllFederationSecretScopes holds details about calls to the ListAllFederationSecretScopes method.
		ListAllFederationSecretScopes []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListAllSubgraphs holds details about calls to the ListAllSubgraphs method.
		ListAllSubgraphs []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// ListFederationSecrets holds details about calls to the ListFederationSecrets method.
		ListFederationSecrets []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// LoadSiteConfig holds details about calls to the LoadSiteConfig method.
		LoadSiteConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// PublicURL holds details about calls to the PublicURL method.
		PublicURL []struct {
		}
	}
	lockLatestNoteViews               sync.RWMutex
	lockListAllFederationSecretScopes sync.RWMutex
	lockListAllSubgraphs              sync.RWMutex
	lockListFederationSecrets         sync.RWMutex
	lockLoadSiteConfig                sync.RWMutex
	lockPublicURL                     sync.RWMutex
}

// LatestNoteViews calls LatestNoteViewsFunc.
func (mock *EnvMock) LatestNoteViews() *model.NoteViews {
	if mock.LatestNoteViewsFunc == nil {
		panic("EnvMock.LatestNoteViewsFunc: method is nil but Env.LatestNoteViews was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLatestNoteViews.Lock()
	mock.calls.LatestNoteViews = append(mock.calls.LatestNoteViews, callInfo)
	mock.lockLatestNoteViews.Unlock()
	return mock.LatestNoteViewsFunc()
}

// LatestNoteViewsCalls gets all the calls that were made to LatestNoteViews.
// Check the length with:
//
//	len(mockedEnv.LatestNoteViewsCalls())
func (mock *EnvMock) LatestNoteViewsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLatestNoteViews.RLock()
	calls = mock.calls.LatestNoteViews
	mock.lockLatestNoteViews.RUnlock()
	return calls
}

// ListAllFederationSecretScopes calls ListAllFederationSecretScopesFunc.
func (mock *EnvMock) ListAllFederationSecretScopes(ctx context.Context) ([]db.ListAllFederationSecretScopesRow, error) {
	if mock.ListAllFederationSecretScopesFunc == nil {
		panic("EnvMock.ListAllFederationSecretScopesFunc: method is nil but Env.ListAllFederationSecretScopes was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListAllFederationSecretScopes.Lock()
	mock.calls.ListAllFederationSecretScopes = append(mock.calls.ListAllFederationSecretScopes, callInfo)
	mock.lockListAllFederationSecretScopes.Unlock()
	return mock.ListAllFederationSecretScopesFunc(ctx)
}

// ListAllFederationSecretScopesCalls gets all the calls that were made to ListAllFederationSecretScopes.
// Check the length with:
//
//	len(mockedEnv.ListAllFederationSecretScopesCalls())
func (mock *EnvMock) ListAllFederationSecretScopesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListAllFederationSecretScopes.RLock()
	calls = mock.calls.ListAllFederationSecretScopes
	mock.lockListAllFederationSecretScopes.RUnlock()
	return calls
}

// ListAllSubgraphs calls ListAllSubgraphsFunc.
func (mock *EnvMock) ListAllSubgraphs(ctx context.Context) ([]db.Subgraph, error) {
	if mock.ListAllSubgraphsFunc == nil {
		panic("EnvMock.ListAllSubgraphsFunc: method is nil but Env.ListAllSubgraphs was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListAllSubgraphs.Lock()
	mock.calls.ListAllSubgraphs = append(mock.calls.ListAllSubgraphs, callInfo)
	mock.lockListAllSubgraphs.Unlock()
	return mock.ListAllSubgraphsFunc(ctx)
}

// ListAllSubgraphsCalls gets all the calls that were made to ListAllSubgraphs.
// Check the length with:
//
//	len(mockedEnv.ListAllSubgraphsCalls())
func (mock *EnvMock) ListAllSubgraphsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListAllSubgraphs.RLock()
	calls = mock.calls.ListAllSubgraphs
	mock.lockListAllSubgraphs.RUnlock()
	return calls
}

// ListFederationSecrets calls ListFederationSecretsFunc.
func (mock *EnvMock) ListFederationSecrets(ctx context.Context) ([]db.ListFederationSecretsRow, error) {
	if mock.ListFederationSecretsFunc == nil {
		panic("EnvMock.ListFederationSecretsFunc: method is nil but Env.ListFederationSecrets was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListFederationSecrets.Lock()
	mock.calls.ListFederationSecrets = append(mock.calls.ListFederationSecrets, callInfo)
	mock.lockListFederationSecrets.Unlock()
	return mock.ListFederationSecretsFunc(ctx)
}

// ListFederationSecretsCalls gets all the calls that were made to ListFederationSecrets.
// Check the length with:
//
//	len(mockedEnv.ListFederationSecretsCalls())
func (mock *EnvMock) ListFederationSecretsCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListFederationSecrets.RLock()
	calls = mock.calls.ListFederationSecrets
	mock.lockListFederationSecrets.RUnlock()
	return calls
}

// LoadSiteConfig calls LoadSiteConfigFunc.
func (mock *EnvMock) LoadSiteConfig(ctx context.Context) (model.SiteConfig, error) {
	if mock.LoadSiteConfigFunc == nil {
		panic("EnvMock.LoadSiteConfigFunc: method is nil but Env.LoadSiteConfig was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockLoadSiteConfig.Lock()
	mock.calls.LoadSiteConfig = append(mock.calls.LoadSiteConfig, callInfo)
	mock.lockLoadSiteConfig.Unlock()
	return mock.LoadSiteConfigFunc(ctx)
}

// LoadSiteConfigCalls gets all the calls that were made to LoadSiteConfig.
// Check the length with:
//
//	len(mockedEnv.LoadSiteConfigCalls())
func (mock *EnvMock) LoadSiteConfigCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockLoadSiteConfig.RLock()
	calls = mock.calls.LoadSiteConfig
	mock.lockLoadSiteConfig.RUnlock()
	return calls
}

// PublicURL calls PublicURLFunc.
func (mock *EnvMock) PublicURL() string {
	if mock.PublicURLFunc == nil {
		panic("EnvMock.PublicURLFunc: method is nil but Env.PublicURL was just called")
	}
	callInfo := struct {
	}{}
	mock.lockPublicURL.Lock()
	mock.calls.PublicURL = append(mock.calls.PublicURL, callInfo)
	mock.lockPublicURL.Unlock()
	return mock.PublicURLFunc()
}

// PublicURLCalls gets all the calls that were made to PublicURL.
// Check the length with:
//
//	len(mockedEnv.PublicURLCalls())
func (mock *EnvMock) PublicURLCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockPublicURL.RLock()
	calls = mock.calls.PublicURL
	mock.lockPublicURL.RUnlock()
	return calls
}
