// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type trip2g_admin_changewebhook_show_deliveriesQueryVariables = Exact<{
  id: Scalars['Int64']['input'];
}>;


export type trip2g_admin_changewebhook_show_deliveriesQuery = { __typename?: 'Query', admin: { __typename?: 'AdminQuery', changeWebhookDeliveries: { __typename?: 'AdminChangeWebhookDeliveriesConnection', nodes: Array<{ __typename?: 'AdminChangeWebhookDelivery', id: any, status: string, responseStatus?: any | null, attempt: any, durationMs?: any | null, createdAt: any, completedAt?: any | null }> } } };


export function $trip2g_admin_changewebhook_show_deliveries(variables: trip2g_admin_changewebhook_show_deliveriesQueryVariables, opts?: { revalidate?: boolean }): trip2g_admin_changewebhook_show_deliveriesQuery {
	return $trip2g_gql_request(`query trip2g_admin_changewebhook_show_deliveries(\u0024id: Int64!) {
  admin {
    changeWebhookDeliveries(filter: {webhookId: \u0024id, limit: 20}) {
      nodes {
        id
        status
        responseStatus
        attempt
        durationMs
        createdAt
        completedAt
      }
    }
  }
}`, variables, opts) as trip2g_admin_changewebhook_show_deliveriesQuery
}

}
