// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type trip2g_admin_boostycredentials_show_subgraphs_saveMutationVariables = Exact<{
  input: SetBoostyTierSubgraphsInput;
}>;


export type trip2g_admin_boostycredentials_show_subgraphs_saveMutation = { __typename?: 'Mutation', admin: { __typename?: 'AdminMutation', data: { __typename: 'ErrorPayload', message: string } | { __typename: 'SetBoostyTierSubgraphsPayload', success: boolean } } };


export function $trip2g_admin_boostycredentials_show_subgraphs_save(variables: trip2g_admin_boostycredentials_show_subgraphs_saveMutationVariables, opts?: { revalidate?: boolean }): trip2g_admin_boostycredentials_show_subgraphs_saveMutation {
	return $trip2g_gql_request(`mutation trip2g_admin_boostycredentials_show_subgraphs_save(\u0024input: SetBoostyTierSubgraphsInput!) {
  admin {
    data: setBoostyTierSubgraphs(input: \u0024input) {
      __typename
      ... on SetBoostyTierSubgraphsPayload {
        success
      }
      ... on ErrorPayload {
        message
      }
    }
  }
}`, variables, opts) as trip2g_admin_boostycredentials_show_subgraphs_saveMutation
}

}
