// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type trip2g_admin_cronwebhook_update_saveMutationVariables = Exact<{
  input: UpdateCronWebhookInput;
}>;


export type trip2g_admin_cronwebhook_update_saveMutation = { __typename?: 'Mutation', admin: { __typename?: 'AdminMutation', payload: { __typename: 'ErrorPayload', message: string } | { __typename: 'UpdateCronWebhookPayload', cronWebhook: { __typename?: 'AdminCronWebhook', id: any } } } };


export function $trip2g_admin_cronwebhook_update_save(variables: trip2g_admin_cronwebhook_update_saveMutationVariables, opts?: { revalidate?: boolean }): trip2g_admin_cronwebhook_update_saveMutation {
	return $trip2g_gql_request(`mutation trip2g_admin_cronwebhook_update_save(\u0024input: UpdateCronWebhookInput!) {
  admin {
    payload: updateCronWebhook(input: \u0024input) {
      __typename
      ... on UpdateCronWebhookPayload {
        cronWebhook {
          id
        }
      }
      ... on ErrorPayload {
        message
      }
    }
  }
}`, variables, opts) as trip2g_admin_cronwebhook_update_saveMutation
}

}
