// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type TraceHopFragment = { __typename?: 'AdminTraceDelivery', kind: string, id: any, webhookId: any, status: string, responseStatus?: any | null, attempt: any, durationMs?: any | null, createdAt: any, completedAt?: any | null, parentKind?: string | null, parentId?: any | null, depthReached: any, costs: Array<{ __typename?: 'AdminCost', id: string, value: number }>, writes: Array<{ __typename?: 'AdminTraceWrite', path: string, version: any }> } & { ' \u0024fragmentName'?: 'TraceHopFragment' };


/** Data declared by fragment `TraceHop` - spread it anywhere as `...TraceHop`. */
export type $trip2g_admin_deliverytrace_hop_hop = TraceHopFragment

/** Opaque ref to this fragment - a bare name usable where generics don't fit, e.g. a .view.tree property: `<prop> null $trip2g_admin_deliverytrace_hop_hop_ref`. */
export type $trip2g_admin_deliverytrace_hop_hop_ref = $trip2g_gql_ref<TraceHopFragment>

/**
 * Identity accessor: turns an opaque fragment ref (masked parent data) into the typed fragment fields.
 * Preserves the ref's nullability: a non-null ref yields the fragment, a nullable ref (nullable schema
 * field, null list element) yields a nullable fragment - the compiler forces the null branch.
 */
export function $trip2g_admin_deliverytrace_hop_hop_unmask(ref: $trip2g_gql_ref<TraceHopFragment>): TraceHopFragment
export function $trip2g_admin_deliverytrace_hop_hop_unmask(ref: $trip2g_gql_ref<TraceHopFragment> | null | undefined): TraceHopFragment | null | undefined
export function $trip2g_admin_deliverytrace_hop_hop_unmask(ref: $trip2g_gql_ref<TraceHopFragment> | null | undefined): TraceHopFragment | null | undefined {
	return ref as TraceHopFragment | null | undefined
}

/** Checked accessor: unmask that throws on a null/undefined ref - the runtime-checked alternative to TS `!`. */
export function $trip2g_admin_deliverytrace_hop_hop_unmask_not_null(ref: $trip2g_gql_ref<TraceHopFragment> | null | undefined): TraceHopFragment {
	if (ref == null) throw new Error('null fragment ref for TraceHop')
	return ref as TraceHopFragment
}

}
