// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type trip2g_admin_admin_create_createMutationVariables = Exact<{
  input: CreateAdminInput;
}>;


export type trip2g_admin_admin_create_createMutation = { __typename?: 'Mutation', admin: { __typename?: 'AdminMutation', data: { __typename: 'CreateAdminPayload', admin: { __typename?: 'Admin', id: any } } | { __typename: 'ErrorPayload', message: string } } };


export function $trip2g_admin_admin_create_create(variables: trip2g_admin_admin_create_createMutationVariables, opts?: { revalidate?: boolean }): trip2g_admin_admin_create_createMutation {
	return $trip2g_gql_request(`mutation trip2g_admin_admin_create_create(\u0024input: CreateAdminInput!) {
  admin {
    data: createAdmin(input: \u0024input) {
      __typename
      ... on ErrorPayload {
        message
      }
      ... on CreateAdminPayload {
        admin {
          id
        }
      }
    }
  }
}`, variables, opts) as trip2g_admin_admin_create_createMutation
}

}
