#!/bin/sh

scenario="$1"

if [ "$scenario" = "1" ]; then

curl localhost:8081/graphql \
  -F operations='{ "variables": {"input":{"file":null,"noteId":30,"sha256Hash":"7af6955bbf11e55de9bf9c4242905cc24717eb521291fcae93ef4d9fbe8ba70d","path":"/test.png","absolutePath":"/test.png"}}, "query": "mutation($input: UploadNoteAssetInput!) { uploadNoteAsset(input: $input) { ... on ErrorPayload { message } ... on UploadNoteAssetPayload { uploadSkipped } } }" }' \
  -F map='{ "0": ["variables.input.file"] }' \
  -F 0=@./scripts/test.png

elif [ "$scenario" = "2" ]; then

curl localhost:8081/graphql \
  -F operations='{ "variables": {"input":{"file":null,"noteId":30,"sha256Hash":"91ac57a8c62bcd88eb5253a98791f931398bde7d6dd5e3155c453fb658cfe338","path":"/test.png","absolutePath":"/test.png"}}, "query": "mutation($input: UploadNoteAssetInput!) { uploadNoteAsset(input: $input) { ... on ErrorPayload { message } ... on UploadNoteAssetPayload { uploadSkipped } } }" }' \
  -F map='{ "0": ["variables.input.file"] }' \
  -F 0=@./scripts/test2.png

else
  echo "Invalid scenario. Please use 1 or 2."
  exit 1
fi
