#!/usr/bin/env bash
# Vector-search benchmark stack driver.
#
# Subcommands:
#   up     Build + start the isolated stack, auto-provision an API key, push the
#          test vault, and wait for embedding jobs to drain. Idempotent.
#   sync   Re-push the test vault and wait for jobs (after editing testdata/vecbench/vault).
#   eval   Run the retrieval benchmark against the running instance (LABEL, OUT).
#   down   Stop and remove the stack (keeps the embedding model cache).
#   logs   Tail app logs.
#
# Usage:
#   ./scripts/vecbench.sh up
#   ./scripts/vecbench.sh eval baseline-bgem3
#   ./scripts/vecbench.sh down
set -euo pipefail

COMPOSE="docker compose -f docker-compose.vecbench.yml"
APP_URL="http://localhost:21081"
GRAPHQL="$APP_URL/_system/graphql"
COOKIE_NAME="trip2g_vecbench"
OWNER_EMAIL="hello@example.com"
DEV_CODE="111111"
VAULT="testdata/vecbench/vault"
API_KEY_FILE=".vecbench-api-key"

GREEN='\033[0;32m'; RED='\033[0;31m'; NC='\033[0m'

wait_all_jobs() {
  echo "⏳ Waiting for background jobs (embeddings) to drain..."
  curl -s --max-time 300 "$APP_URL/debug/wait_all_jobs" | tee /dev/stderr | grep -q "^ok:" || {
    echo -e "${RED}✗ wait_all_jobs did not return ok${NC}"; exit 1
  }
  sleep 2
}

# wait_graphql_ready polls until the GraphQL endpoint answers a trivial query.
# The TCP port opens slightly before the GraphQL handler is ready, so signing in
# immediately after waitfor can race and fail.
wait_graphql_ready() {
  echo "⏳ Waiting for GraphQL to be ready..."
  for _ in $(seq 1 60); do
    if curl -sf -X POST "$GRAPHQL" -H 'Content-Type: application/json' \
        -d '{"query":"{ __typename }"}' | grep -q '"__typename"'; then
      return 0
    fi
    sleep 1
  done
  echo -e "${RED}✗ GraphQL did not become ready${NC}"; exit 1
}

# reload_app restarts the app so the in-memory note/chunk cache (and the bleve
# index) reload from SQLite. Embeddings are generated by async jobs AFTER the
# vault sync, so the chunks loaded at first boot have no vectors until a reload —
# without this the vector lane returns nothing.
reload_app() {
  echo "🔁 Reloading app to pick up freshly generated embeddings..."
  $COMPOSE restart app >/dev/null
  ./scripts/waitfor localhost:21081 || { echo -e "${RED}✗ app failed to restart${NC}"; exit 1; }
  wait_graphql_ready
}

# get_session_token signs in as the owner (dev code) and echoes a fresh admin
# session-token JWT. Each call requests a new code (codes are single-use).
get_session_token() {
  curl -sf -X POST "$GRAPHQL" -H 'Content-Type: application/json' \
    -d "{\"query\":\"mutation { requestEmailSignInCode(input: { email: \\\"$OWNER_EMAIL\\\" }) { ... on RequestEmailSignInCodePayload { success } } }\"}" > /dev/null
  curl -sf -X POST "$GRAPHQL" -H 'Content-Type: application/json' \
    -d "{\"query\":\"mutation { signInByEmail(input: { email: \\\"$OWNER_EMAIL\\\", code: \\\"$DEV_CODE\\\" }) { ... on SignInPayload { token } } }\"}" \
    | grep -o '"token":"[^"]*"' | cut -d'"' -f4
}

create_api_key() {
  echo "🔑 Signing in (dev code $DEV_CODE) and creating an API key..."
  local TOKEN
  TOKEN=$(get_session_token)
  if [ -z "$TOKEN" ]; then
    echo -e "${RED}✗ Sign-in failed${NC}"; exit 1
  fi

  # Create an API key (admin) using the session cookie.
  local KEY
  KEY=$(curl -sf -X POST "$GRAPHQL" -H 'Content-Type: application/json' \
    -H "Cookie: $COOKIE_NAME=$TOKEN" \
    -d '{"query":"mutation AdminCreateApiKey($input: CreateApiKeyInput!) { admin { createApiKey(input: $input) { ... on ErrorPayload { message } ... on CreateApiKeyPayload { value } } } }","variables":{"input":{"description":"vecbench"}}}' \
    | grep -o '"value":"[^"]*"' | cut -d'"' -f4)
  if [ -z "$KEY" ]; then
    echo -e "${RED}✗ API key creation failed${NC}"; exit 1
  fi
  echo "$KEY" > "$API_KEY_FILE"
  echo -e "${GREEN}✓ API key: ${KEY:0:20}... (saved to $API_KEY_FILE)${NC}"
}

push_vault() {
  local KEY
  KEY=$(cat "$API_KEY_FILE")
  echo "🔄 Pushing test vault $VAULT ..."
  npx tsx obsidian-sync/src/sync/cli/cmd.ts --folder "$VAULT" --api-key "$KEY" --api-url "$GRAPHQL"
}

cmd_up() {
  mkdir -p tmp/vecbench-data
  echo "🚀 Building and starting the vecbench stack..."
  $COMPOSE up -d --no-recreate embedding 2>/dev/null || true
  $COMPOSE up -d --build app minio
  ./scripts/waitfor localhost:21081 || { echo -e "${RED}✗ app failed to start${NC}"; exit 1; }
  wait_graphql_ready
  create_api_key
  # `up` may run against a fresh/wiped DB; a stale obsidian-sync state would make
  # the client think the server already has everything and push nothing. Force a
  # full reconcile by clearing it.
  rm -f "$VAULT/.sync-state.json"
  push_vault
  wait_all_jobs
  reload_app
  echo -e "${GREEN}✓ vecbench up.${NC} GraphQL: $GRAPHQL  | run: ./scripts/vecbench.sh eval baseline"
}

cmd_sync() {
  push_vault
  wait_all_jobs
  reload_app
}

# rebuild rebuilds the app image and recreates the container — for code-only
# changes. Embeddings persist in the DB volume, so no re-sync/re-embed is needed
# (chunks reload from SQLite on boot). Use `sync` instead if vault content changed.
cmd_rebuild() {
  echo "🔨 Rebuilding app image (code change)..."
  # Build/start reranker too (no-op if unchanged); app depends_on it when the
  # reranker feature is enabled. First reranker run downloads the model (~568 MB).
  $COMPOSE up -d --build reranker app
  ./scripts/waitfor localhost:21081 || { echo -e "${RED}✗ app failed to start${NC}"; exit 1; }
  wait_graphql_ready
  echo -e "${GREEN}✓ app rebuilt.${NC}"
}

cmd_eval() {
  local LABEL="${1:-run}"
  local OUT="${2:-docs/superpowers/eval-runs/${LABEL}.json}"
  # Search as admin so the benchmark sees the full (latest) index — anonymous
  # search only returns live notes, and the vault is synced as draft/latest.
  local TOKEN
  TOKEN=$(get_session_token)
  if [ -z "$TOKEN" ]; then
    echo -e "${RED}✗ Could not get admin token for eval${NC}"; exit 1
  fi
  # Authenticate via the session cookie: a session-token JWT sent as a Bearer
  # header is misclassified by the scoped-shortapitoken stamp and yields deny-all
  # in search. The cookie is the reliable admin path.
  go run ./cmd/evalretrieval \
    -golden testdata/eval/golden_set.json \
    -endpoint "$GRAPHQL" \
    -bearer "$TOKEN" \
    -cookie-name "$COOKIE_NAME" \
    -label "$LABEL" -k 10 -out "$OUT" \
    -timeout "${EVAL_TIMEOUT:-5m}" \
    -fail-under-ndcg "${EVAL_MIN_NDCG:-0}"
}

case "${1:-up}" in
  up)      cmd_up ;;
  sync)    cmd_sync ;;
  rebuild) cmd_rebuild ;;
  eval)    shift; cmd_eval "$@" ;;
  down)    $COMPOSE down ;;
  logs)    $COMPOSE logs -f app ;;
  *) echo "usage: $0 {up|sync|rebuild|eval|down|logs}"; exit 1 ;;
esac
