// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package updatetelegrampublishposts_test

import (
	"context"
	"sync"
	"trip2g/internal/case/cronjob/updatetelegrampublishposts"
	"trip2g/internal/logger"
)

// Ensure, that EnvMock does implement updatetelegrampublishposts.Env.
// If this is not the case, regenerate this file with moq.
var _ updatetelegrampublishposts.Env = &EnvMock{}

// EnvMock is a mock implementation of updatetelegrampublishposts.Env.
//
//	func TestSomethingThatUsesEnv(t *testing.T) {
//
//		// make and configure a mocked updatetelegrampublishposts.Env
//		mockedEnv := &EnvMock{
//			ListDistinctChatIDsFromSentMessagesFunc: func(ctx context.Context) ([]int64, error) {
//				panic("mock out the ListDistinctChatIDsFromSentMessages method")
//			},
//			LoggerFunc: func() logger.Logger {
//				panic("mock out the Logger method")
//			},
//			QueueUpdateAllChatTelegramPublishPostsFunc: func(ctx context.Context, chatID int64) error {
//				panic("mock out the QueueUpdateAllChatTelegramPublishPosts method")
//			},
//		}
//
//		// use mockedEnv in code that requires updatetelegrampublishposts.Env
//		// and then make assertions.
//
//	}
type EnvMock struct {
	// ListDistinctChatIDsFromSentMessagesFunc mocks the ListDistinctChatIDsFromSentMessages method.
	ListDistinctChatIDsFromSentMessagesFunc func(ctx context.Context) ([]int64, error)

	// LoggerFunc mocks the Logger method.
	LoggerFunc func() logger.Logger

	// QueueUpdateAllChatTelegramPublishPostsFunc mocks the QueueUpdateAllChatTelegramPublishPosts method.
	QueueUpdateAllChatTelegramPublishPostsFunc func(ctx context.Context, chatID int64) error

	// calls tracks calls to the methods.
	calls struct {
		// ListDistinctChatIDsFromSentMessages holds details about calls to the ListDistinctChatIDsFromSentMessages method.
		ListDistinctChatIDsFromSentMessages []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// Logger holds details about calls to the Logger method.
		Logger []struct {
		}
		// QueueUpdateAllChatTelegramPublishPosts holds details about calls to the QueueUpdateAllChatTelegramPublishPosts method.
		QueueUpdateAllChatTelegramPublishPosts []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChatID is the chatID argument value.
			ChatID int64
		}
	}
	lockListDistinctChatIDsFromSentMessages    sync.RWMutex
	lockLogger                                 sync.RWMutex
	lockQueueUpdateAllChatTelegramPublishPosts sync.RWMutex
}

// ListDistinctChatIDsFromSentMessages calls ListDistinctChatIDsFromSentMessagesFunc.
func (mock *EnvMock) ListDistinctChatIDsFromSentMessages(ctx context.Context) ([]int64, error) {
	if mock.ListDistinctChatIDsFromSentMessagesFunc == nil {
		panic("EnvMock.ListDistinctChatIDsFromSentMessagesFunc: method is nil but Env.ListDistinctChatIDsFromSentMessages was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockListDistinctChatIDsFromSentMessages.Lock()
	mock.calls.ListDistinctChatIDsFromSentMessages = append(mock.calls.ListDistinctChatIDsFromSentMessages, callInfo)
	mock.lockListDistinctChatIDsFromSentMessages.Unlock()
	return mock.ListDistinctChatIDsFromSentMessagesFunc(ctx)
}

// ListDistinctChatIDsFromSentMessagesCalls gets all the calls that were made to ListDistinctChatIDsFromSentMessages.
// Check the length with:
//
//	len(mockedEnv.ListDistinctChatIDsFromSentMessagesCalls())
func (mock *EnvMock) ListDistinctChatIDsFromSentMessagesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockListDistinctChatIDsFromSentMessages.RLock()
	calls = mock.calls.ListDistinctChatIDsFromSentMessages
	mock.lockListDistinctChatIDsFromSentMessages.RUnlock()
	return calls
}

// Logger calls LoggerFunc.
func (mock *EnvMock) Logger() logger.Logger {
	if mock.LoggerFunc == nil {
		panic("EnvMock.LoggerFunc: method is nil but Env.Logger was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLogger.Lock()
	mock.calls.Logger = append(mock.calls.Logger, callInfo)
	mock.lockLogger.Unlock()
	return mock.LoggerFunc()
}

// LoggerCalls gets all the calls that were made to Logger.
// Check the length with:
//
//	len(mockedEnv.LoggerCalls())
func (mock *EnvMock) LoggerCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLogger.RLock()
	calls = mock.calls.Logger
	mock.lockLogger.RUnlock()
	return calls
}

// QueueUpdateAllChatTelegramPublishPosts calls QueueUpdateAllChatTelegramPublishPostsFunc.
func (mock *EnvMock) QueueUpdateAllChatTelegramPublishPosts(ctx context.Context, chatID int64) error {
	if mock.QueueUpdateAllChatTelegramPublishPostsFunc == nil {
		panic("EnvMock.QueueUpdateAllChatTelegramPublishPostsFunc: method is nil but Env.QueueUpdateAllChatTelegramPublishPosts was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ChatID int64
	}{
		Ctx:    ctx,
		ChatID: chatID,
	}
	mock.lockQueueUpdateAllChatTelegramPublishPosts.Lock()
	mock.calls.QueueUpdateAllChatTelegramPublishPosts = append(mock.calls.QueueUpdateAllChatTelegramPublishPosts, callInfo)
	mock.lockQueueUpdateAllChatTelegramPublishPosts.Unlock()
	return mock.QueueUpdateAllChatTelegramPublishPostsFunc(ctx, chatID)
}

// QueueUpdateAllChatTelegramPublishPostsCalls gets all the calls that were made to QueueUpdateAllChatTelegramPublishPosts.
// Check the length with:
//
//	len(mockedEnv.QueueUpdateAllChatTelegramPublishPostsCalls())
func (mock *EnvMock) QueueUpdateAllChatTelegramPublishPostsCalls() []struct {
	Ctx    context.Context
	ChatID int64
} {
	var calls []struct {
		Ctx    context.Context
		ChatID int64
	}
	mock.lockQueueUpdateAllChatTelegramPublishPosts.RLock()
	calls = mock.calls.QueueUpdateAllChatTelegramPublishPosts
	mock.lockQueueUpdateAllChatTelegramPublishPosts.RUnlock()
	return calls
}
