// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package resettelegrampublishnote_test

import (
	"context"
	tgbotapi "github.com/go-telegram-bot-api/telegram-bot-api/v5"
	"sync"
	"trip2g/internal/case/admin/resettelegrampublishnote"
	"trip2g/internal/db"
	"trip2g/internal/logger"
	"trip2g/internal/usertoken"
)

// Ensure, that EnvMock does implement resettelegrampublishnote.Env.
// If this is not the case, regenerate this file with moq.
var _ resettelegrampublishnote.Env = &EnvMock{}

// EnvMock is a mock implementation of resettelegrampublishnote.Env.
//
//	func TestSomethingThatUsesEnv(t *testing.T) {
//
//		// make and configure a mocked resettelegrampublishnote.Env
//		mockedEnv := &EnvMock{
//			CurrentAdminUserTokenFunc: func(ctx context.Context) (*usertoken.Data, error) {
//				panic("mock out the CurrentAdminUserToken method")
//			},
//			DeleteTelegramAccountMessageFunc: func(ctx context.Context, account db.TelegramAccount, chatID int64, messageID int64) error {
//				panic("mock out the DeleteTelegramAccountMessage method")
//			},
//			DeleteTelegramPublishSentAccountMessagesByNotePathIDFunc: func(ctx context.Context, notePathID int64) error {
//				panic("mock out the DeleteTelegramPublishSentAccountMessagesByNotePathID method")
//			},
//			DeleteTelegramPublishSentMessagesByNotePathIDFunc: func(ctx context.Context, notePathID int64) error {
//				panic("mock out the DeleteTelegramPublishSentMessagesByNotePathID method")
//			},
//			GetTelegramAccountByIDFunc: func(ctx context.Context, id int64) (db.TelegramAccount, error) {
//				panic("mock out the GetTelegramAccountByID method")
//			},
//			GetTelegramPublishNoteByNotePathIDFunc: func(ctx context.Context, notePathID int64) (db.TelegramPublishNote, error) {
//				panic("mock out the GetTelegramPublishNoteByNotePathID method")
//			},
//			ListTelegramPublishSentAccountMessagesByNotePathIDFunc: func(ctx context.Context, notePathID int64) ([]db.ListTelegramPublishSentAccountMessagesByNotePathIDRow, error) {
//				panic("mock out the ListTelegramPublishSentAccountMessagesByNotePathID method")
//			},
//			ListTelegramPublishSentMessagesByNotePathIDFunc: func(ctx context.Context, notePathID int64) ([]db.ListTelegramPublishSentMessagesByNotePathIDRow, error) {
//				panic("mock out the ListTelegramPublishSentMessagesByNotePathID method")
//			},
//			LoggerFunc: func() logger.Logger {
//				panic("mock out the Logger method")
//			},
//			ResetTelegramPublishNoteFunc: func(ctx context.Context, notePathID int64) error {
//				panic("mock out the ResetTelegramPublishNote method")
//			},
//			SendTelegramRequestFunc: func(ctx context.Context, chatID int64, msg tgbotapi.Chattable) error {
//				panic("mock out the SendTelegramRequest method")
//			},
//		}
//
//		// use mockedEnv in code that requires resettelegrampublishnote.Env
//		// and then make assertions.
//
//	}
type EnvMock struct {
	// CurrentAdminUserTokenFunc mocks the CurrentAdminUserToken method.
	CurrentAdminUserTokenFunc func(ctx context.Context) (*usertoken.Data, error)

	// DeleteTelegramAccountMessageFunc mocks the DeleteTelegramAccountMessage method.
	DeleteTelegramAccountMessageFunc func(ctx context.Context, account db.TelegramAccount, chatID int64, messageID int64) error

	// DeleteTelegramPublishSentAccountMessagesByNotePathIDFunc mocks the DeleteTelegramPublishSentAccountMessagesByNotePathID method.
	DeleteTelegramPublishSentAccountMessagesByNotePathIDFunc func(ctx context.Context, notePathID int64) error

	// DeleteTelegramPublishSentMessagesByNotePathIDFunc mocks the DeleteTelegramPublishSentMessagesByNotePathID method.
	DeleteTelegramPublishSentMessagesByNotePathIDFunc func(ctx context.Context, notePathID int64) error

	// GetTelegramAccountByIDFunc mocks the GetTelegramAccountByID method.
	GetTelegramAccountByIDFunc func(ctx context.Context, id int64) (db.TelegramAccount, error)

	// GetTelegramPublishNoteByNotePathIDFunc mocks the GetTelegramPublishNoteByNotePathID method.
	GetTelegramPublishNoteByNotePathIDFunc func(ctx context.Context, notePathID int64) (db.TelegramPublishNote, error)

	// ListTelegramPublishSentAccountMessagesByNotePathIDFunc mocks the ListTelegramPublishSentAccountMessagesByNotePathID method.
	ListTelegramPublishSentAccountMessagesByNotePathIDFunc func(ctx context.Context, notePathID int64) ([]db.ListTelegramPublishSentAccountMessagesByNotePathIDRow, error)

	// ListTelegramPublishSentMessagesByNotePathIDFunc mocks the ListTelegramPublishSentMessagesByNotePathID method.
	ListTelegramPublishSentMessagesByNotePathIDFunc func(ctx context.Context, notePathID int64) ([]db.ListTelegramPublishSentMessagesByNotePathIDRow, error)

	// LoggerFunc mocks the Logger method.
	LoggerFunc func() logger.Logger

	// ResetTelegramPublishNoteFunc mocks the ResetTelegramPublishNote method.
	ResetTelegramPublishNoteFunc func(ctx context.Context, notePathID int64) error

	// SendTelegramRequestFunc mocks the SendTelegramRequest method.
	SendTelegramRequestFunc func(ctx context.Context, chatID int64, msg tgbotapi.Chattable) error

	// calls tracks calls to the methods.
	calls struct {
		// CurrentAdminUserToken holds details about calls to the CurrentAdminUserToken method.
		CurrentAdminUserToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// DeleteTelegramAccountMessage holds details about calls to the DeleteTelegramAccountMessage method.
		DeleteTelegramAccountMessage []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Account is the account argument value.
			Account db.TelegramAccount
			// ChatID is the chatID argument value.
			ChatID int64
			// MessageID is the messageID argument value.
			MessageID int64
		}
		// DeleteTelegramPublishSentAccountMessagesByNotePathID holds details about calls to the DeleteTelegramPublishSentAccountMessagesByNotePathID method.
		DeleteTelegramPublishSentAccountMessagesByNotePathID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// NotePathID is the notePathID argument value.
			NotePathID int64
		}
		// DeleteTelegramPublishSentMessagesByNotePathID holds details about calls to the DeleteTelegramPublishSentMessagesByNotePathID method.
		DeleteTelegramPublishSentMessagesByNotePathID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// NotePathID is the notePathID argument value.
			NotePathID int64
		}
		// GetTelegramAccountByID holds details about calls to the GetTelegramAccountByID method.
		GetTelegramAccountByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// GetTelegramPublishNoteByNotePathID holds details about calls to the GetTelegramPublishNoteByNotePathID method.
		GetTelegramPublishNoteByNotePathID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// NotePathID is the notePathID argument value.
			NotePathID int64
		}
		// ListTelegramPublishSentAccountMessagesByNotePathID holds details about calls to the ListTelegramPublishSentAccountMessagesByNotePathID method.
		ListTelegramPublishSentAccountMessagesByNotePathID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// NotePathID is the notePathID argument value.
			NotePathID int64
		}
		// ListTelegramPublishSentMessagesByNotePathID holds details about calls to the ListTelegramPublishSentMessagesByNotePathID method.
		ListTelegramPublishSentMessagesByNotePathID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// NotePathID is the notePathID argument value.
			NotePathID int64
		}
		// Logger holds details about calls to the Logger method.
		Logger []struct {
		}
		// ResetTelegramPublishNote holds details about calls to the ResetTelegramPublishNote method.
		ResetTelegramPublishNote []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// NotePathID is the notePathID argument value.
			NotePathID int64
		}
		// SendTelegramRequest holds details about calls to the SendTelegramRequest method.
		SendTelegramRequest []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ChatID is the chatID argument value.
			ChatID int64
			// Msg is the msg argument value.
			Msg tgbotapi.Chattable
		}
	}
	lockCurrentAdminUserToken                                sync.RWMutex
	lockDeleteTelegramAccountMessage                         sync.RWMutex
	lockDeleteTelegramPublishSentAccountMessagesByNotePathID sync.RWMutex
	lockDeleteTelegramPublishSentMessagesByNotePathID        sync.RWMutex
	lockGetTelegramAccountByID                               sync.RWMutex
	lockGetTelegramPublishNoteByNotePathID                   sync.RWMutex
	lockListTelegramPublishSentAccountMessagesByNotePathID   sync.RWMutex
	lockListTelegramPublishSentMessagesByNotePathID          sync.RWMutex
	lockLogger                                               sync.RWMutex
	lockResetTelegramPublishNote                             sync.RWMutex
	lockSendTelegramRequest                                  sync.RWMutex
}

// CurrentAdminUserToken calls CurrentAdminUserTokenFunc.
func (mock *EnvMock) CurrentAdminUserToken(ctx context.Context) (*usertoken.Data, error) {
	if mock.CurrentAdminUserTokenFunc == nil {
		panic("EnvMock.CurrentAdminUserTokenFunc: method is nil but Env.CurrentAdminUserToken was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCurrentAdminUserToken.Lock()
	mock.calls.CurrentAdminUserToken = append(mock.calls.CurrentAdminUserToken, callInfo)
	mock.lockCurrentAdminUserToken.Unlock()
	return mock.CurrentAdminUserTokenFunc(ctx)
}

// CurrentAdminUserTokenCalls gets all the calls that were made to CurrentAdminUserToken.
// Check the length with:
//
//	len(mockedEnv.CurrentAdminUserTokenCalls())
func (mock *EnvMock) CurrentAdminUserTokenCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCurrentAdminUserToken.RLock()
	calls = mock.calls.CurrentAdminUserToken
	mock.lockCurrentAdminUserToken.RUnlock()
	return calls
}

// DeleteTelegramAccountMessage calls DeleteTelegramAccountMessageFunc.
func (mock *EnvMock) DeleteTelegramAccountMessage(ctx context.Context, account db.TelegramAccount, chatID int64, messageID int64) error {
	if mock.DeleteTelegramAccountMessageFunc == nil {
		panic("EnvMock.DeleteTelegramAccountMessageFunc: method is nil but Env.DeleteTelegramAccountMessage was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		Account   db.TelegramAccount
		ChatID    int64
		MessageID int64
	}{
		Ctx:       ctx,
		Account:   account,
		ChatID:    chatID,
		MessageID: messageID,
	}
	mock.lockDeleteTelegramAccountMessage.Lock()
	mock.calls.DeleteTelegramAccountMessage = append(mock.calls.DeleteTelegramAccountMessage, callInfo)
	mock.lockDeleteTelegramAccountMessage.Unlock()
	return mock.DeleteTelegramAccountMessageFunc(ctx, account, chatID, messageID)
}

// DeleteTelegramAccountMessageCalls gets all the calls that were made to DeleteTelegramAccountMessage.
// Check the length with:
//
//	len(mockedEnv.DeleteTelegramAccountMessageCalls())
func (mock *EnvMock) DeleteTelegramAccountMessageCalls() []struct {
	Ctx       context.Context
	Account   db.TelegramAccount
	ChatID    int64
	MessageID int64
} {
	var calls []struct {
		Ctx       context.Context
		Account   db.TelegramAccount
		ChatID    int64
		MessageID int64
	}
	mock.lockDeleteTelegramAccountMessage.RLock()
	calls = mock.calls.DeleteTelegramAccountMessage
	mock.lockDeleteTelegramAccountMessage.RUnlock()
	return calls
}

// DeleteTelegramPublishSentAccountMessagesByNotePathID calls DeleteTelegramPublishSentAccountMessagesByNotePathIDFunc.
func (mock *EnvMock) DeleteTelegramPublishSentAccountMessagesByNotePathID(ctx context.Context, notePathID int64) error {
	if mock.DeleteTelegramPublishSentAccountMessagesByNotePathIDFunc == nil {
		panic("EnvMock.DeleteTelegramPublishSentAccountMessagesByNotePathIDFunc: method is nil but Env.DeleteTelegramPublishSentAccountMessagesByNotePathID was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		NotePathID int64
	}{
		Ctx:        ctx,
		NotePathID: notePathID,
	}
	mock.lockDeleteTelegramPublishSentAccountMessagesByNotePathID.Lock()
	mock.calls.DeleteTelegramPublishSentAccountMessagesByNotePathID = append(mock.calls.DeleteTelegramPublishSentAccountMessagesByNotePathID, callInfo)
	mock.lockDeleteTelegramPublishSentAccountMessagesByNotePathID.Unlock()
	return mock.DeleteTelegramPublishSentAccountMessagesByNotePathIDFunc(ctx, notePathID)
}

// DeleteTelegramPublishSentAccountMessagesByNotePathIDCalls gets all the calls that were made to DeleteTelegramPublishSentAccountMessagesByNotePathID.
// Check the length with:
//
//	len(mockedEnv.DeleteTelegramPublishSentAccountMessagesByNotePathIDCalls())
func (mock *EnvMock) DeleteTelegramPublishSentAccountMessagesByNotePathIDCalls() []struct {
	Ctx        context.Context
	NotePathID int64
} {
	var calls []struct {
		Ctx        context.Context
		NotePathID int64
	}
	mock.lockDeleteTelegramPublishSentAccountMessagesByNotePathID.RLock()
	calls = mock.calls.DeleteTelegramPublishSentAccountMessagesByNotePathID
	mock.lockDeleteTelegramPublishSentAccountMessagesByNotePathID.RUnlock()
	return calls
}

// DeleteTelegramPublishSentMessagesByNotePathID calls DeleteTelegramPublishSentMessagesByNotePathIDFunc.
func (mock *EnvMock) DeleteTelegramPublishSentMessagesByNotePathID(ctx context.Context, notePathID int64) error {
	if mock.DeleteTelegramPublishSentMessagesByNotePathIDFunc == nil {
		panic("EnvMock.DeleteTelegramPublishSentMessagesByNotePathIDFunc: method is nil but Env.DeleteTelegramPublishSentMessagesByNotePathID was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		NotePathID int64
	}{
		Ctx:        ctx,
		NotePathID: notePathID,
	}
	mock.lockDeleteTelegramPublishSentMessagesByNotePathID.Lock()
	mock.calls.DeleteTelegramPublishSentMessagesByNotePathID = append(mock.calls.DeleteTelegramPublishSentMessagesByNotePathID, callInfo)
	mock.lockDeleteTelegramPublishSentMessagesByNotePathID.Unlock()
	return mock.DeleteTelegramPublishSentMessagesByNotePathIDFunc(ctx, notePathID)
}

// DeleteTelegramPublishSentMessagesByNotePathIDCalls gets all the calls that were made to DeleteTelegramPublishSentMessagesByNotePathID.
// Check the length with:
//
//	len(mockedEnv.DeleteTelegramPublishSentMessagesByNotePathIDCalls())
func (mock *EnvMock) DeleteTelegramPublishSentMessagesByNotePathIDCalls() []struct {
	Ctx        context.Context
	NotePathID int64
} {
	var calls []struct {
		Ctx        context.Context
		NotePathID int64
	}
	mock.lockDeleteTelegramPublishSentMessagesByNotePathID.RLock()
	calls = mock.calls.DeleteTelegramPublishSentMessagesByNotePathID
	mock.lockDeleteTelegramPublishSentMessagesByNotePathID.RUnlock()
	return calls
}

// GetTelegramAccountByID calls GetTelegramAccountByIDFunc.
func (mock *EnvMock) GetTelegramAccountByID(ctx context.Context, id int64) (db.TelegramAccount, error) {
	if mock.GetTelegramAccountByIDFunc == nil {
		panic("EnvMock.GetTelegramAccountByIDFunc: method is nil but Env.GetTelegramAccountByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockGetTelegramAccountByID.Lock()
	mock.calls.GetTelegramAccountByID = append(mock.calls.GetTelegramAccountByID, callInfo)
	mock.lockGetTelegramAccountByID.Unlock()
	return mock.GetTelegramAccountByIDFunc(ctx, id)
}

// GetTelegramAccountByIDCalls gets all the calls that were made to GetTelegramAccountByID.
// Check the length with:
//
//	len(mockedEnv.GetTelegramAccountByIDCalls())
func (mock *EnvMock) GetTelegramAccountByIDCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockGetTelegramAccountByID.RLock()
	calls = mock.calls.GetTelegramAccountByID
	mock.lockGetTelegramAccountByID.RUnlock()
	return calls
}

// GetTelegramPublishNoteByNotePathID calls GetTelegramPublishNoteByNotePathIDFunc.
func (mock *EnvMock) GetTelegramPublishNoteByNotePathID(ctx context.Context, notePathID int64) (db.TelegramPublishNote, error) {
	if mock.GetTelegramPublishNoteByNotePathIDFunc == nil {
		panic("EnvMock.GetTelegramPublishNoteByNotePathIDFunc: method is nil but Env.GetTelegramPublishNoteByNotePathID was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		NotePathID int64
	}{
		Ctx:        ctx,
		NotePathID: notePathID,
	}
	mock.lockGetTelegramPublishNoteByNotePathID.Lock()
	mock.calls.GetTelegramPublishNoteByNotePathID = append(mock.calls.GetTelegramPublishNoteByNotePathID, callInfo)
	mock.lockGetTelegramPublishNoteByNotePathID.Unlock()
	return mock.GetTelegramPublishNoteByNotePathIDFunc(ctx, notePathID)
}

// GetTelegramPublishNoteByNotePathIDCalls gets all the calls that were made to GetTelegramPublishNoteByNotePathID.
// Check the length with:
//
//	len(mockedEnv.GetTelegramPublishNoteByNotePathIDCalls())
func (mock *EnvMock) GetTelegramPublishNoteByNotePathIDCalls() []struct {
	Ctx        context.Context
	NotePathID int64
} {
	var calls []struct {
		Ctx        context.Context
		NotePathID int64
	}
	mock.lockGetTelegramPublishNoteByNotePathID.RLock()
	calls = mock.calls.GetTelegramPublishNoteByNotePathID
	mock.lockGetTelegramPublishNoteByNotePathID.RUnlock()
	return calls
}

// ListTelegramPublishSentAccountMessagesByNotePathID calls ListTelegramPublishSentAccountMessagesByNotePathIDFunc.
func (mock *EnvMock) ListTelegramPublishSentAccountMessagesByNotePathID(ctx context.Context, notePathID int64) ([]db.ListTelegramPublishSentAccountMessagesByNotePathIDRow, error) {
	if mock.ListTelegramPublishSentAccountMessagesByNotePathIDFunc == nil {
		panic("EnvMock.ListTelegramPublishSentAccountMessagesByNotePathIDFunc: method is nil but Env.ListTelegramPublishSentAccountMessagesByNotePathID was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		NotePathID int64
	}{
		Ctx:        ctx,
		NotePathID: notePathID,
	}
	mock.lockListTelegramPublishSentAccountMessagesByNotePathID.Lock()
	mock.calls.ListTelegramPublishSentAccountMessagesByNotePathID = append(mock.calls.ListTelegramPublishSentAccountMessagesByNotePathID, callInfo)
	mock.lockListTelegramPublishSentAccountMessagesByNotePathID.Unlock()
	return mock.ListTelegramPublishSentAccountMessagesByNotePathIDFunc(ctx, notePathID)
}

// ListTelegramPublishSentAccountMessagesByNotePathIDCalls gets all the calls that were made to ListTelegramPublishSentAccountMessagesByNotePathID.
// Check the length with:
//
//	len(mockedEnv.ListTelegramPublishSentAccountMessagesByNotePathIDCalls())
func (mock *EnvMock) ListTelegramPublishSentAccountMessagesByNotePathIDCalls() []struct {
	Ctx        context.Context
	NotePathID int64
} {
	var calls []struct {
		Ctx        context.Context
		NotePathID int64
	}
	mock.lockListTelegramPublishSentAccountMessagesByNotePathID.RLock()
	calls = mock.calls.ListTelegramPublishSentAccountMessagesByNotePathID
	mock.lockListTelegramPublishSentAccountMessagesByNotePathID.RUnlock()
	return calls
}

// ListTelegramPublishSentMessagesByNotePathID calls ListTelegramPublishSentMessagesByNotePathIDFunc.
func (mock *EnvMock) ListTelegramPublishSentMessagesByNotePathID(ctx context.Context, notePathID int64) ([]db.ListTelegramPublishSentMessagesByNotePathIDRow, error) {
	if mock.ListTelegramPublishSentMessagesByNotePathIDFunc == nil {
		panic("EnvMock.ListTelegramPublishSentMessagesByNotePathIDFunc: method is nil but Env.ListTelegramPublishSentMessagesByNotePathID was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		NotePathID int64
	}{
		Ctx:        ctx,
		NotePathID: notePathID,
	}
	mock.lockListTelegramPublishSentMessagesByNotePathID.Lock()
	mock.calls.ListTelegramPublishSentMessagesByNotePathID = append(mock.calls.ListTelegramPublishSentMessagesByNotePathID, callInfo)
	mock.lockListTelegramPublishSentMessagesByNotePathID.Unlock()
	return mock.ListTelegramPublishSentMessagesByNotePathIDFunc(ctx, notePathID)
}

// ListTelegramPublishSentMessagesByNotePathIDCalls gets all the calls that were made to ListTelegramPublishSentMessagesByNotePathID.
// Check the length with:
//
//	len(mockedEnv.ListTelegramPublishSentMessagesByNotePathIDCalls())
func (mock *EnvMock) ListTelegramPublishSentMessagesByNotePathIDCalls() []struct {
	Ctx        context.Context
	NotePathID int64
} {
	var calls []struct {
		Ctx        context.Context
		NotePathID int64
	}
	mock.lockListTelegramPublishSentMessagesByNotePathID.RLock()
	calls = mock.calls.ListTelegramPublishSentMessagesByNotePathID
	mock.lockListTelegramPublishSentMessagesByNotePathID.RUnlock()
	return calls
}

// Logger calls LoggerFunc.
func (mock *EnvMock) Logger() logger.Logger {
	if mock.LoggerFunc == nil {
		panic("EnvMock.LoggerFunc: method is nil but Env.Logger was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLogger.Lock()
	mock.calls.Logger = append(mock.calls.Logger, callInfo)
	mock.lockLogger.Unlock()
	return mock.LoggerFunc()
}

// LoggerCalls gets all the calls that were made to Logger.
// Check the length with:
//
//	len(mockedEnv.LoggerCalls())
func (mock *EnvMock) LoggerCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLogger.RLock()
	calls = mock.calls.Logger
	mock.lockLogger.RUnlock()
	return calls
}

// ResetTelegramPublishNote calls ResetTelegramPublishNoteFunc.
func (mock *EnvMock) ResetTelegramPublishNote(ctx context.Context, notePathID int64) error {
	if mock.ResetTelegramPublishNoteFunc == nil {
		panic("EnvMock.ResetTelegramPublishNoteFunc: method is nil but Env.ResetTelegramPublishNote was just called")
	}
	callInfo := struct {
		Ctx        context.Context
		NotePathID int64
	}{
		Ctx:        ctx,
		NotePathID: notePathID,
	}
	mock.lockResetTelegramPublishNote.Lock()
	mock.calls.ResetTelegramPublishNote = append(mock.calls.ResetTelegramPublishNote, callInfo)
	mock.lockResetTelegramPublishNote.Unlock()
	return mock.ResetTelegramPublishNoteFunc(ctx, notePathID)
}

// ResetTelegramPublishNoteCalls gets all the calls that were made to ResetTelegramPublishNote.
// Check the length with:
//
//	len(mockedEnv.ResetTelegramPublishNoteCalls())
func (mock *EnvMock) ResetTelegramPublishNoteCalls() []struct {
	Ctx        context.Context
	NotePathID int64
} {
	var calls []struct {
		Ctx        context.Context
		NotePathID int64
	}
	mock.lockResetTelegramPublishNote.RLock()
	calls = mock.calls.ResetTelegramPublishNote
	mock.lockResetTelegramPublishNote.RUnlock()
	return calls
}

// SendTelegramRequest calls SendTelegramRequestFunc.
func (mock *EnvMock) SendTelegramRequest(ctx context.Context, chatID int64, msg tgbotapi.Chattable) error {
	if mock.SendTelegramRequestFunc == nil {
		panic("EnvMock.SendTelegramRequestFunc: method is nil but Env.SendTelegramRequest was just called")
	}
	callInfo := struct {
		Ctx    context.Context
		ChatID int64
		Msg    tgbotapi.Chattable
	}{
		Ctx:    ctx,
		ChatID: chatID,
		Msg:    msg,
	}
	mock.lockSendTelegramRequest.Lock()
	mock.calls.SendTelegramRequest = append(mock.calls.SendTelegramRequest, callInfo)
	mock.lockSendTelegramRequest.Unlock()
	return mock.SendTelegramRequestFunc(ctx, chatID, msg)
}

// SendTelegramRequestCalls gets all the calls that were made to SendTelegramRequest.
// Check the length with:
//
//	len(mockedEnv.SendTelegramRequestCalls())
func (mock *EnvMock) SendTelegramRequestCalls() []struct {
	Ctx    context.Context
	ChatID int64
	Msg    tgbotapi.Chattable
} {
	var calls []struct {
		Ctx    context.Context
		ChatID int64
		Msg    tgbotapi.Chattable
	}
	mock.lockSendTelegramRequest.RLock()
	calls = mock.calls.SendTelegramRequest
	mock.lockSendTelegramRequest.RUnlock()
	return calls
}
