// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package setapikeymcpadmintools_test

import (
	"context"
	"sync"
	"trip2g/internal/case/admin/setapikeymcpadmintools"
	"trip2g/internal/db"
	"trip2g/internal/usertoken"
)

// Ensure, that EnvMock does implement setapikeymcpadmintools.Env.
// If this is not the case, regenerate this file with moq.
var _ setapikeymcpadmintools.Env = &EnvMock{}

// EnvMock is a mock implementation of setapikeymcpadmintools.Env.
//
//	func TestSomethingThatUsesEnv(t *testing.T) {
//
//		// make and configure a mocked setapikeymcpadmintools.Env
//		mockedEnv := &EnvMock{
//			ApiKeyByIDFunc: func(ctx context.Context, id int64) (db.ApiKey, error) {
//				panic("mock out the ApiKeyByID method")
//			},
//			CurrentAdminUserTokenFunc: func(ctx context.Context) (*usertoken.Data, error) {
//				panic("mock out the CurrentAdminUserToken method")
//			},
//			SetApiKeyMcpAdminToolsFunc: func(ctx context.Context, arg db.SetApiKeyMcpAdminToolsParams) error {
//				panic("mock out the SetApiKeyMcpAdminTools method")
//			},
//		}
//
//		// use mockedEnv in code that requires setapikeymcpadmintools.Env
//		// and then make assertions.
//
//	}
type EnvMock struct {
	// ApiKeyByIDFunc mocks the ApiKeyByID method.
	ApiKeyByIDFunc func(ctx context.Context, id int64) (db.ApiKey, error)

	// CurrentAdminUserTokenFunc mocks the CurrentAdminUserToken method.
	CurrentAdminUserTokenFunc func(ctx context.Context) (*usertoken.Data, error)

	// SetApiKeyMcpAdminToolsFunc mocks the SetApiKeyMcpAdminTools method.
	SetApiKeyMcpAdminToolsFunc func(ctx context.Context, arg db.SetApiKeyMcpAdminToolsParams) error

	// calls tracks calls to the methods.
	calls struct {
		// ApiKeyByID holds details about calls to the ApiKeyByID method.
		ApiKeyByID []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// ID is the id argument value.
			ID int64
		}
		// CurrentAdminUserToken holds details about calls to the CurrentAdminUserToken method.
		CurrentAdminUserToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// SetApiKeyMcpAdminTools holds details about calls to the SetApiKeyMcpAdminTools method.
		SetApiKeyMcpAdminTools []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.SetApiKeyMcpAdminToolsParams
		}
	}
	lockApiKeyByID             sync.RWMutex
	lockCurrentAdminUserToken  sync.RWMutex
	lockSetApiKeyMcpAdminTools sync.RWMutex
}

// ApiKeyByID calls ApiKeyByIDFunc.
func (mock *EnvMock) ApiKeyByID(ctx context.Context, id int64) (db.ApiKey, error) {
	if mock.ApiKeyByIDFunc == nil {
		panic("EnvMock.ApiKeyByIDFunc: method is nil but Env.ApiKeyByID was just called")
	}
	callInfo := struct {
		Ctx context.Context
		ID  int64
	}{
		Ctx: ctx,
		ID:  id,
	}
	mock.lockApiKeyByID.Lock()
	mock.calls.ApiKeyByID = append(mock.calls.ApiKeyByID, callInfo)
	mock.lockApiKeyByID.Unlock()
	return mock.ApiKeyByIDFunc(ctx, id)
}

// ApiKeyByIDCalls gets all the calls that were made to ApiKeyByID.
// Check the length with:
//
//	len(mockedEnv.ApiKeyByIDCalls())
func (mock *EnvMock) ApiKeyByIDCalls() []struct {
	Ctx context.Context
	ID  int64
} {
	var calls []struct {
		Ctx context.Context
		ID  int64
	}
	mock.lockApiKeyByID.RLock()
	calls = mock.calls.ApiKeyByID
	mock.lockApiKeyByID.RUnlock()
	return calls
}

// CurrentAdminUserToken calls CurrentAdminUserTokenFunc.
func (mock *EnvMock) CurrentAdminUserToken(ctx context.Context) (*usertoken.Data, error) {
	if mock.CurrentAdminUserTokenFunc == nil {
		panic("EnvMock.CurrentAdminUserTokenFunc: method is nil but Env.CurrentAdminUserToken was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCurrentAdminUserToken.Lock()
	mock.calls.CurrentAdminUserToken = append(mock.calls.CurrentAdminUserToken, callInfo)
	mock.lockCurrentAdminUserToken.Unlock()
	return mock.CurrentAdminUserTokenFunc(ctx)
}

// CurrentAdminUserTokenCalls gets all the calls that were made to CurrentAdminUserToken.
// Check the length with:
//
//	len(mockedEnv.CurrentAdminUserTokenCalls())
func (mock *EnvMock) CurrentAdminUserTokenCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCurrentAdminUserToken.RLock()
	calls = mock.calls.CurrentAdminUserToken
	mock.lockCurrentAdminUserToken.RUnlock()
	return calls
}

// SetApiKeyMcpAdminTools calls SetApiKeyMcpAdminToolsFunc.
func (mock *EnvMock) SetApiKeyMcpAdminTools(ctx context.Context, arg db.SetApiKeyMcpAdminToolsParams) error {
	if mock.SetApiKeyMcpAdminToolsFunc == nil {
		panic("EnvMock.SetApiKeyMcpAdminToolsFunc: method is nil but Env.SetApiKeyMcpAdminTools was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.SetApiKeyMcpAdminToolsParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockSetApiKeyMcpAdminTools.Lock()
	mock.calls.SetApiKeyMcpAdminTools = append(mock.calls.SetApiKeyMcpAdminTools, callInfo)
	mock.lockSetApiKeyMcpAdminTools.Unlock()
	return mock.SetApiKeyMcpAdminToolsFunc(ctx, arg)
}

// SetApiKeyMcpAdminToolsCalls gets all the calls that were made to SetApiKeyMcpAdminTools.
// Check the length with:
//
//	len(mockedEnv.SetApiKeyMcpAdminToolsCalls())
func (mock *EnvMock) SetApiKeyMcpAdminToolsCalls() []struct {
	Ctx context.Context
	Arg db.SetApiKeyMcpAdminToolsParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.SetApiKeyMcpAdminToolsParams
	}
	mock.lockSetApiKeyMcpAdminTools.RLock()
	calls = mock.calls.SetApiKeyMcpAdminTools
	mock.lockSetApiKeyMcpAdminTools.RUnlock()
	return calls
}
