// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package createoutboundfederationsecret_test

import (
	"context"
	"sync"
	"trip2g/internal/case/admin/createoutboundfederationsecret"
	"trip2g/internal/db"
	"trip2g/internal/usertoken"
)

// Ensure, that EnvMock does implement createoutboundfederationsecret.Env.
// If this is not the case, regenerate this file with moq.
var _ createoutboundfederationsecret.Env = &EnvMock{}

// EnvMock is a mock implementation of createoutboundfederationsecret.Env.
//
//	func TestSomethingThatUsesEnv(t *testing.T) {
//
//		// make and configure a mocked createoutboundfederationsecret.Env
//		mockedEnv := &EnvMock{
//			CurrentAdminUserTokenFunc: func(ctx context.Context) (*usertoken.Data, error) {
//				panic("mock out the CurrentAdminUserToken method")
//			},
//			EncryptDataFunc: func(plaintext []byte) ([]byte, error) {
//				panic("mock out the EncryptData method")
//			},
//			InsertFederationSecretFunc: func(ctx context.Context, arg db.InsertFederationSecretParams) (db.FederationSecret, error) {
//				panic("mock out the InsertFederationSecret method")
//			},
//		}
//
//		// use mockedEnv in code that requires createoutboundfederationsecret.Env
//		// and then make assertions.
//
//	}
type EnvMock struct {
	// CurrentAdminUserTokenFunc mocks the CurrentAdminUserToken method.
	CurrentAdminUserTokenFunc func(ctx context.Context) (*usertoken.Data, error)

	// EncryptDataFunc mocks the EncryptData method.
	EncryptDataFunc func(plaintext []byte) ([]byte, error)

	// InsertFederationSecretFunc mocks the InsertFederationSecret method.
	InsertFederationSecretFunc func(ctx context.Context, arg db.InsertFederationSecretParams) (db.FederationSecret, error)

	// calls tracks calls to the methods.
	calls struct {
		// CurrentAdminUserToken holds details about calls to the CurrentAdminUserToken method.
		CurrentAdminUserToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// EncryptData holds details about calls to the EncryptData method.
		EncryptData []struct {
			// Plaintext is the plaintext argument value.
			Plaintext []byte
		}
		// InsertFederationSecret holds details about calls to the InsertFederationSecret method.
		InsertFederationSecret []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.InsertFederationSecretParams
		}
	}
	lockCurrentAdminUserToken  sync.RWMutex
	lockEncryptData            sync.RWMutex
	lockInsertFederationSecret sync.RWMutex
}

// CurrentAdminUserToken calls CurrentAdminUserTokenFunc.
func (mock *EnvMock) CurrentAdminUserToken(ctx context.Context) (*usertoken.Data, error) {
	if mock.CurrentAdminUserTokenFunc == nil {
		panic("EnvMock.CurrentAdminUserTokenFunc: method is nil but Env.CurrentAdminUserToken was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCurrentAdminUserToken.Lock()
	mock.calls.CurrentAdminUserToken = append(mock.calls.CurrentAdminUserToken, callInfo)
	mock.lockCurrentAdminUserToken.Unlock()
	return mock.CurrentAdminUserTokenFunc(ctx)
}

// CurrentAdminUserTokenCalls gets all the calls that were made to CurrentAdminUserToken.
// Check the length with:
//
//	len(mockedEnv.CurrentAdminUserTokenCalls())
func (mock *EnvMock) CurrentAdminUserTokenCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCurrentAdminUserToken.RLock()
	calls = mock.calls.CurrentAdminUserToken
	mock.lockCurrentAdminUserToken.RUnlock()
	return calls
}

// EncryptData calls EncryptDataFunc.
func (mock *EnvMock) EncryptData(plaintext []byte) ([]byte, error) {
	if mock.EncryptDataFunc == nil {
		panic("EnvMock.EncryptDataFunc: method is nil but Env.EncryptData was just called")
	}
	callInfo := struct {
		Plaintext []byte
	}{
		Plaintext: plaintext,
	}
	mock.lockEncryptData.Lock()
	mock.calls.EncryptData = append(mock.calls.EncryptData, callInfo)
	mock.lockEncryptData.Unlock()
	return mock.EncryptDataFunc(plaintext)
}

// EncryptDataCalls gets all the calls that were made to EncryptData.
// Check the length with:
//
//	len(mockedEnv.EncryptDataCalls())
func (mock *EnvMock) EncryptDataCalls() []struct {
	Plaintext []byte
} {
	var calls []struct {
		Plaintext []byte
	}
	mock.lockEncryptData.RLock()
	calls = mock.calls.EncryptData
	mock.lockEncryptData.RUnlock()
	return calls
}

// InsertFederationSecret calls InsertFederationSecretFunc.
func (mock *EnvMock) InsertFederationSecret(ctx context.Context, arg db.InsertFederationSecretParams) (db.FederationSecret, error) {
	if mock.InsertFederationSecretFunc == nil {
		panic("EnvMock.InsertFederationSecretFunc: method is nil but Env.InsertFederationSecret was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.InsertFederationSecretParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockInsertFederationSecret.Lock()
	mock.calls.InsertFederationSecret = append(mock.calls.InsertFederationSecret, callInfo)
	mock.lockInsertFederationSecret.Unlock()
	return mock.InsertFederationSecretFunc(ctx, arg)
}

// InsertFederationSecretCalls gets all the calls that were made to InsertFederationSecret.
// Check the length with:
//
//	len(mockedEnv.InsertFederationSecretCalls())
func (mock *EnvMock) InsertFederationSecretCalls() []struct {
	Ctx context.Context
	Arg db.InsertFederationSecretParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.InsertFederationSecretParams
	}
	mock.lockInsertFederationSecret.RLock()
	calls = mock.calls.InsertFederationSecret
	mock.lockInsertFederationSecret.RUnlock()
	return calls
}
