// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package removefederationsecretsubgraph_test

import (
	"context"
	"sync"
	"trip2g/internal/case/admin/removefederationsecretsubgraph"
	"trip2g/internal/db"
	"trip2g/internal/usertoken"
)

// Ensure, that EnvMock does implement removefederationsecretsubgraph.Env.
// If this is not the case, regenerate this file with moq.
var _ removefederationsecretsubgraph.Env = &EnvMock{}

// EnvMock is a mock implementation of removefederationsecretsubgraph.Env.
//
//	func TestSomethingThatUsesEnv(t *testing.T) {
//
//		// make and configure a mocked removefederationsecretsubgraph.Env
//		mockedEnv := &EnvMock{
//			CurrentAdminUserTokenFunc: func(ctx context.Context) (*usertoken.Data, error) {
//				panic("mock out the CurrentAdminUserToken method")
//			},
//			DeleteFederationSecretSubgraphFunc: func(ctx context.Context, arg db.DeleteFederationSecretSubgraphParams) error {
//				panic("mock out the DeleteFederationSecretSubgraph method")
//			},
//		}
//
//		// use mockedEnv in code that requires removefederationsecretsubgraph.Env
//		// and then make assertions.
//
//	}
type EnvMock struct {
	// CurrentAdminUserTokenFunc mocks the CurrentAdminUserToken method.
	CurrentAdminUserTokenFunc func(ctx context.Context) (*usertoken.Data, error)

	// DeleteFederationSecretSubgraphFunc mocks the DeleteFederationSecretSubgraph method.
	DeleteFederationSecretSubgraphFunc func(ctx context.Context, arg db.DeleteFederationSecretSubgraphParams) error

	// calls tracks calls to the methods.
	calls struct {
		// CurrentAdminUserToken holds details about calls to the CurrentAdminUserToken method.
		CurrentAdminUserToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// DeleteFederationSecretSubgraph holds details about calls to the DeleteFederationSecretSubgraph method.
		DeleteFederationSecretSubgraph []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.DeleteFederationSecretSubgraphParams
		}
	}
	lockCurrentAdminUserToken          sync.RWMutex
	lockDeleteFederationSecretSubgraph sync.RWMutex
}

// CurrentAdminUserToken calls CurrentAdminUserTokenFunc.
func (mock *EnvMock) CurrentAdminUserToken(ctx context.Context) (*usertoken.Data, error) {
	if mock.CurrentAdminUserTokenFunc == nil {
		panic("EnvMock.CurrentAdminUserTokenFunc: method is nil but Env.CurrentAdminUserToken was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCurrentAdminUserToken.Lock()
	mock.calls.CurrentAdminUserToken = append(mock.calls.CurrentAdminUserToken, callInfo)
	mock.lockCurrentAdminUserToken.Unlock()
	return mock.CurrentAdminUserTokenFunc(ctx)
}

// CurrentAdminUserTokenCalls gets all the calls that were made to CurrentAdminUserToken.
// Check the length with:
//
//	len(mockedEnv.CurrentAdminUserTokenCalls())
func (mock *EnvMock) CurrentAdminUserTokenCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCurrentAdminUserToken.RLock()
	calls = mock.calls.CurrentAdminUserToken
	mock.lockCurrentAdminUserToken.RUnlock()
	return calls
}

// DeleteFederationSecretSubgraph calls DeleteFederationSecretSubgraphFunc.
func (mock *EnvMock) DeleteFederationSecretSubgraph(ctx context.Context, arg db.DeleteFederationSecretSubgraphParams) error {
	if mock.DeleteFederationSecretSubgraphFunc == nil {
		panic("EnvMock.DeleteFederationSecretSubgraphFunc: method is nil but Env.DeleteFederationSecretSubgraph was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.DeleteFederationSecretSubgraphParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockDeleteFederationSecretSubgraph.Lock()
	mock.calls.DeleteFederationSecretSubgraph = append(mock.calls.DeleteFederationSecretSubgraph, callInfo)
	mock.lockDeleteFederationSecretSubgraph.Unlock()
	return mock.DeleteFederationSecretSubgraphFunc(ctx, arg)
}

// DeleteFederationSecretSubgraphCalls gets all the calls that were made to DeleteFederationSecretSubgraph.
// Check the length with:
//
//	len(mockedEnv.DeleteFederationSecretSubgraphCalls())
func (mock *EnvMock) DeleteFederationSecretSubgraphCalls() []struct {
	Ctx context.Context
	Arg db.DeleteFederationSecretSubgraphParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.DeleteFederationSecretSubgraphParams
	}
	mock.lockDeleteFederationSecretSubgraph.RLock()
	calls = mock.calls.DeleteFederationSecretSubgraph
	mock.lockDeleteFederationSecretSubgraph.RUnlock()
	return calls
}
