// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type trip2g_admin_subgraph_catalog_listQueryVariables = Exact<{ [key: string]: never; }>;


export type trip2g_admin_subgraph_catalog_listQuery = { __typename?: 'Query', admin: { __typename?: 'AdminQuery', allSubgraphs: { __typename?: 'AdminSubgraphsConnection', nodes: Array<{ __typename: 'AdminSubgraph', id: any, name: string, color?: string | null, createdAt: any }> } } };


export function $trip2g_admin_subgraph_catalog_list(opts?: { revalidate?: boolean }): trip2g_admin_subgraph_catalog_listQuery {
	return $trip2g_gql_request(`query trip2g_admin_subgraph_catalog_list {
  admin {
    allSubgraphs {
      nodes {
        __typename
        id
        name
        color
        createdAt
      }
    }
  }
}`, undefined, opts) as trip2g_admin_subgraph_catalog_listQuery
}

}
