// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package replicareload

import (
	"context"
	"sync"
	"trip2g/internal/db"
	"trip2g/internal/model"
)

// Ensure, that EnvMock does implement Env.
// If this is not the case, regenerate this file with moq.
var _ Env = &EnvMock{}

// EnvMock is a mock implementation of Env.
//
//	func TestSomethingThatUsesEnv(t *testing.T) {
//
//		// make and configure a mocked Env
//		mockedEnv := &EnvMock{
//			NotesReloadSignalFunc: func(ctx context.Context) (db.NotesReloadSignalRow, error) {
//				panic("mock out the NotesReloadSignal method")
//			},
//			PrepareLatestNotesFunc: func(ctx context.Context, partial bool) (*model.NoteViews, error) {
//				panic("mock out the PrepareLatestNotes method")
//			},
//			PrepareLiveNotesFunc: func(ctx context.Context) (*model.NoteViews, error) {
//				panic("mock out the PrepareLiveNotes method")
//			},
//		}
//
//		// use mockedEnv in code that requires Env
//		// and then make assertions.
//
//	}
type EnvMock struct {
	// NotesReloadSignalFunc mocks the NotesReloadSignal method.
	NotesReloadSignalFunc func(ctx context.Context) (db.NotesReloadSignalRow, error)

	// PrepareLatestNotesFunc mocks the PrepareLatestNotes method.
	PrepareLatestNotesFunc func(ctx context.Context, partial bool) (*model.NoteViews, error)

	// PrepareLiveNotesFunc mocks the PrepareLiveNotes method.
	PrepareLiveNotesFunc func(ctx context.Context) (*model.NoteViews, error)

	// calls tracks calls to the methods.
	calls struct {
		// NotesReloadSignal holds details about calls to the NotesReloadSignal method.
		NotesReloadSignal []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// PrepareLatestNotes holds details about calls to the PrepareLatestNotes method.
		PrepareLatestNotes []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Partial is the partial argument value.
			Partial bool
		}
		// PrepareLiveNotes holds details about calls to the PrepareLiveNotes method.
		PrepareLiveNotes []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
	}
	lockNotesReloadSignal  sync.RWMutex
	lockPrepareLatestNotes sync.RWMutex
	lockPrepareLiveNotes   sync.RWMutex
}

// NotesReloadSignal calls NotesReloadSignalFunc.
func (mock *EnvMock) NotesReloadSignal(ctx context.Context) (db.NotesReloadSignalRow, error) {
	if mock.NotesReloadSignalFunc == nil {
		panic("EnvMock.NotesReloadSignalFunc: method is nil but Env.NotesReloadSignal was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockNotesReloadSignal.Lock()
	mock.calls.NotesReloadSignal = append(mock.calls.NotesReloadSignal, callInfo)
	mock.lockNotesReloadSignal.Unlock()
	return mock.NotesReloadSignalFunc(ctx)
}

// NotesReloadSignalCalls gets all the calls that were made to NotesReloadSignal.
// Check the length with:
//
//	len(mockedEnv.NotesReloadSignalCalls())
func (mock *EnvMock) NotesReloadSignalCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockNotesReloadSignal.RLock()
	calls = mock.calls.NotesReloadSignal
	mock.lockNotesReloadSignal.RUnlock()
	return calls
}

// PrepareLatestNotes calls PrepareLatestNotesFunc.
func (mock *EnvMock) PrepareLatestNotes(ctx context.Context, partial bool) (*model.NoteViews, error) {
	if mock.PrepareLatestNotesFunc == nil {
		panic("EnvMock.PrepareLatestNotesFunc: method is nil but Env.PrepareLatestNotes was just called")
	}
	callInfo := struct {
		Ctx     context.Context
		Partial bool
	}{
		Ctx:     ctx,
		Partial: partial,
	}
	mock.lockPrepareLatestNotes.Lock()
	mock.calls.PrepareLatestNotes = append(mock.calls.PrepareLatestNotes, callInfo)
	mock.lockPrepareLatestNotes.Unlock()
	return mock.PrepareLatestNotesFunc(ctx, partial)
}

// PrepareLatestNotesCalls gets all the calls that were made to PrepareLatestNotes.
// Check the length with:
//
//	len(mockedEnv.PrepareLatestNotesCalls())
func (mock *EnvMock) PrepareLatestNotesCalls() []struct {
	Ctx     context.Context
	Partial bool
} {
	var calls []struct {
		Ctx     context.Context
		Partial bool
	}
	mock.lockPrepareLatestNotes.RLock()
	calls = mock.calls.PrepareLatestNotes
	mock.lockPrepareLatestNotes.RUnlock()
	return calls
}

// PrepareLiveNotes calls PrepareLiveNotesFunc.
func (mock *EnvMock) PrepareLiveNotes(ctx context.Context) (*model.NoteViews, error) {
	if mock.PrepareLiveNotesFunc == nil {
		panic("EnvMock.PrepareLiveNotesFunc: method is nil but Env.PrepareLiveNotes was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockPrepareLiveNotes.Lock()
	mock.calls.PrepareLiveNotes = append(mock.calls.PrepareLiveNotes, callInfo)
	mock.lockPrepareLiveNotes.Unlock()
	return mock.PrepareLiveNotesFunc(ctx)
}

// PrepareLiveNotesCalls gets all the calls that were made to PrepareLiveNotes.
// Check the length with:
//
//	len(mockedEnv.PrepareLiveNotesCalls())
func (mock *EnvMock) PrepareLiveNotesCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockPrepareLiveNotes.RLock()
	calls = mock.calls.PrepareLiveNotes
	mock.lockPrepareLiveNotes.RUnlock()
	return calls
}
