// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package completetelegramaccountauth_test

import (
	"context"
	"sync"
	"trip2g/internal/case/admin/completetelegramaccountauth"
	"trip2g/internal/db"
	appmodel "trip2g/internal/model"
	"trip2g/internal/usertoken"
)

// Ensure, that EnvMock does implement completetelegramaccountauth.Env.
// If this is not the case, regenerate this file with moq.
var _ completetelegramaccountauth.Env = &EnvMock{}

// EnvMock is a mock implementation of completetelegramaccountauth.Env.
//
//	func TestSomethingThatUsesEnv(t *testing.T) {
//
//		// make and configure a mocked completetelegramaccountauth.Env
//		mockedEnv := &EnvMock{
//			CurrentAdminUserTokenFunc: func(ctx context.Context) (*usertoken.Data, error) {
//				panic("mock out the CurrentAdminUserToken method")
//			},
//			EncryptDataFunc: func(plaintext []byte) ([]byte, error) {
//				panic("mock out the EncryptData method")
//			},
//			GetTelegramAccountByPhoneFunc: func(ctx context.Context, phone string) (db.TelegramAccount, error) {
//				panic("mock out the GetTelegramAccountByPhone method")
//			},
//			InsertTelegramAccountFunc: func(ctx context.Context, arg db.InsertTelegramAccountParams) (db.TelegramAccount, error) {
//				panic("mock out the InsertTelegramAccount method")
//			},
//			TelegramAccountCompleteAuthFunc: func(ctx context.Context, phone string, code string, password string) (*appmodel.TelegramCompleteAuthResult, error) {
//				panic("mock out the TelegramAccountCompleteAuth method")
//			},
//			TelegramAccountGetAppConfigFunc: func(ctx context.Context, accountID int64) (string, error) {
//				panic("mock out the TelegramAccountGetAppConfig method")
//			},
//			TelegramAccountGetPasswordHintFunc: func(phone string) string {
//				panic("mock out the TelegramAccountGetPasswordHint method")
//			},
//			UpdateTelegramAccountFunc: func(ctx context.Context, arg db.UpdateTelegramAccountParams) error {
//				panic("mock out the UpdateTelegramAccount method")
//			},
//			UpdateTelegramAccountAppConfigFunc: func(ctx context.Context, arg db.UpdateTelegramAccountAppConfigParams) error {
//				panic("mock out the UpdateTelegramAccountAppConfig method")
//			},
//		}
//
//		// use mockedEnv in code that requires completetelegramaccountauth.Env
//		// and then make assertions.
//
//	}
type EnvMock struct {
	// CurrentAdminUserTokenFunc mocks the CurrentAdminUserToken method.
	CurrentAdminUserTokenFunc func(ctx context.Context) (*usertoken.Data, error)

	// EncryptDataFunc mocks the EncryptData method.
	EncryptDataFunc func(plaintext []byte) ([]byte, error)

	// GetTelegramAccountByPhoneFunc mocks the GetTelegramAccountByPhone method.
	GetTelegramAccountByPhoneFunc func(ctx context.Context, phone string) (db.TelegramAccount, error)

	// InsertTelegramAccountFunc mocks the InsertTelegramAccount method.
	InsertTelegramAccountFunc func(ctx context.Context, arg db.InsertTelegramAccountParams) (db.TelegramAccount, error)

	// TelegramAccountCompleteAuthFunc mocks the TelegramAccountCompleteAuth method.
	TelegramAccountCompleteAuthFunc func(ctx context.Context, phone string, code string, password string) (*appmodel.TelegramCompleteAuthResult, error)

	// TelegramAccountGetAppConfigFunc mocks the TelegramAccountGetAppConfig method.
	TelegramAccountGetAppConfigFunc func(ctx context.Context, accountID int64) (string, error)

	// TelegramAccountGetPasswordHintFunc mocks the TelegramAccountGetPasswordHint method.
	TelegramAccountGetPasswordHintFunc func(phone string) string

	// UpdateTelegramAccountFunc mocks the UpdateTelegramAccount method.
	UpdateTelegramAccountFunc func(ctx context.Context, arg db.UpdateTelegramAccountParams) error

	// UpdateTelegramAccountAppConfigFunc mocks the UpdateTelegramAccountAppConfig method.
	UpdateTelegramAccountAppConfigFunc func(ctx context.Context, arg db.UpdateTelegramAccountAppConfigParams) error

	// calls tracks calls to the methods.
	calls struct {
		// CurrentAdminUserToken holds details about calls to the CurrentAdminUserToken method.
		CurrentAdminUserToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// EncryptData holds details about calls to the EncryptData method.
		EncryptData []struct {
			// Plaintext is the plaintext argument value.
			Plaintext []byte
		}
		// GetTelegramAccountByPhone holds details about calls to the GetTelegramAccountByPhone method.
		GetTelegramAccountByPhone []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Phone is the phone argument value.
			Phone string
		}
		// InsertTelegramAccount holds details about calls to the InsertTelegramAccount method.
		InsertTelegramAccount []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.InsertTelegramAccountParams
		}
		// TelegramAccountCompleteAuth holds details about calls to the TelegramAccountCompleteAuth method.
		TelegramAccountCompleteAuth []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Phone is the phone argument value.
			Phone string
			// Code is the code argument value.
			Code string
			// Password is the password argument value.
			Password string
		}
		// TelegramAccountGetAppConfig holds details about calls to the TelegramAccountGetAppConfig method.
		TelegramAccountGetAppConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// AccountID is the accountID argument value.
			AccountID int64
		}
		// TelegramAccountGetPasswordHint holds details about calls to the TelegramAccountGetPasswordHint method.
		TelegramAccountGetPasswordHint []struct {
			// Phone is the phone argument value.
			Phone string
		}
		// UpdateTelegramAccount holds details about calls to the UpdateTelegramAccount method.
		UpdateTelegramAccount []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.UpdateTelegramAccountParams
		}
		// UpdateTelegramAccountAppConfig holds details about calls to the UpdateTelegramAccountAppConfig method.
		UpdateTelegramAccountAppConfig []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.UpdateTelegramAccountAppConfigParams
		}
	}
	lockCurrentAdminUserToken          sync.RWMutex
	lockEncryptData                    sync.RWMutex
	lockGetTelegramAccountByPhone      sync.RWMutex
	lockInsertTelegramAccount          sync.RWMutex
	lockTelegramAccountCompleteAuth    sync.RWMutex
	lockTelegramAccountGetAppConfig    sync.RWMutex
	lockTelegramAccountGetPasswordHint sync.RWMutex
	lockUpdateTelegramAccount          sync.RWMutex
	lockUpdateTelegramAccountAppConfig sync.RWMutex
}

// CurrentAdminUserToken calls CurrentAdminUserTokenFunc.
func (mock *EnvMock) CurrentAdminUserToken(ctx context.Context) (*usertoken.Data, error) {
	if mock.CurrentAdminUserTokenFunc == nil {
		panic("EnvMock.CurrentAdminUserTokenFunc: method is nil but Env.CurrentAdminUserToken was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCurrentAdminUserToken.Lock()
	mock.calls.CurrentAdminUserToken = append(mock.calls.CurrentAdminUserToken, callInfo)
	mock.lockCurrentAdminUserToken.Unlock()
	return mock.CurrentAdminUserTokenFunc(ctx)
}

// CurrentAdminUserTokenCalls gets all the calls that were made to CurrentAdminUserToken.
// Check the length with:
//
//	len(mockedEnv.CurrentAdminUserTokenCalls())
func (mock *EnvMock) CurrentAdminUserTokenCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCurrentAdminUserToken.RLock()
	calls = mock.calls.CurrentAdminUserToken
	mock.lockCurrentAdminUserToken.RUnlock()
	return calls
}

// EncryptData calls EncryptDataFunc.
func (mock *EnvMock) EncryptData(plaintext []byte) ([]byte, error) {
	if mock.EncryptDataFunc == nil {
		panic("EnvMock.EncryptDataFunc: method is nil but Env.EncryptData was just called")
	}
	callInfo := struct {
		Plaintext []byte
	}{
		Plaintext: plaintext,
	}
	mock.lockEncryptData.Lock()
	mock.calls.EncryptData = append(mock.calls.EncryptData, callInfo)
	mock.lockEncryptData.Unlock()
	return mock.EncryptDataFunc(plaintext)
}

// EncryptDataCalls gets all the calls that were made to EncryptData.
// Check the length with:
//
//	len(mockedEnv.EncryptDataCalls())
func (mock *EnvMock) EncryptDataCalls() []struct {
	Plaintext []byte
} {
	var calls []struct {
		Plaintext []byte
	}
	mock.lockEncryptData.RLock()
	calls = mock.calls.EncryptData
	mock.lockEncryptData.RUnlock()
	return calls
}

// GetTelegramAccountByPhone calls GetTelegramAccountByPhoneFunc.
func (mock *EnvMock) GetTelegramAccountByPhone(ctx context.Context, phone string) (db.TelegramAccount, error) {
	if mock.GetTelegramAccountByPhoneFunc == nil {
		panic("EnvMock.GetTelegramAccountByPhoneFunc: method is nil but Env.GetTelegramAccountByPhone was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Phone string
	}{
		Ctx:   ctx,
		Phone: phone,
	}
	mock.lockGetTelegramAccountByPhone.Lock()
	mock.calls.GetTelegramAccountByPhone = append(mock.calls.GetTelegramAccountByPhone, callInfo)
	mock.lockGetTelegramAccountByPhone.Unlock()
	return mock.GetTelegramAccountByPhoneFunc(ctx, phone)
}

// GetTelegramAccountByPhoneCalls gets all the calls that were made to GetTelegramAccountByPhone.
// Check the length with:
//
//	len(mockedEnv.GetTelegramAccountByPhoneCalls())
func (mock *EnvMock) GetTelegramAccountByPhoneCalls() []struct {
	Ctx   context.Context
	Phone string
} {
	var calls []struct {
		Ctx   context.Context
		Phone string
	}
	mock.lockGetTelegramAccountByPhone.RLock()
	calls = mock.calls.GetTelegramAccountByPhone
	mock.lockGetTelegramAccountByPhone.RUnlock()
	return calls
}

// InsertTelegramAccount calls InsertTelegramAccountFunc.
func (mock *EnvMock) InsertTelegramAccount(ctx context.Context, arg db.InsertTelegramAccountParams) (db.TelegramAccount, error) {
	if mock.InsertTelegramAccountFunc == nil {
		panic("EnvMock.InsertTelegramAccountFunc: method is nil but Env.InsertTelegramAccount was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.InsertTelegramAccountParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockInsertTelegramAccount.Lock()
	mock.calls.InsertTelegramAccount = append(mock.calls.InsertTelegramAccount, callInfo)
	mock.lockInsertTelegramAccount.Unlock()
	return mock.InsertTelegramAccountFunc(ctx, arg)
}

// InsertTelegramAccountCalls gets all the calls that were made to InsertTelegramAccount.
// Check the length with:
//
//	len(mockedEnv.InsertTelegramAccountCalls())
func (mock *EnvMock) InsertTelegramAccountCalls() []struct {
	Ctx context.Context
	Arg db.InsertTelegramAccountParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.InsertTelegramAccountParams
	}
	mock.lockInsertTelegramAccount.RLock()
	calls = mock.calls.InsertTelegramAccount
	mock.lockInsertTelegramAccount.RUnlock()
	return calls
}

// TelegramAccountCompleteAuth calls TelegramAccountCompleteAuthFunc.
func (mock *EnvMock) TelegramAccountCompleteAuth(ctx context.Context, phone string, code string, password string) (*appmodel.TelegramCompleteAuthResult, error) {
	if mock.TelegramAccountCompleteAuthFunc == nil {
		panic("EnvMock.TelegramAccountCompleteAuthFunc: method is nil but Env.TelegramAccountCompleteAuth was just called")
	}
	callInfo := struct {
		Ctx      context.Context
		Phone    string
		Code     string
		Password string
	}{
		Ctx:      ctx,
		Phone:    phone,
		Code:     code,
		Password: password,
	}
	mock.lockTelegramAccountCompleteAuth.Lock()
	mock.calls.TelegramAccountCompleteAuth = append(mock.calls.TelegramAccountCompleteAuth, callInfo)
	mock.lockTelegramAccountCompleteAuth.Unlock()
	return mock.TelegramAccountCompleteAuthFunc(ctx, phone, code, password)
}

// TelegramAccountCompleteAuthCalls gets all the calls that were made to TelegramAccountCompleteAuth.
// Check the length with:
//
//	len(mockedEnv.TelegramAccountCompleteAuthCalls())
func (mock *EnvMock) TelegramAccountCompleteAuthCalls() []struct {
	Ctx      context.Context
	Phone    string
	Code     string
	Password string
} {
	var calls []struct {
		Ctx      context.Context
		Phone    string
		Code     string
		Password string
	}
	mock.lockTelegramAccountCompleteAuth.RLock()
	calls = mock.calls.TelegramAccountCompleteAuth
	mock.lockTelegramAccountCompleteAuth.RUnlock()
	return calls
}

// TelegramAccountGetAppConfig calls TelegramAccountGetAppConfigFunc.
func (mock *EnvMock) TelegramAccountGetAppConfig(ctx context.Context, accountID int64) (string, error) {
	if mock.TelegramAccountGetAppConfigFunc == nil {
		panic("EnvMock.TelegramAccountGetAppConfigFunc: method is nil but Env.TelegramAccountGetAppConfig was just called")
	}
	callInfo := struct {
		Ctx       context.Context
		AccountID int64
	}{
		Ctx:       ctx,
		AccountID: accountID,
	}
	mock.lockTelegramAccountGetAppConfig.Lock()
	mock.calls.TelegramAccountGetAppConfig = append(mock.calls.TelegramAccountGetAppConfig, callInfo)
	mock.lockTelegramAccountGetAppConfig.Unlock()
	return mock.TelegramAccountGetAppConfigFunc(ctx, accountID)
}

// TelegramAccountGetAppConfigCalls gets all the calls that were made to TelegramAccountGetAppConfig.
// Check the length with:
//
//	len(mockedEnv.TelegramAccountGetAppConfigCalls())
func (mock *EnvMock) TelegramAccountGetAppConfigCalls() []struct {
	Ctx       context.Context
	AccountID int64
} {
	var calls []struct {
		Ctx       context.Context
		AccountID int64
	}
	mock.lockTelegramAccountGetAppConfig.RLock()
	calls = mock.calls.TelegramAccountGetAppConfig
	mock.lockTelegramAccountGetAppConfig.RUnlock()
	return calls
}

// TelegramAccountGetPasswordHint calls TelegramAccountGetPasswordHintFunc.
func (mock *EnvMock) TelegramAccountGetPasswordHint(phone string) string {
	if mock.TelegramAccountGetPasswordHintFunc == nil {
		panic("EnvMock.TelegramAccountGetPasswordHintFunc: method is nil but Env.TelegramAccountGetPasswordHint was just called")
	}
	callInfo := struct {
		Phone string
	}{
		Phone: phone,
	}
	mock.lockTelegramAccountGetPasswordHint.Lock()
	mock.calls.TelegramAccountGetPasswordHint = append(mock.calls.TelegramAccountGetPasswordHint, callInfo)
	mock.lockTelegramAccountGetPasswordHint.Unlock()
	return mock.TelegramAccountGetPasswordHintFunc(phone)
}

// TelegramAccountGetPasswordHintCalls gets all the calls that were made to TelegramAccountGetPasswordHint.
// Check the length with:
//
//	len(mockedEnv.TelegramAccountGetPasswordHintCalls())
func (mock *EnvMock) TelegramAccountGetPasswordHintCalls() []struct {
	Phone string
} {
	var calls []struct {
		Phone string
	}
	mock.lockTelegramAccountGetPasswordHint.RLock()
	calls = mock.calls.TelegramAccountGetPasswordHint
	mock.lockTelegramAccountGetPasswordHint.RUnlock()
	return calls
}

// UpdateTelegramAccount calls UpdateTelegramAccountFunc.
func (mock *EnvMock) UpdateTelegramAccount(ctx context.Context, arg db.UpdateTelegramAccountParams) error {
	if mock.UpdateTelegramAccountFunc == nil {
		panic("EnvMock.UpdateTelegramAccountFunc: method is nil but Env.UpdateTelegramAccount was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.UpdateTelegramAccountParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpdateTelegramAccount.Lock()
	mock.calls.UpdateTelegramAccount = append(mock.calls.UpdateTelegramAccount, callInfo)
	mock.lockUpdateTelegramAccount.Unlock()
	return mock.UpdateTelegramAccountFunc(ctx, arg)
}

// UpdateTelegramAccountCalls gets all the calls that were made to UpdateTelegramAccount.
// Check the length with:
//
//	len(mockedEnv.UpdateTelegramAccountCalls())
func (mock *EnvMock) UpdateTelegramAccountCalls() []struct {
	Ctx context.Context
	Arg db.UpdateTelegramAccountParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.UpdateTelegramAccountParams
	}
	mock.lockUpdateTelegramAccount.RLock()
	calls = mock.calls.UpdateTelegramAccount
	mock.lockUpdateTelegramAccount.RUnlock()
	return calls
}

// UpdateTelegramAccountAppConfig calls UpdateTelegramAccountAppConfigFunc.
func (mock *EnvMock) UpdateTelegramAccountAppConfig(ctx context.Context, arg db.UpdateTelegramAccountAppConfigParams) error {
	if mock.UpdateTelegramAccountAppConfigFunc == nil {
		panic("EnvMock.UpdateTelegramAccountAppConfigFunc: method is nil but Env.UpdateTelegramAccountAppConfig was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.UpdateTelegramAccountAppConfigParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockUpdateTelegramAccountAppConfig.Lock()
	mock.calls.UpdateTelegramAccountAppConfig = append(mock.calls.UpdateTelegramAccountAppConfig, callInfo)
	mock.lockUpdateTelegramAccountAppConfig.Unlock()
	return mock.UpdateTelegramAccountAppConfigFunc(ctx, arg)
}

// UpdateTelegramAccountAppConfigCalls gets all the calls that were made to UpdateTelegramAccountAppConfig.
// Check the length with:
//
//	len(mockedEnv.UpdateTelegramAccountAppConfigCalls())
func (mock *EnvMock) UpdateTelegramAccountAppConfigCalls() []struct {
	Ctx context.Context
	Arg db.UpdateTelegramAccountAppConfigParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.UpdateTelegramAccountAppConfigParams
	}
	mock.lockUpdateTelegramAccountAppConfig.RLock()
	calls = mock.calls.UpdateTelegramAccountAppConfig
	mock.lockUpdateTelegramAccountAppConfig.RUnlock()
	return calls
}
