// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type trip2g_admin_boostycredentials_catalog_listQueryVariables = Exact<{
  filter?: InputMaybe<AdminBoostyCredentialsFilterInput>;
}>;


export type trip2g_admin_boostycredentials_catalog_listQuery = { __typename?: 'Query', admin: { __typename?: 'AdminQuery', allBoostyCredentials: { __typename?: 'AdminBoostyCredentialsConnection', nodes: Array<{ __typename?: 'AdminBoostyCredentials', id: any, state: BoostyCredentialsStateEnum, deviceId: string, blogName: string, createdAt: any, createdBy: { __typename?: 'AdminUser', id: any, email?: string | null } }> } } };


export function $trip2g_admin_boostycredentials_catalog_list(variables?: trip2g_admin_boostycredentials_catalog_listQueryVariables, opts?: { revalidate?: boolean }): trip2g_admin_boostycredentials_catalog_listQuery {
	return $trip2g_gql_request(`query trip2g_admin_boostycredentials_catalog_list(\u0024filter: AdminBoostyCredentialsFilterInput) {
  admin {
    allBoostyCredentials(filter: \u0024filter) {
      nodes {
        id
        state
        deviceId
        blogName
        createdAt
        createdBy {
          id
          email
        }
      }
    }
  }
}`, variables, opts) as trip2g_admin_boostycredentials_catalog_listQuery
}

}
