// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package graph

import (
	"context"
	"sync"
	"trip2g/internal/db"
	"trip2g/internal/logger"
	appmodel "trip2g/internal/model"
	"trip2g/internal/usertoken"
)

// Ensure, that noteChangesACLEnvMock does implement noteChangesACLEnv.
// If this is not the case, regenerate this file with moq.
var _ noteChangesACLEnv = &noteChangesACLEnvMock{}

// noteChangesACLEnvMock is a mock implementation of noteChangesACLEnv.
//
//	func TestSomethingThatUsesnoteChangesACLEnv(t *testing.T) {
//
//		// make and configure a mocked noteChangesACLEnv
//		mockednoteChangesACLEnv := &noteChangesACLEnvMock{
//			CanReadNoteFunc: func(ctx context.Context, note *appmodel.NoteView) (bool, error) {
//				panic("mock out the CanReadNote method")
//			},
//			LatestNoteViewsFunc: func() *appmodel.NoteViews {
//				panic("mock out the LatestNoteViews method")
//			},
//			LoggerFunc: func() logger.Logger {
//				panic("mock out the Logger method")
//			},
//		}
//
//		// use mockednoteChangesACLEnv in code that requires noteChangesACLEnv
//		// and then make assertions.
//
//	}
type noteChangesACLEnvMock struct {
	// CanReadNoteFunc mocks the CanReadNote method.
	CanReadNoteFunc func(ctx context.Context, note *appmodel.NoteView) (bool, error)

	// LatestNoteViewsFunc mocks the LatestNoteViews method.
	LatestNoteViewsFunc func() *appmodel.NoteViews

	// LoggerFunc mocks the Logger method.
	LoggerFunc func() logger.Logger

	// calls tracks calls to the methods.
	calls struct {
		// CanReadNote holds details about calls to the CanReadNote method.
		CanReadNote []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Note is the note argument value.
			Note *appmodel.NoteView
		}
		// LatestNoteViews holds details about calls to the LatestNoteViews method.
		LatestNoteViews []struct {
		}
		// Logger holds details about calls to the Logger method.
		Logger []struct {
		}
	}
	lockCanReadNote     sync.RWMutex
	lockLatestNoteViews sync.RWMutex
	lockLogger          sync.RWMutex
}

// CanReadNote calls CanReadNoteFunc.
func (mock *noteChangesACLEnvMock) CanReadNote(ctx context.Context, note *appmodel.NoteView) (bool, error) {
	if mock.CanReadNoteFunc == nil {
		panic("noteChangesACLEnvMock.CanReadNoteFunc: method is nil but noteChangesACLEnv.CanReadNote was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Note *appmodel.NoteView
	}{
		Ctx:  ctx,
		Note: note,
	}
	mock.lockCanReadNote.Lock()
	mock.calls.CanReadNote = append(mock.calls.CanReadNote, callInfo)
	mock.lockCanReadNote.Unlock()
	return mock.CanReadNoteFunc(ctx, note)
}

// CanReadNoteCalls gets all the calls that were made to CanReadNote.
// Check the length with:
//
//	len(mockednoteChangesACLEnv.CanReadNoteCalls())
func (mock *noteChangesACLEnvMock) CanReadNoteCalls() []struct {
	Ctx  context.Context
	Note *appmodel.NoteView
} {
	var calls []struct {
		Ctx  context.Context
		Note *appmodel.NoteView
	}
	mock.lockCanReadNote.RLock()
	calls = mock.calls.CanReadNote
	mock.lockCanReadNote.RUnlock()
	return calls
}

// LatestNoteViews calls LatestNoteViewsFunc.
func (mock *noteChangesACLEnvMock) LatestNoteViews() *appmodel.NoteViews {
	if mock.LatestNoteViewsFunc == nil {
		panic("noteChangesACLEnvMock.LatestNoteViewsFunc: method is nil but noteChangesACLEnv.LatestNoteViews was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLatestNoteViews.Lock()
	mock.calls.LatestNoteViews = append(mock.calls.LatestNoteViews, callInfo)
	mock.lockLatestNoteViews.Unlock()
	return mock.LatestNoteViewsFunc()
}

// LatestNoteViewsCalls gets all the calls that were made to LatestNoteViews.
// Check the length with:
//
//	len(mockednoteChangesACLEnv.LatestNoteViewsCalls())
func (mock *noteChangesACLEnvMock) LatestNoteViewsCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLatestNoteViews.RLock()
	calls = mock.calls.LatestNoteViews
	mock.lockLatestNoteViews.RUnlock()
	return calls
}

// Logger calls LoggerFunc.
func (mock *noteChangesACLEnvMock) Logger() logger.Logger {
	if mock.LoggerFunc == nil {
		panic("noteChangesACLEnvMock.LoggerFunc: method is nil but noteChangesACLEnv.Logger was just called")
	}
	callInfo := struct {
	}{}
	mock.lockLogger.Lock()
	mock.calls.Logger = append(mock.calls.Logger, callInfo)
	mock.lockLogger.Unlock()
	return mock.LoggerFunc()
}

// LoggerCalls gets all the calls that were made to Logger.
// Check the length with:
//
//	len(mockednoteChangesACLEnv.LoggerCalls())
func (mock *noteChangesACLEnvMock) LoggerCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockLogger.RLock()
	calls = mock.calls.Logger
	mock.lockLogger.RUnlock()
	return calls
}

// Ensure, that noteChangesAuthEnvMock does implement noteChangesAuthEnv.
// If this is not the case, regenerate this file with moq.
var _ noteChangesAuthEnv = &noteChangesAuthEnvMock{}

// noteChangesAuthEnvMock is a mock implementation of noteChangesAuthEnv.
//
//	func TestSomethingThatUsesnoteChangesAuthEnv(t *testing.T) {
//
//		// make and configure a mocked noteChangesAuthEnv
//		mockednoteChangesAuthEnv := &noteChangesAuthEnvMock{
//			ApiKeyByValueFunc: func(ctx context.Context, value string) (db.ApiKey, error) {
//				panic("mock out the ApiKeyByValue method")
//			},
//			CurrentUserTokenFunc: func(ctx context.Context) (*usertoken.Data, error) {
//				panic("mock out the CurrentUserToken method")
//			},
//			InsertAPIKeyLogFunc: func(ctx context.Context, arg db.InsertAPIKeyLogParams) error {
//				panic("mock out the InsertAPIKeyLog method")
//			},
//			ShortAPITokenSecretFunc: func() string {
//				panic("mock out the ShortAPITokenSecret method")
//			},
//			UpsertAPIKeyLogActionFunc: func(ctx context.Context, name string) error {
//				panic("mock out the UpsertAPIKeyLogAction method")
//			},
//			UpsertAPIKeyLogIPFunc: func(ctx context.Context, ip string) error {
//				panic("mock out the UpsertAPIKeyLogIP method")
//			},
//		}
//
//		// use mockednoteChangesAuthEnv in code that requires noteChangesAuthEnv
//		// and then make assertions.
//
//	}
type noteChangesAuthEnvMock struct {
	// ApiKeyByValueFunc mocks the ApiKeyByValue method.
	ApiKeyByValueFunc func(ctx context.Context, value string) (db.ApiKey, error)

	// CurrentUserTokenFunc mocks the CurrentUserToken method.
	CurrentUserTokenFunc func(ctx context.Context) (*usertoken.Data, error)

	// InsertAPIKeyLogFunc mocks the InsertAPIKeyLog method.
	InsertAPIKeyLogFunc func(ctx context.Context, arg db.InsertAPIKeyLogParams) error

	// ShortAPITokenSecretFunc mocks the ShortAPITokenSecret method.
	ShortAPITokenSecretFunc func() string

	// UpsertAPIKeyLogActionFunc mocks the UpsertAPIKeyLogAction method.
	UpsertAPIKeyLogActionFunc func(ctx context.Context, name string) error

	// UpsertAPIKeyLogIPFunc mocks the UpsertAPIKeyLogIP method.
	UpsertAPIKeyLogIPFunc func(ctx context.Context, ip string) error

	// calls tracks calls to the methods.
	calls struct {
		// ApiKeyByValue holds details about calls to the ApiKeyByValue method.
		ApiKeyByValue []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Value is the value argument value.
			Value string
		}
		// CurrentUserToken holds details about calls to the CurrentUserToken method.
		CurrentUserToken []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
		}
		// InsertAPIKeyLog holds details about calls to the InsertAPIKeyLog method.
		InsertAPIKeyLog []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Arg is the arg argument value.
			Arg db.InsertAPIKeyLogParams
		}
		// ShortAPITokenSecret holds details about calls to the ShortAPITokenSecret method.
		ShortAPITokenSecret []struct {
		}
		// UpsertAPIKeyLogAction holds details about calls to the UpsertAPIKeyLogAction method.
		UpsertAPIKeyLogAction []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Name is the name argument value.
			Name string
		}
		// UpsertAPIKeyLogIP holds details about calls to the UpsertAPIKeyLogIP method.
		UpsertAPIKeyLogIP []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// IP is the ip argument value.
			IP string
		}
	}
	lockApiKeyByValue         sync.RWMutex
	lockCurrentUserToken      sync.RWMutex
	lockInsertAPIKeyLog       sync.RWMutex
	lockShortAPITokenSecret   sync.RWMutex
	lockUpsertAPIKeyLogAction sync.RWMutex
	lockUpsertAPIKeyLogIP     sync.RWMutex
}

// ApiKeyByValue calls ApiKeyByValueFunc.
func (mock *noteChangesAuthEnvMock) ApiKeyByValue(ctx context.Context, value string) (db.ApiKey, error) {
	if mock.ApiKeyByValueFunc == nil {
		panic("noteChangesAuthEnvMock.ApiKeyByValueFunc: method is nil but noteChangesAuthEnv.ApiKeyByValue was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		Value string
	}{
		Ctx:   ctx,
		Value: value,
	}
	mock.lockApiKeyByValue.Lock()
	mock.calls.ApiKeyByValue = append(mock.calls.ApiKeyByValue, callInfo)
	mock.lockApiKeyByValue.Unlock()
	return mock.ApiKeyByValueFunc(ctx, value)
}

// ApiKeyByValueCalls gets all the calls that were made to ApiKeyByValue.
// Check the length with:
//
//	len(mockednoteChangesAuthEnv.ApiKeyByValueCalls())
func (mock *noteChangesAuthEnvMock) ApiKeyByValueCalls() []struct {
	Ctx   context.Context
	Value string
} {
	var calls []struct {
		Ctx   context.Context
		Value string
	}
	mock.lockApiKeyByValue.RLock()
	calls = mock.calls.ApiKeyByValue
	mock.lockApiKeyByValue.RUnlock()
	return calls
}

// CurrentUserToken calls CurrentUserTokenFunc.
func (mock *noteChangesAuthEnvMock) CurrentUserToken(ctx context.Context) (*usertoken.Data, error) {
	if mock.CurrentUserTokenFunc == nil {
		panic("noteChangesAuthEnvMock.CurrentUserTokenFunc: method is nil but noteChangesAuthEnv.CurrentUserToken was just called")
	}
	callInfo := struct {
		Ctx context.Context
	}{
		Ctx: ctx,
	}
	mock.lockCurrentUserToken.Lock()
	mock.calls.CurrentUserToken = append(mock.calls.CurrentUserToken, callInfo)
	mock.lockCurrentUserToken.Unlock()
	return mock.CurrentUserTokenFunc(ctx)
}

// CurrentUserTokenCalls gets all the calls that were made to CurrentUserToken.
// Check the length with:
//
//	len(mockednoteChangesAuthEnv.CurrentUserTokenCalls())
func (mock *noteChangesAuthEnvMock) CurrentUserTokenCalls() []struct {
	Ctx context.Context
} {
	var calls []struct {
		Ctx context.Context
	}
	mock.lockCurrentUserToken.RLock()
	calls = mock.calls.CurrentUserToken
	mock.lockCurrentUserToken.RUnlock()
	return calls
}

// InsertAPIKeyLog calls InsertAPIKeyLogFunc.
func (mock *noteChangesAuthEnvMock) InsertAPIKeyLog(ctx context.Context, arg db.InsertAPIKeyLogParams) error {
	if mock.InsertAPIKeyLogFunc == nil {
		panic("noteChangesAuthEnvMock.InsertAPIKeyLogFunc: method is nil but noteChangesAuthEnv.InsertAPIKeyLog was just called")
	}
	callInfo := struct {
		Ctx context.Context
		Arg db.InsertAPIKeyLogParams
	}{
		Ctx: ctx,
		Arg: arg,
	}
	mock.lockInsertAPIKeyLog.Lock()
	mock.calls.InsertAPIKeyLog = append(mock.calls.InsertAPIKeyLog, callInfo)
	mock.lockInsertAPIKeyLog.Unlock()
	return mock.InsertAPIKeyLogFunc(ctx, arg)
}

// InsertAPIKeyLogCalls gets all the calls that were made to InsertAPIKeyLog.
// Check the length with:
//
//	len(mockednoteChangesAuthEnv.InsertAPIKeyLogCalls())
func (mock *noteChangesAuthEnvMock) InsertAPIKeyLogCalls() []struct {
	Ctx context.Context
	Arg db.InsertAPIKeyLogParams
} {
	var calls []struct {
		Ctx context.Context
		Arg db.InsertAPIKeyLogParams
	}
	mock.lockInsertAPIKeyLog.RLock()
	calls = mock.calls.InsertAPIKeyLog
	mock.lockInsertAPIKeyLog.RUnlock()
	return calls
}

// ShortAPITokenSecret calls ShortAPITokenSecretFunc.
func (mock *noteChangesAuthEnvMock) ShortAPITokenSecret() string {
	if mock.ShortAPITokenSecretFunc == nil {
		panic("noteChangesAuthEnvMock.ShortAPITokenSecretFunc: method is nil but noteChangesAuthEnv.ShortAPITokenSecret was just called")
	}
	callInfo := struct {
	}{}
	mock.lockShortAPITokenSecret.Lock()
	mock.calls.ShortAPITokenSecret = append(mock.calls.ShortAPITokenSecret, callInfo)
	mock.lockShortAPITokenSecret.Unlock()
	return mock.ShortAPITokenSecretFunc()
}

// ShortAPITokenSecretCalls gets all the calls that were made to ShortAPITokenSecret.
// Check the length with:
//
//	len(mockednoteChangesAuthEnv.ShortAPITokenSecretCalls())
func (mock *noteChangesAuthEnvMock) ShortAPITokenSecretCalls() []struct {
} {
	var calls []struct {
	}
	mock.lockShortAPITokenSecret.RLock()
	calls = mock.calls.ShortAPITokenSecret
	mock.lockShortAPITokenSecret.RUnlock()
	return calls
}

// UpsertAPIKeyLogAction calls UpsertAPIKeyLogActionFunc.
func (mock *noteChangesAuthEnvMock) UpsertAPIKeyLogAction(ctx context.Context, name string) error {
	if mock.UpsertAPIKeyLogActionFunc == nil {
		panic("noteChangesAuthEnvMock.UpsertAPIKeyLogActionFunc: method is nil but noteChangesAuthEnv.UpsertAPIKeyLogAction was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Name string
	}{
		Ctx:  ctx,
		Name: name,
	}
	mock.lockUpsertAPIKeyLogAction.Lock()
	mock.calls.UpsertAPIKeyLogAction = append(mock.calls.UpsertAPIKeyLogAction, callInfo)
	mock.lockUpsertAPIKeyLogAction.Unlock()
	return mock.UpsertAPIKeyLogActionFunc(ctx, name)
}

// UpsertAPIKeyLogActionCalls gets all the calls that were made to UpsertAPIKeyLogAction.
// Check the length with:
//
//	len(mockednoteChangesAuthEnv.UpsertAPIKeyLogActionCalls())
func (mock *noteChangesAuthEnvMock) UpsertAPIKeyLogActionCalls() []struct {
	Ctx  context.Context
	Name string
} {
	var calls []struct {
		Ctx  context.Context
		Name string
	}
	mock.lockUpsertAPIKeyLogAction.RLock()
	calls = mock.calls.UpsertAPIKeyLogAction
	mock.lockUpsertAPIKeyLogAction.RUnlock()
	return calls
}

// UpsertAPIKeyLogIP calls UpsertAPIKeyLogIPFunc.
func (mock *noteChangesAuthEnvMock) UpsertAPIKeyLogIP(ctx context.Context, ip string) error {
	if mock.UpsertAPIKeyLogIPFunc == nil {
		panic("noteChangesAuthEnvMock.UpsertAPIKeyLogIPFunc: method is nil but noteChangesAuthEnv.UpsertAPIKeyLogIP was just called")
	}
	callInfo := struct {
		Ctx context.Context
		IP  string
	}{
		Ctx: ctx,
		IP:  ip,
	}
	mock.lockUpsertAPIKeyLogIP.Lock()
	mock.calls.UpsertAPIKeyLogIP = append(mock.calls.UpsertAPIKeyLogIP, callInfo)
	mock.lockUpsertAPIKeyLogIP.Unlock()
	return mock.UpsertAPIKeyLogIPFunc(ctx, ip)
}

// UpsertAPIKeyLogIPCalls gets all the calls that were made to UpsertAPIKeyLogIP.
// Check the length with:
//
//	len(mockednoteChangesAuthEnv.UpsertAPIKeyLogIPCalls())
func (mock *noteChangesAuthEnvMock) UpsertAPIKeyLogIPCalls() []struct {
	Ctx context.Context
	IP  string
} {
	var calls []struct {
		Ctx context.Context
		IP  string
	}
	mock.lockUpsertAPIKeyLogIP.RLock()
	calls = mock.calls.UpsertAPIKeyLogIP
	mock.lockUpsertAPIKeyLogIP.RUnlock()
	return calls
}
