// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type trip2g_auth_oauth_buttons_urlsQueryVariables = Exact<{
  input: OAuthUrlInput;
}>;


export type trip2g_auth_oauth_buttons_urlsQuery = { __typename?: 'Query', googleAuthUrl: { __typename?: 'OAuthUrlPayload', authUrl?: string | null }, githubAuthUrl: { __typename?: 'OAuthUrlPayload', authUrl?: string | null }, oidcAuthUrl: { __typename?: 'OAuthUrlPayload', authUrl?: string | null } };


export function $trip2g_auth_oauth_buttons_urls(variables: trip2g_auth_oauth_buttons_urlsQueryVariables, opts?: { revalidate?: boolean }): trip2g_auth_oauth_buttons_urlsQuery {
	return $trip2g_gql_request(`query trip2g_auth_oauth_buttons_urls(\u0024input: OAuthUrlInput!) {
  googleAuthUrl(input: \u0024input) {
    authUrl
  }
  githubAuthUrl(input: \u0024input) {
    authUrl
  }
  oidcAuthUrl(input: \u0024input) {
    authUrl
  }
}`, variables, opts) as trip2g_auth_oauth_buttons_urlsQuery
}

}
