// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type trip2g_admin_config_show_save_stringMutationVariables = Exact<{
  input: SetConfigStringValueInput;
}>;


export type trip2g_admin_config_show_save_stringMutation = { __typename?: 'Mutation', admin: { __typename?: 'AdminMutation', setConfigStringValue: { __typename: 'ErrorPayload', message: string } | { __typename: 'SetConfigStringValueSuccess', configValue: { __typename?: 'AdminConfigStringValue', id: string, value: string, updatedAt?: any | null } } } };


export function $trip2g_admin_config_show_save_string(variables: trip2g_admin_config_show_save_stringMutationVariables, opts?: { revalidate?: boolean }): trip2g_admin_config_show_save_stringMutation {
	return $trip2g_gql_request(`mutation trip2g_admin_config_show_save_string(\u0024input: SetConfigStringValueInput!) {
  admin {
    setConfigStringValue(input: \u0024input) {
      __typename
      ... on SetConfigStringValueSuccess {
        configValue {
          id
          value
          updatedAt
        }
      }
      ... on ErrorPayload {
        message
      }
    }
  }
}`, variables, opts) as trip2g_admin_config_show_save_stringMutation
}

}
