// Code generated by gencmd from ./gencmd/views/endpoints.qtpl; DO NOT EDIT.
//
// This file was auto-generated. Any manual changes will be lost.
// To regenerate, run: go run ./internal/router/gencmd
package router

import (
	downloadonboardingvaultdownloadonboardingvault "trip2g/internal/case/downloadonboardingvault"
	handlegithubcallbackhandlegithubcallback "trip2g/internal/case/handlegithubcallback"
	handlegithubstarthandlegithubstart "trip2g/internal/case/handlegithubstart"
	handlegooglecallbackhandlegooglecallback "trip2g/internal/case/handlegooglecallback"
	handlegooglestarthandlegooglestart "trip2g/internal/case/handlegooglestart"
	handleoidccallbackhandleoidccallback "trip2g/internal/case/handleoidccallback"
	handleoidcstarthandleoidcstart "trip2g/internal/case/handleoidcstart"
	mcpmcp "trip2g/internal/case/mcp"
	processnowpaymentsipnprocessnowpaymentsipn "trip2g/internal/case/processnowpaymentsipn"
	processpatreonwebhookprocesspatreonwebhook "trip2g/internal/case/processpatreonwebhook"
	render404render404 "trip2g/internal/case/render404"
	renderadminpagerenderadminpage "trip2g/internal/case/renderadminpage"
	rendernotepagerendernotepage "trip2g/internal/case/rendernotepage"
	rendersearchpagerendersearchpage "trip2g/internal/case/rendersearchpage"
	signinbyhatsigninbyhat "trip2g/internal/case/signinbyhat"
	renderlayoutpreviewrenderlayoutpreview "trip2g/internal/case/admin/renderlayoutpreview"
	renderpreviewrenderpreview "trip2g/internal/case/admin/renderpreview"
	revokeusersubgraphaccessrevokeusersubgraphaccess "trip2g/internal/case/admin/revokeusersubgraphaccess"
	federationtopologyfederationtopology "trip2g/internal/case/system/federationtopology"
)

var endpoints = []Endpoint{
	&downloadonboardingvaultdownloadonboardingvault.Endpoint{},
	&handlegithubcallbackhandlegithubcallback.Endpoint{},
	&handlegithubstarthandlegithubstart.Endpoint{},
	&handlegooglecallbackhandlegooglecallback.Endpoint{},
	&handlegooglestarthandlegooglestart.Endpoint{},
	&handleoidccallbackhandleoidccallback.Endpoint{},
	&handleoidcstarthandleoidcstart.Endpoint{},
	&mcpmcp.Endpoint{},
	&mcpmcp.GetEndpoint{},
	&processnowpaymentsipnprocessnowpaymentsipn.Endpoint{},
	&processpatreonwebhookprocesspatreonwebhook.Endpoint{},
	&render404render404.Endpoint{},
	&renderadminpagerenderadminpage.Endpoint{},
	&renderadminpagerenderadminpage.GetEndpoint{},
	&rendernotepagerendernotepage.Endpoint{},
	&rendersearchpagerendersearchpage.Endpoint{},
	&signinbyhatsigninbyhat.Endpoint{},
	&renderlayoutpreviewrenderlayoutpreview.Endpoint{},
	&renderpreviewrenderpreview.Endpoint{},
	&renderpreviewrenderpreview.GetEndpoint{},
	&revokeusersubgraphaccessrevokeusersubgraphaccess.Endpoint{},
	&federationtopologyfederationtopology.Endpoint{},
}

type RoutesEnv interface {
	downloadonboardingvaultdownloadonboardingvault.Env
	handlegithubcallbackhandlegithubcallback.Env
	handlegithubstarthandlegithubstart.Env
	handlegooglecallbackhandlegooglecallback.Env
	handlegooglestarthandlegooglestart.Env
	handleoidccallbackhandleoidccallback.Env
	handleoidcstarthandleoidcstart.Env
	mcpmcp.Env
	processnowpaymentsipnprocessnowpaymentsipn.Env
	processpatreonwebhookprocesspatreonwebhook.Env
	render404render404.Env
	renderadminpagerenderadminpage.Env
	rendernotepagerendernotepage.Env
	rendersearchpagerendersearchpage.Env
	signinbyhatsigninbyhat.Env
	renderlayoutpreviewrenderlayoutpreview.Env
	renderpreviewrenderpreview.Env
	revokeusersubgraphaccessrevokeusersubgraphaccess.Env
	federationtopologyfederationtopology.Env
}

