// Code generated by gencmd from ./gencmd/views/endpoints.qtpl; DO NOT EDIT.
//
// This file was auto-generated. Any manual changes will be lost.
// To regenerate, run: go run ./internal/router/gencmd
package router

import (
	getnotehashesgetnotehashes "trip2g/internal/case/getnotehashes"
	meme "trip2g/internal/case/me"
	pushnotespushnotes "trip2g/internal/case/pushnotes"
	rendernotepagerendernotepage "trip2g/internal/case/rendernotepage"
	createoffercreateoffer "trip2g/internal/case/admin/createoffer"
	createusersubgraphaccesscreateusersubgraphaccess "trip2g/internal/case/admin/createusersubgraphaccess"
	deleteofferdeleteoffer "trip2g/internal/case/admin/deleteoffer"
	getpagegetpage "trip2g/internal/case/admin/getpage"
	listnotepathslistnotepaths "trip2g/internal/case/admin/listnotepaths"
	listofferslistoffers "trip2g/internal/case/admin/listoffers"
	listsubgraphslistsubgraphs "trip2g/internal/case/admin/listsubgraphs"
	listuserslistusers "trip2g/internal/case/admin/listusers"
	renderpagerenderpage "trip2g/internal/case/admin/renderpage"
	revokeusersubgraphaccessrevokeusersubgraphaccess "trip2g/internal/case/admin/revokeusersubgraphaccess"
	updateofferupdateoffer "trip2g/internal/case/admin/updateoffer"
	updatesubgraphupdatesubgraph "trip2g/internal/case/admin/updatesubgraph"

	"trip2g/internal/logger"
)

var endpoints = []Endpoint{
	&getnotehashesgetnotehashes.Endpoint{},
	&meme.Endpoint{},
	&pushnotespushnotes.Endpoint{},
	&rendernotepagerendernotepage.Endpoint{},
	&createoffercreateoffer.Endpoint{},
	&createusersubgraphaccesscreateusersubgraphaccess.Endpoint{},
	&deleteofferdeleteoffer.Endpoint{},
	&getpagegetpage.Endpoint{},
	&listnotepathslistnotepaths.Endpoint{},
	&listofferslistoffers.Endpoint{},
	&listsubgraphslistsubgraphs.Endpoint{},
	&listuserslistusers.Endpoint{},
	&renderpagerenderpage.Endpoint{},
	&revokeusersubgraphaccessrevokeusersubgraphaccess.Endpoint{},
	&updateofferupdateoffer.Endpoint{},
	&updatesubgraphupdatesubgraph.Endpoint{},
}

type Env interface {
	getnotehashesgetnotehashes.Env
	meme.Env
	pushnotespushnotes.Env
	rendernotepagerendernotepage.Env
	createoffercreateoffer.Env
	createusersubgraphaccesscreateusersubgraphaccess.Env
	deleteofferdeleteoffer.Env
	getpagegetpage.Env
	listnotepathslistnotepaths.Env
	listofferslistoffers.Env
	listsubgraphslistsubgraphs.Env
	listuserslistusers.Env
	renderpagerenderpage.Env
	revokeusersubgraphaccessrevokeusersubgraphaccess.Env
	updateofferupdateoffer.Env
	updatesubgraphupdatesubgraph.Env

	Logger() logger.Logger
}

