// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: queries.sql

package db

import (
	"context"
)

const incrementNoteVersionCount = `-- name: IncrementNoteVersionCount :one
update note_paths
   set version_count = version_count + 1
 where path = ?
returning version_count, id
`

type IncrementNoteVersionCountRow struct {
	VersionCount int64
	ID           int64
}

func (q *Queries) IncrementNoteVersionCount(ctx context.Context, path string) (IncrementNoteVersionCountRow, error) {
	row := q.db.QueryRowContext(ctx, incrementNoteVersionCount, path)
	var i IncrementNoteVersionCountRow
	err := row.Scan(&i.VersionCount, &i.ID)
	return i, err
}

const insertNotePath = `-- name: InsertNotePath :exec
insert into note_paths (path, path_hash)
values (?, ?)
`

type InsertNotePathParams struct {
	Path     string
	PathHash string
}

func (q *Queries) InsertNotePath(ctx context.Context, arg InsertNotePathParams) error {
	_, err := q.db.ExecContext(ctx, insertNotePath, arg.Path, arg.PathHash)
	return err
}

const insertNoteVersion = `-- name: InsertNoteVersion :exec
insert into note_versions (path_id, version, content, content_hash)
values (?, ?, ?, ?)
`

type InsertNoteVersionParams struct {
	PathID      int64
	Version     int64
	Content     string
	ContentHash string
}

func (q *Queries) InsertNoteVersion(ctx context.Context, arg InsertNoteVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertNoteVersion,
		arg.PathID,
		arg.Version,
		arg.Content,
		arg.ContentHash,
	)
	return err
}
