// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package listsecretkeys_test

import (
	"context"
	"sync"
	"trip2g/internal/case/admin/listsecretkeys"
)

// Ensure, that EnvMock does implement listsecretkeys.Env.
// If this is not the case, regenerate this file with moq.
var _ listsecretkeys.Env = &EnvMock{}

// EnvMock is a mock implementation of listsecretkeys.Env.
//
//	func TestSomethingThatUsesEnv(t *testing.T) {
//
//		// make and configure a mocked listsecretkeys.Env
//		mockedEnv := &EnvMock{
//			ListSecretKeysFunc: func(ctx context.Context, like string) ([]string, error) {
//				panic("mock out the ListSecretKeys method")
//			},
//		}
//
//		// use mockedEnv in code that requires listsecretkeys.Env
//		// and then make assertions.
//
//	}
type EnvMock struct {
	// ListSecretKeysFunc mocks the ListSecretKeys method.
	ListSecretKeysFunc func(ctx context.Context, like string) ([]string, error)

	// calls tracks calls to the methods.
	calls struct {
		// ListSecretKeys holds details about calls to the ListSecretKeys method.
		ListSecretKeys []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// Like is the like argument value.
			Like string
		}
	}
	lockListSecretKeys sync.RWMutex
}

// ListSecretKeys calls ListSecretKeysFunc.
func (mock *EnvMock) ListSecretKeys(ctx context.Context, like string) ([]string, error) {
	if mock.ListSecretKeysFunc == nil {
		panic("EnvMock.ListSecretKeysFunc: method is nil but Env.ListSecretKeys was just called")
	}
	callInfo := struct {
		Ctx  context.Context
		Like string
	}{
		Ctx:  ctx,
		Like: like,
	}
	mock.lockListSecretKeys.Lock()
	mock.calls.ListSecretKeys = append(mock.calls.ListSecretKeys, callInfo)
	mock.lockListSecretKeys.Unlock()
	return mock.ListSecretKeysFunc(ctx, like)
}

// ListSecretKeysCalls gets all the calls that were made to ListSecretKeys.
// Check the length with:
//
//	len(mockedEnv.ListSecretKeysCalls())
func (mock *EnvMock) ListSecretKeysCalls() []struct {
	Ctx  context.Context
	Like string
} {
	var calls []struct {
		Ctx  context.Context
		Like string
	}
	mock.lockListSecretKeys.RLock()
	calls = mock.calls.ListSecretKeys
	mock.lockListSecretKeys.RUnlock()
	return calls
}
