// AUTO-GENERATED by `npm run codegen:ui` - do not edit.
namespace $ {

export type trip2g_admin_federation_button_rotate_saveMutationVariables = Exact<{
  kid: Scalars['String']['input'];
}>;


export type trip2g_admin_federation_button_rotate_saveMutation = { __typename?: 'Mutation', admin: { __typename?: 'AdminMutation', data: { __typename: 'ErrorPayload', message: string } | { __typename: 'RotateFederationSecretPayload', kid: string } } };


export function $trip2g_admin_federation_button_rotate_save(variables: trip2g_admin_federation_button_rotate_saveMutationVariables, opts?: { revalidate?: boolean }): trip2g_admin_federation_button_rotate_saveMutation {
	return $trip2g_gql_request(`mutation trip2g_admin_federation_button_rotate_save(\u0024kid: String!) {
  admin {
    data: rotateFederationSecret(kid: \u0024kid) {
      __typename
      ... on ErrorPayload {
        message
      }
      ... on RotateFederationSecretPayload {
        kid
      }
    }
  }
}`, variables, opts) as trip2g_admin_federation_button_rotate_saveMutation
}

}
